### ISSUE TITLE
Single call for Image buttons

### ISSUE THREAD

**Issue by chopra-austin-west-mec** [jarvisteach/appJar#106]
can you implement a way of having a button be an image instead of a text button?

something like 
`app.addButtonImage(name, imagePath, function)`

**Comment by jarvisteach** [comment]
This feature actually already exists...
Just add a button as normal, then call ```.setButtonImage(button, fileName)```

Check out the docs here: http://appjar.info/pythonWidgets/#button

**Comment by jarvisteach** [comment]
But, let's add an additional function call to wrap the two into one, as suggested...
