### ISSUE TITLE
way to resize images

### ISSUE THREAD

**Issue by chopra-austin-west-mec** [jarvisteach/appJar#107]
can you implement a way of resizing images or have it so I don't need to go into photoshop and resize the image to make it fit

**Comment by jarvisteach** [comment]
In the current implementation, image support is VERY rudimentary - it relies on tinter's inbuilt classes, plus a couple of simple things I found online...

However, you do have a couple of options open to you:
```.setImageSize(img, width, height)``` will crop an image to fit the specified dimensions
```.zoomImage(image, size)``` will allow you to scale the image (up or down)

Check out the docs for a bit more info: http://appjar.info/pythonImages/#change-images

Long-term, I'm planning to link up with other libraries (PIL & PyGame) to give much better image support - but that will be much closer to the 1.0 release...

**Comment by chopra-austin-west-mec** [comment]
ok
