### ISSUE TITLE
AutoEntry blocked while typing

### ISSUE THREAD

**Issue by jacobthetechy** [jarvisteach/appJar#110]
When you start typing into the entry field of a autoentry the entry box is blocked an you cant see what your typing. Is there a possibility of offsetting there the words are shown so you can see the entry box?

*edit:
This is only an issue if the entry is at the bottom of the window

**Comment by jarvisteach** [comment]
Upon a quick investigation (on OSX, with python 2.7 & 3.4), I don't quite see the issue you mention. The entryBox is always visible, but the drop-down of options gets hidden?

```
app = gui()
options=["apple", "ape", "apricot", "applause", "add", "address", "adept"]
app.addAutoEntry('Entry', options)
app.setFocus('Entry')
app.go()
```

Is this what you mean? Or, are you saying that the entryBox gets covered by the options drop-down?

Either way, I think the issues are related...

The drop-down is simply a listBox widget that is (meant to be) temporarily shown over the top of the widgets beneath the entry box.

It can't exists outside the bounds of the appJar window. So, if there's no space to show it under the entryBox (in OSX at least), then it gets hidden. I'll investigate in Windows, to see if there is different behaviour (with it being drawn over the top of the entry box?).

One solution is to always ensure you have space underneath the entry, to show the drop-down.

An extra feature, could be to have the listBox appear above the entry if necessary (& possible) - this may not involve too much re-engineering...

An alternative feature would be to make the window extend to accommodate the listBox. Again, not too hard, but perhaps better left up to the developer to decide on window size?

Other than those three options, I don't really see a solution. I don't think a widget can exist outside the bounds of the tkinter window? And I don't think spawning an extra window to show the options would work well enough (or look good enough) to be worth the effort.

I need to investigate in Windows first, to see what the behaviour is...

**Comment by jarvisteach** [comment]
One other thought, would be to limit/configure the number of rows in the drop-down? appJar could try to identify how many rows to show, or the user could specify if they know they have space constraints...

**Comment by jarvisteach** [comment]
appJar uses winfo_height() combined with winfo_y() (in the makeListBox function) to determine where to place the listBox. Do these work on Windows? Might need to look at winfo_reqheight() ??

**Comment by jacobthetechy** [comment]
> Or, are you saying that the entryBox gets covered by the options drop-down?

Yes this is what I was seeing. I realize this was due in part to my negligence in not realizing I was making such a small window and expecting the window to resize when the options appeared.

> An extra feature, could be to have the listBox appear above the entry if necessary (& possible) - this may not involve too much re-engineering...

I believe this would be a better solution for aesthetics. 

My thoughts on the behavior on the AutoEntry. It should look like and EntryBox and OptionBox combination. As you type it only show matches (just as it does now), but also have the drop down for selection. You should also be able to pass a max number of rows to be shown with the ability to scroll through all the options.  

Or create a new type of entry called addEntryListBox() where this behavior available. 

Either way the OptionBox needs to have some way to limit the number of rows being displayed. The DatePicker would benefit from this as well. That way it would not show 31 options and take up most of the screen/window when selecting a date.

**Comment by jarvisteach** [comment]
OK - added feature to limit the number of rows.
Still need to investigate positioning in windows.
Will split out ideas to scroll up, addEntryListBox() & modify date picker  as new feature requests.

**Comment by lieuzhenghong** [comment]
In my opinion, the option box shouldn't be visible when the field is not in focus.

Not in focus
![image](https://cloud.githubusercontent.com/assets/7903071/24889181/22bb27bc-1e9b-11e7-8a7a-af36f27e0810.png)

In focus
![image](https://cloud.githubusercontent.com/assets/7903071/24889190/322b4dbc-1e9b-11e7-8419-ad11e9b4a55a.png)

**Comment by jarvisteach** [comment]
@lieuzhenghong - this is definitely not intended behaviour!

It's also not the behaviour I see on OSX (10.11.6) python 2.7.13 & 3.6.1 or Linux(Raspbian) python 2.7.9 or 3.4.2. What platform, version of python, version of appJar are you running?

In appJar, the `FocusOut` event is bound to `.closeList()` - so the moment focus leaves the Entry, the listBox should be destroyed...

Equally, showing the list box is bound to a trace on the textVar, so it should only be visible when at least one character is present in the entry or the arrow keys are pressed...

Can you try out one of my test programs: https://github.com/jarvisteach/appJar/blob/appJar/examples/1_autoEntry.py

The 1st & 7th entries are AutoEntries...

**Comment by lieuzhenghong** [comment]
@jarvisteach Yours looks fine for me. I am using Python 3.5.2+, Ubuntu 16.10, 
`pip3 show appjar`
Name: appJar
Version: 0.52
Summary: A GUI wrapper for tkinter
Home-page: http://appJar.info
Author: Richard Jarvis
Author-email: info@appjar.info
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires:

**Comment by jarvisteach** [comment]
Interesting - I narrowed it down to the line of code causing the bug:
It's `app.setEntryDefault('email', 'email address')`

Can you confirm removing that line fixes the issue?

**Comment by lieuzhenghong** [comment]
@jarvisteach Yep, that line fixes the issue!

**Comment by jarvisteach** [comment]
OK, for now - remove the default for the AutoEntry
I can see why it breaks - just need to fix it.
Have raised a new issue...

**Comment by jarvisteach** [comment]
The issue has been resolved for the next release

**Comment by gsantner** [comment]
![screenshot_20181111-204108](https://user-images.githubusercontent.com/6735650/48317411-25926e80-e5f2-11e8-91a3-a0a2b832b55d.png)

```
from appJar import gui

app = gui("test", "500x500")

def appjar_add_input(resIdInput, input_type="textline", pref=False, default_value=None, options=[], crow=0):
    # Add input element
    if False: pass
    elif input_type == "combobox":
        app.addAutoEntry(resIdInput, words=options, row=crow, column=1)
    else:
        app.addEntry(resIdInput, row=crow, column=1)

    value = default_value if not pref else app.getSetting(resIdInput, default_value)

    # Apply changes to input element
    if value or value is 0:
        app.setEntry(resIdInput, value, False)

appjar_add_input("R.id.textline1", input_type="textline", default_value="hi", crow=0)
appjar_add_input("R.id.combobox1", input_type="combobox", options=["something","text","hi"], crow=1, default_value="tex")
appjar_add_input("R.id.textline2", input_type="textline", default_value="hi", crow=2, )
appjar_add_input("R.id.textline3", input_type="textline", default_value="hi", crow=3)

app.go()
```
