### ISSUE TITLE
Issue with tkinter on i3 window manager

### ISSUE THREAD

**Issue by xircon** [jarvisteach/appJar#129]
```bash
Traceback (most recent call last):
  File "buttons.py", line 7, in <module>
    app=gui()
  File "/usr/lib/python3.6/site-packages/appJar/appjar.py", line 427, in __init__
    self.topLevel = Tk()
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "[80]#000000"
```
Any ideas?

appJar 0.52 from pip

**Comment by xircon** [comment]
```python
from appJar import gui

# the title of the button will be received as a parameter
def press(btn):
    print(btn)

app=gui()
# 3 buttons, each calling the same function
app.addButton("One", press)
app.addButton("Two", press)
app.addButton("Three", press)
app.go()
```
Is the example script.

**Comment by jarvisteach** [comment]
This looks like it might be an issue with python/tkinter?

can you try the following code:
```
import tkinter
top = tkinter.Tk()
# Code to add widgets will go here...
top.mainloop()
```

**Comment by xircon** [comment]
```
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> top = tkinter.Tk()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/tkinter/__init__.py", line 2017, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: unknown color name "[80]#000000"
>>> 
```
This is weird.  Manjaro linux, will look through my pacman logs, see if anything has updated.

**Comment by jarvisteach** [comment]
OK, good - so it's not an appJar problem. Let me know how you get on, would be great to hear about appJar being used on different platforms.

I've renamed, this issue.

**Comment by xircon** [comment]
Cheers.  Will do.  This is bizarre was working fine.

**Comment by xircon** [comment]
OK - I have worked it out, it aint Manjaro, it is i3wm.  Everything works well in KDE Plasma:
![image](https://cloud.githubusercontent.com/assets/1316691/24656820/e2288b5e-193b-11e7-9c4b-376beedeb2f6.png)

**Comment by jarvisteach** [comment]
good news!

**Comment by xircon** [comment]
Right, taken all day, have goggle eyes from googling :D

Top of my .extended.Xresources file in my home:

> ! XTerm Settings
> *background: [80]#000000 <<<<<<<<< THIS LINE
> *foreground: #ffffff
> URxvt*inheritPixmap: false

I never use/used xterm but it was line 2 that was causing the problem.
