### ISSUE TITLE
Feature request: file picker/directory picker widget

### ISSUE THREAD

**Issue by lieuzhenghong** [jarvisteach/appJar#134]
Love the library, I think it would be greatly improved with the addition of this widget.

**Comment by jarvisteach** [comment]
There are already a couple of dialogs for selecting folders & directories.

There is also a tree widget, that could be used to show a directory tree...

Do you have an example of what you're after? Have you seen any existing tkinter implementations?

I think I can provide a couple of things:
* an entry, which when clicked, pops up a file dialog, that auto populates the entry
* sample code for the tree widget to be a file explorer

I think IDLE might already have a file explorer widget (using the tree) so I might be able to incorporate that...

**Comment by jarvisteach** [comment]
Example of directory tree: http://stackoverflow.com/questions/16746387/tkinter-treeview-widget

**Comment by lieuzhenghong** [comment]
I am using a Tkinter `filedialog` at the moment.
![image](https://cloud.githubusercontent.com/assets/7903071/24888688/ae81e622-1e97-11e7-8686-adee2aaee2c0.png)
![image](https://cloud.githubusercontent.com/assets/7903071/24888693/bb744834-1e97-11e7-8a0e-865178194075.png)

```python3
from appJar import gui
from tkinter.filedialog import askdirectory


app = gui("Form emailer")
app.setSticky("ew")
app.setStretch("column")
app.addEntry('path', 0, 0, 2)
app.setEntryDefault('path', 'path')
app.addButton('Choose path', add_file, 0, 2)
```

**Comment by jarvisteach** [comment]
Great - that's exactly what I've described in issue #137 :)

I would mention that appJar already imports askdirectory - you can get to it with:
`filename = app.directoryBox(title, dirName)`
Where `dirName` is the starting folder. That way you won't need the extra import.

For some reason I never finished the documentation in: http://appjar.info/pythonDialogs/#file-boxes
Will raise an issue...
