### ISSUE TITLE
Video functionality please.

### ISSUE THREAD

**Issue by captainsmu** [jarvisteach/appJar#14]

**Comment by gretel** [comment]
i am trying to display a continuous stream of binary jpeg-encoded image data (actually it's a usb camera video via [pyuvc](https://github.com/pupil-labs/pyuvc)) with some simple ui. kindly asking for advice

**Comment by jarvisteach** [comment]
1. Create a simple GUI with [an image](http://appjar.info/pythonImages/#add-images)
2. Then write a function to get the most recent image from a folder and [update the image](http://appjar.info/pythonImages/#change-images)
3. Finally register the function to be [called regularly](http://appjar.info/pythonEvents/#repeating-events)

NB. jpegs take a few seconds to parse...

**Comment by gretel** [comment]
thanks, did [hack it up](https://gist.github.com/gretel/73fb72ff48db4cfea71a650f4cc72ba7) using `pygame`. slow and intensive but good enough.

**Comment by jarvisteach** [comment]
Raised new issue (#90) to support raw data images...
