### ISSUE TITLE
Center Widget on screen.

### ISSUE THREAD

**Issue by juanlatorre** [jarvisteach/appJar#150]
Hey, I read all the docs and Learning, but i couldn't find any documentation about centering windows on the screen. Any idea on how to do this?

**Comment by jarvisteach** [comment]
There are a couple of [options](http://appjar.info/pythonGuiOptions/#gui-configuration) you can set directly on the GUI:
* `app.setLocation(x,y)` - sets the position on the screen  
* `app.setGeometry(width, height)` - sets the width/height of the GUI  

They allow you to manipulate the initial size & position.

If you don't set them, **appJar** does its best to set a size and position - and it should default to the middle of the screen.

Is it not starting in the middle?

**Comment by jarvisteach** [comment]
Or, are you trying to position **subWindows** - in which case, just use the same functions after starting a **subWindow**...

**Comment by juanlatorre** [comment]
I am so sorry for the bad explanation, regarding your answer about **subWindows**, yes, that is the case. thank you very much for the quick response.
