### ISSUE TITLE
.addGrid(my_list, addRow=True) error in Windows 7 environment

### ISSUE THREAD

**Issue by slightlynybbled** [jarvisteach/appJar#151]
Windows 7
Python 3.5
appJar 0.052 (used pip to install)

Code:

```python
app.addGrid(
    'airflow_data_raw',
    [
        ['Nozzle Diameter', 'Number of Nozzles', 'Differential Pressure', 'Static Pressure', 'Voltage', 'Current', 'Frequency'],
    ],
    row=1,
    column=0,
    colspan=3,
    addRow=True
)
```
The button doesn't show up well:

![button](https://cloud.githubusercontent.com/assets/2328302/25241425/ed9101ee-25c3-11e7-8177-beb20239e21e.png)

Additionally, when pressed, the button throws an error:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\tkinter\__init__.py", line 1550, in __call__
    return self.func(*args)
  File "C:\_virtual_env\appjar\lib\site-packages\appJar\appjar.py", line 1986, in <lambda>
    return lambda: funcName(param)
TypeError: 'NoneType' object is not callable
```

**Comment by jarvisteach** [comment]
Great to see someone trying out the beta widgets!

Grid is probably the **MOST** beta - sorry!

The button on the `addRow` needs a function to call. Currently, it assumes a function has been assigned to the `action` variable. So tries to call that, passing the String `newRow`.

Now, in your case, no `action` has been set - so it's bombing out.

However, setting `action` will also cause **Press** buttons to appear at the end of each row - probably not what you want?

Short-term, you can populate the `action` parameter, long term, I think the function call should be changed - so that both `action` & `addRow` default to None and expect functions as parameters?

**Comment by jarvisteach** [comment]
The squashed button is linked in to the above assumption.

The extra column, where the `Press` button is being drawn, gets created when the buttons are added to the previous rows. As no `action` function was set, the buttons weren't created above, and the header cell wasn't drawn.

Again, short-term - setting the `action` variable will fix the squashed button...

**Comment by slightlynybbled** [comment]
I tried that, but it still doesn't add a new row:

```python
def dummy(*args):
    print('dummy function executed', args)

app.addGrid(
    'airflow_data_raw',
    [
        ['Nozzle Diameter', 'Number of Nozzles', 'Differential Pressure', 'Static Pressure', 'Voltage', 'Current', 'Frequency'],
    ],
    addRow=True,
    action=dummy
)
```

Basically, there is never a row added.

I have been using tkinter for a bit and I ended up coding up a block (tkinter) that I have been able to use in a few places adequately.  I am including it here:

[grid.zip](https://github.com/jarvisteach/appJar/files/945057/grid.zip)

Nice features:
 * hitting 'tab' on the last row will automatically add a new row
 * rows can be deleted by index
 * columns are even

The styling doesn't look as nice as yours is, but it is workable.

**Comment by jarvisteach** [comment]
No, that will just fix the button. You have to manage adding a new row yourself.

Pressing the **Press** button will just call your `dummy(*args)` function.

Your `dummy(*args)` function would need to call `app.getGridEntries(title)` to get the data typed in, as a list. You should then process that data, before adding a new row to the grid using `app.addGridRow(title, data)`

If you don't want to do any processing, you can simply add the following code to `dummy(*args)`:
```
if args[0]=="newRow":
        app.addGridRow('airflow_data_raw', app.getGridEntries('airflow_data_raw'))
```

**Comment by slightlynybbled** [comment]
Ahh, I see.  I must have missed that in the docs.  Will do.

**Comment by jarvisteach** [comment]
Ha - it's not really documented, I've created a new branch to look into the Grid widget, and have already updated the docs to reflect how it works...
