### ISSUE TITLE
Warning - Deprecated config function (command) used for: RadioButton->application use Submit or Change instead

### ISSUE THREAD

**Issue by juanlatorre** [jarvisteach/appJar#153]
Hey, since 0.6 update i'm getting this warning message.

The code is:
![screenshot from 2017-04-22 16-10-50](https://cloud.githubusercontent.com/assets/4494526/25307359/44e363f2-2776-11e7-88a4-1411a8956a96.png)

**Comment by jarvisteach** [comment]
Hopefully, you worked out that I've been renaming some functions...

`.setRadioButtonFunction()` is still there, but you should now be using `.setRadioButtonChangeFunction()` - as that's always guaranteed to be called when someone changes the RadioButton selection.

There's not much of a difference on RadioButtons, but for consistency, I've updated it for all widgets, as it was causing some confusion on the Text widget - where change/submit have big differences...
