### ISSUE TITLE
starting python script with appJar GUI after startup

### ISSUE THREAD

**Issue by martincurda** [jarvisteach/appJar#163]
I am using appjar on my raspberry pi3. If I start my script from terminal in raspbian graphical interface script is working well, but problem is with autostart after reboot. I dont know what I have to do. This is log: 
Traceback (most recent call last):
  File "/home/pi/programming/grid.py", line 78, in <module>
    app=gui("Connection test", "fullscreen")
  File "/usr/local/lib/python3.4/dist-packages/appJar/appjar.py", line 427, in __init__
    self.topLevel = Tk()
  File "/usr/lib/python3.4/tkinter/__init__.py", line 1854, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by jarvisteach** [comment]
Hi @martincurda - are you trying to boot the pi straight into the python gui? Or are you betting into pixel, then trying to launch the python GUI? The error you;re getting is not to do with python, but rather a missing environment setting - python needs a $DISPLAY in order to launch the GUI, but one isn't set...

**Comment by martincurda** [comment]
I am trying start my script by cron, autostart... Script is probably runned earlier then pixel. Maybe, I have to wait few seconds and delay start of my script. I will try use a sleep time on start.

**Comment by jarvisteach** [comment]
You'll still have issues with the display, if you're doing it from cron:
* https://ubuntuforums.org/showthread.php?t=185993

Instead, you could you the autostart scheduler within the desktop (scroll about half-way down):
* http://www.raspberry-projects.com/pi/pi-operating-systems/raspbian/auto-running-programs-gui

**Comment by martincurda** [comment]
Thank you, it works well!
