### ISSUE TITLE
Updating Label Text Frequently

### ISSUE THREAD

**Issue by ed1231233** [jarvisteach/appJar#167]
Hi

I have a program which loops through doing various things and prints out its status whilst doing so. I am trying to report this same information within the gui through a message box or label, however it doesn't seem to be updating the text at the times when it should be. IE it will print the text at the right point in time, but the label will not update at that point in time but at a delayed time or not at all

What am I missing here? Thank you"

**Comment by jarvisteach** [comment]
GUIs run an event loop, which checks the UI for clicks, drags, etc and updates accordingly. If you run your own loop, then the event loop will hang, until your loop finishes. If you want to run code in a loop, while having the GUI stay responsive and have it update itself, then you need to run your loop in its own thread, or register it with the GUI, and have the GUI run the loop.

The easiest way to do this in appJar, is to call `app.registerEvent(function)` - this will cal your function once every second, while still keeping the GUI responsive. Then, whatever code was meant to be in your loop, put it in the function...

More info at: http://appjar.info/pythonEvents/#repeating-events

**Comment by ed1231233** [comment]
Thank you so much, really appreciated!

**Comment by jarvisteach** [comment]
Closing this, as assumed resolved?

**Comment by ed1231233** [comment]
Yes! rewrote some of my program flow logic in light of what you said and got it all working, thanks again.
