### ISSUE TITLE
Unknown Function: setScaleIncrement and setScaleChangeFunction.

### ISSUE THREAD

**Issue by nbness2** [jarvisteach/appJar#168]
I was using these functions as shown by the documentation at appjar.info, and these warnings have come up when trying to use these functions to set scale increment value and set the function for when it changes.
I double checked spelling and even copy-pasted from the documentation to be 100% sure that it was correct, but it does not work.

Sample code to reproduce

'''
app = gui()
app.setFont(20)
app.addLabelScale("scale")
app.setScaleIncrement("scale", 5)
app.setScaleChangeFunction("scale", print)
app.go()
'''

```
Warning - Unknown function:setScaleIncrement ('scale1', 4) {}
Warning - Unknown function:setScaleChangeFunction ('scale1', <built-in function print>) {}
```

**Comment by jarvisteach** [comment]
That code should work just fine. Maybe you have an older version of appJar? Can you try adding this line of code: `print(app.SHOW_VERSION())` and log the output here.

**Comment by nbness2** [comment]
This is odd. I installed appJar just 2 days ago. There's no SHOW_VERSION either, it gives me the same warning message. However, when I uninstall and reinstall using pip, it says I am un/re installing "appjar-0.52" and I noticed that appJar is 0.6 now.

**Comment by jarvisteach** [comment]
Weird - I'm actually seeing the same here too!

pypi says it's at version 0.06, but it installs 0.052

Try requesting a version: `pip install -Iv appJar==0.06` and I'll look into pypi

**Comment by nbness2** [comment]
Yeah, looks like downloading and installing from the download on appjar.info makes everything work as expected. Thanks!

**Comment by jarvisteach** [comment]
Not sure why version 0.06 was having issues. Have pushed out 0.061 - it's working fine my end...
