### ISSUE TITLE
Update individual values on ListBox

### ISSUE THREAD

**Issue by nbness2** [jarvisteach/appJar#173]
The most comparable function in another widget is
`setOptionBox(title, position, value=True, callFunction=True)`
I think that adding this functionality to ListBox would be beneficial to people who use large lists so that they don't have to update with big delay every time they want to change something in the list.
`setListItem(title, item, value)`

**Comment by nbness2** [comment]
The current workaround is to do this instantly

```
self.getListBoxWidget(listbox_title).delete(current_)
self.getListBoxWidget(listbox_title).insert(idx, new_value)
```

I suggest this because some people using appjar (beginners to making gui) would not think to change tkinter stuff, or may not even know what tkinter is.

**Comment by jarvisteach** [comment]
There are already features to set the background/foreground colours of individual items in a list based on their value or position, so it shouldn't be much work to change the value of those same items.

Will add to the next release.

**Comment by jarvisteach** [comment]
New functions:
* `.setListItem(title, oldVal, newVal)`
* `.setListItemAtPos(title, pos, newVal)`

In next release.
