### ISSUE TITLE
SubWindow centered in MainWindow

### ISSUE THREAD

**Issue by AbrhmSanchez** [jarvisteach/appJar#177]
Could a method be added to locate SubWindows centered to the Main Window? The location defaults to (100,100). Something like this could do the trick:

```python
def setSubWindowCentered(self, title):
    main_win = self.topLevel
    win = self.__verifyItem(self.n_subWindows, title)
    # Find subWindow width and height
    win.update_idletasks()
    width = win.winfo_width()
    frm_width = win.winfo_rootx() - win.winfo_x()
    win_width = width + 2 * frm_width
    height = win.winfo_height()
    titlebar_height = win.winfo_rooty() - win.winfo_y()
    win_height = height + titlebar_height + frm_width
    # Find Main Window width and height (same thing as before)
    m_width = main_win.winfo_width()
    m_frm_width = main_win.winfo_rootx() - main_win.winfo_x()
    m_win_width = m_width + 2 * m_frm_width
    m_height = main_win.winfo_height()
    m_titlebar_height = main_win.winfo_rooty() - main_win.winfo_y()
    m_win_height = m_height + m_titlebar_height + m_frm_width
    # Find x and y centered on the Main Window
    x = main_win.winfo_x() + m_win_width // 2 - win_width // 2
    y = main_win.winfo_y() + m_win_height // 2 - win_height // 2
    win.geometry('+{}+{}'.format(x, y))
```

Please bear with me as I am a programming noob. I made this based on the static function gui.CENTER(win)

**Comment by AbrhmSanchez** [comment]
Tested it in windows 7. Appears to work well after the subWindow has been shown at least once. It appears a bit off center if the method is called before the first _show_.

**Comment by jarvisteach** [comment]
FYI, SubWindows have all the same functions as the main window, so there is the option to simply call `.setLocation(x, y)`. Although that won't achieve exactly what you've asked for.

As you mention, the difficulty is finding positions before things have been drawn. Until the main window and SubWindow has been draw, their widths & heights won't have been calculated correctly.

First drawing them & then re-positioning them doesn't give a great user experience.

However, there are functions: `winfo_reqwidth()` & `winfo_reqheight()` which allow you to query the *expected* width & height - these might have better results, and save having to first draw the windows.

I'll add it as something to investigate for the next release.

**Comment by AbrhmSanchez** [comment]
Alright, thought it could be useful. Thanks for the input!

**Comment by jarvisteach** [comment]
Would be useful to have a dialog follow its parent - so, if the main appJar GUI is moved, a SubWindow would be centred over it.

This could also be done for num/text boxes - although the built in dialogs don't support it - so would give different behaviour.

Will raise as a new feature request.
