### ISSUE TITLE
Is it possible to transfer an appjar project into an exe

### ISSUE THREAD

**Issue by MattCompute** [jarvisteach/appJar#178]
I was wondering whether its possible to transfer an AppJar project into an executable.

**Comment by jacobthetechy** [comment]
Yes it is. 
[http://appjar.info/packaging/](http://appjar.info/packaging/)

**Comment by MattCompute** [comment]
Okay, Thank you!

**Comment by jarvisteach** [comment]
Closing - would be useful to know if you had any success...
