### ISSUE TITLE
How do I get sound

### ISSUE THREAD

**Issue by MattCompute** [jarvisteach/appJar#179]
Basically I am trying to get a sound to play on AppJar I have tried, setsoundlocation and that but it does not seem to work so can you please explain to me how you do it.

**Comment by jarvisteach** [comment]
To play a `.WAV` file on Windows, you should just be able to call `.playSound("mySound.wav")`, assuming the wav file is in the same folder as the python code.

If the files are not together, you can specify a the path in the filename: `.playSound("../../mySound.wav")` or call `.setLocation()` to make this simpler.

If you're not on Windows, then appJar can't (yet) play sounds directly. If you have other python packages to play sounds you can call those. But be careful that they don't cause the GUI to block...

**Comment by jarvisteach** [comment]
Closing as no follow-up

**Comment by MattCompute** [comment]
Thanks
