### ISSUE TITLE
Validation Entry width

### ISSUE THREAD

**Issue by maphstra** [jarvisteach/appJar#183]
Hey, sorry if there is an easy answer to this question, but how do i set the entry width of a validation entry?
Only going to use it to input a two-digit int value, so it doesn't need to be so big.

trying to use
app.addLabel("Vertical", "Vertical limit:", 2, 2, 1)
app.addValidationEntry("Vertical_e", 2, 3)
app.setEntry("Vertical_e", "75")
app.getLabelWidget("Vertical_e").entry.config(width=2)
but this last line seems to only sets the width for the space of the actual validation ICON, not the text field. 

Also, I like this module a lot, thanks!

Mads

**Comment by jarvisteach** [comment]
Hi Mads, glad you like it!

To set the width of a widget, just call `.set XXX Width()`

So, in this case, try: `app.setEntryWidth("Vertical_e", 2)`

NB. You're trying to change the Entry widget part of a compound "validation entry" - so you should be targeting the Entry, not the Label...

**Comment by jarvisteach** [comment]
Closing as no issue
