### ISSUE TITLE
Multiple listbox not possible.

### ISSUE THREAD

**Issue by iam-aditya** [jarvisteach/appJar#184]
It is not possible to have multiple listbox's (with unique names) in the UI and make selection on both.
It would be very helpful if this would be tweaked.

**Comment by jarvisteach** [comment]
You're right, this would be a useful feature!

I'm not sure if it should be enabled by default, or if users should have to turn it on? I can see use cases for both.

I think I will leave the current functionality as default, as other users might already be using it in single "select mode", and I'll add a new function to turn on "list box grouping"

It's quite easy to enable, `exportselection=False`

So, will create a new function: `setListBoxGroup(title)` to set this attribute on a listbox

**Comment by jarvisteach** [comment]
In next release
