### ISSUE TITLE
textAera getEntry impossible?

### ISSUE THREAD

**Issue by Exaltia** [jarvisteach/appJar#188]
Hello, i'm not really experienced in python and it's the very first time i play with building graphical interfaces.

This is probably not a bug, just me who doesn't understand how to correctly do.
This code works and correctly get and print what i input in LabelEntry 'UserName'
```python
from appJar import gui
def login(btn):
    u = app.getEntry('Username')
    print(u)
def openLogin():
    app.showSubWindow('L')
def testwindow():
    app.showSubWindow('M')
def testdef(btn):
    if btn == 'Send':
        print(app.getEntry('testone'))

app = gui('SLA Sendback Entry')

# Login #
app.startSubWindow("L")
app.setLocation(900,400)
app.addLabelEntry('Username')
app.addButton('Login', login)
app.stopSubWindow()
app.addLabel('l1', 'Sendback Data Entry')
print(app.getAllEntries())

app.setTransparency(0)
openLogin()
app.go()
```
As soon as i change LabelEntry for textAera getEntry returns : 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/home/exaltia/.local/lib/python3.5/site-packages/appJar/appjar.py", line 2410, in <lambda>
    return lambda: funcName(param)
  File "./guitest.py", line 3, in login
    u = app.getEntry('Username')
  File "/home/exaltia/.local/lib/python3.5/site-packages/appJar/appjar.py", line 5967, in getEntry
    self.__verifyItem(self.n_entryVars, name)
  File "/home/exaltia/.local/lib/python3.5/site-packages/appJar/appjar.py", line 2428, in __verifyItem
    raise ItemLookupError("Invalid key: " + item + " does not exist")
appJar.appjar.ItemLookupError: Invalid key: Username does not exist

What did i do wrong?

**Comment by iam-aditya** [comment]
From what you have said, it seems that you are doing app.getEntry('Username') to get text from textArea.
Instead you should be doing, 

    # To add textArea
    app.addTextArea(title)

    # To get text from textArea
    app.getTextArea(title)

Refer: http://appjar.info/pythonWidgets/#textarea

And please try to include code that actually gives error as its easier to point out the bugs.

**Comment by Exaltia** [comment]
Sorry, misreaded the doc, i thought that getEntry could be used for anything.
About the need to include code that actually gives error, i'm not sure to understand, i thought this is what i had done, as the code that doesn't work was identitical than the one i pasted, at the sole exception of the textAera :).
Anyways, i feel stupid now, but a chance it doesn't kill :)
thanks
