### ISSUE TITLE
pip installs old version of appJar

### ISSUE THREAD

**Issue by inukai132** [jarvisteach/appJar#191]
When I try to use setRadioButtonChangeFunction() I get an Unknown Function Warning in Python. The function is also not called when the radio button is changed. Here's some example code to demonstrate what I'm trying to do. 

`
types = ["one","two","three"]
for type in types:
    app.addRadioButton("typeName", type)
app.setRadioButtonChangeFunction("typeName", update)
`
app is the main GUI object. According to your documentation at http://appjar.info/pythonEvents/ this should be possible. I've even tried copying the code on the documentation page and I still get the error.

**Comment by inukai132** [comment]
It would appear that the problem is actually in pip. Running 
`sudo pip install appJar` installs version 0.052. I had to specify appJar==0.061 to get teh correct version to install.

**Comment by jarvisteach** [comment]
Yeah, it's not the first time I've seen this - what version of Python are you on, and what platform?

I've just tried it on my Mac, user python 3.6 - and it got the right version, so don't know what causes it.

I'm hoping to get a new version out this coming week, so that might resolve it...

**Comment by inukai132** [comment]
I was running the command on a Raspberry Pi and I'm pretty sure everything was the latest version according to apt (using python 2.7). I don't have access to it at the moment, but when I do I'll get the specific version info. 

Also I just installed appJar from Windows 7, pip 9.0.1, python 2.7.11 and it pulled the correct version.

**Comment by jarvisteach** [comment]
One issue I've worked out is with version numbers - version 0.07 is behind version 0.061 - I guess because 61 > 7.

So, I've labelled version 0.07 as 0.070, ensuring it is the latest version.
