### ISSUE TITLE
Add base64 encoded image support

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#210]
Great work on appJar, I'm using it to build a simple app to control a video capture/streaming device & I want to include images in the app, but I don't want to have a ton of files hanging around, would it be possible to use base64 encoded image strings instead?

**Comment by jarvisteach** [comment]
There's already some support for this - `.addImageData()` and in the next release there's also support for passing in PhotoImages from PIL.

Alternatively, to keep updating an image with the same name, you can call `.replaceImage()` and it will update the cache each time.

**Comment by mpmc** [comment]
Ah, so there is. I thought I'd read the image docs completely, obviously must've skipped past that one! Sorry!
