### ISSUE TITLE
column fixed width

### ISSUE THREAD

**Issue by megavenik** [jarvisteach/appJar#221]
Hello!

Is there a way to set one exact column not to be stretchable? If it is not, i think, it could be a nice possibility:)

Thanks for you work!

**Comment by jarvisteach** [comment]
It is currently possible, although a bit of a hack....

```
from appJar import gui 

app=gui()

app.addLabel("l0", "Some Text")
app.addLabel("l1", "Some Text", row=0, column=1)

app.setExpand("NONE")
app.addLabel("l2", "Some Text")
app.setLabelBg("l2", "red")

app.setExpand("ALL")
app.addLabel("l3", "Some Text", row=1, column=1)
app.setLabelBg("l3", "green")

app.go()
```

Every time you add a widget, the columns get reconfigured. So, the calls to `.setExpand()` will need to be included before the last calls to position widgets in the app.
