### ISSUE TITLE
Email me about this:

### ISSUE THREAD

**Issue by xHqrley** [jarvisteach/appJar#224]
Hi there, I'm new to using GitHub, so please excuse me if this isn't the best way for me to be contacting you. I recently found appJar, and was hoping to use it for a little project. I will admit I'm pretty inept so if I'm completely missing something here that's to be expected. I was hoping to make a little message bar (label) at the top of the program, where the message would change depending on the occurrence of certain actions. It seems to me that this is not possible with the current version. Email me @ harley.norgate@gmail.com and let me know whether this is true or not, it would be really helpful!

**Comment by jarvisteach** [comment]
Sorry @xHqrley, I don't provide email support...

What you're asking is possible, and quite straightforward.

Simply add a label to the top of your GUI: `app.addEmptyLabel("info")`

Then, write a function that updates the label:
```
def update(btn):
    app.setLabel("info", "some text")
```

Then call the `.update()` function whenever needed, maybe with a button: `app.addButton("Update", update)`

See here for info on labels: http://appjar.info/pythonWidgets/#label
And here for info on buttons: http://appjar.info/pythonWidgets/#button
