### ISSUE TITLE
time.sleep() causes GUI to hang

### ISSUE THREAD

**Issue by xHqrley** [jarvisteach/appJar#225]
Hello again, sorry to bother you again, (more sorry for last time apparently I'm more blind than I give myself credit for) but I have come to a problem and I can't find the cause.
Basically I wrote this for if the button pressed hasn't been implemented.
I wanted it to say one message and then the other with ample reading time between.
`        msg = "Error. Undefined Button."
        app.setLabel("notif", msg)
        #Reports error

        time.sleep(2)
        #Waits 2 seconds before changing the message
        
        msg = "You are using an unsupported version of the game."
        app.setLabel("notif", msg)
        #Explains error`
(if the box there is messed up, it didn't preview correctly either and I don't know why)
Instead of doing what I wanted and thought it would do, it instead ended up lagging really hard the first time I did it, and then only displaying the second message. The button would also appear to be pressed down for around about the 2 second duration. I'm effectively new to coding that isn't out of a text book  or a teacher's mouth (especially event based), so it's likely I'm missing something obvious once again.
If you could help me out once again I'd very much appreciate it :D 

- Harley

**Comment by jarvisteach** [comment]
Hi Harley,

Using sleep in a GUI is bad news - it will make the whole GUI stop working, even the button won't change back - exactly what you're experiencing.

Instead, you need to use `after()` - have a look at this: http://appjar.info/pythonEvents/

Try the following code:
```
from appJar import gui 

def notify(btn):
    app.setLabel("l1", "Updating")
    app.after(2000, app.setLabel, "l1", "Updated message")

app=gui()
app.addLabel("l1", "Simple message here")
app.addButton("PRESS", notify)
app.go()
```
