### ISSUE TITLE
setXXXChangeFunction and setXXXSubmitFunction not working for FileEntry widgets

### ISSUE THREAD

**Issue by BlacKCaT27** [jarvisteach/appJar#226]
According to the documentation, if I wan't to set an event handler for a widget, I follow the syntax from this issues title. But when I try:

app.setFileEntrySubmitFunction("myFileEntryWidgetTitle", myfunc)

or

app.setFileEntryChangeFunction("myFileEntryWidgetTitle", myfunc)

I get a warning at start-up saying the functions don't exist.

Are FileEntry/DirEntry types not supported?

**Comment by jarvisteach** [comment]
Ah yes, this is a bug.

These are new widgets introduced in 0.07 - but they haven't been added to the `WIDGETS` dictionary, so none of the auto-generated functions have been set for those widgets.

You can add a trace manually for the time being:

Get the entry var: `app.n_entryVars["myFileEntryWidgetTitle"]`
Then call `trace()` passing in the details.

**Comment by jarvisteach** [comment]
Actually @BlacKCaT27 - these are still just Entry widgets, so this should work:

```
app.setEntrySubmitFunction("myFileEntryWidgetTitle", myfunc)
```

**Comment by BlacKCaT27** [comment]
That worked! Thanks

**Comment by BlacKCaT27** [comment]
Actually, to clarify:

setEntrySubmitFunction doesn't work. setEntryChangeFunction does. Although
it appears, at least in the case of file entry (haven't tried direntry
yet), to call my callback twice. Once when clearing the old value (so if I
inspect the fileEntries current value it's ''), then again when the new
value is set.

Would be great to not have it called on reset when what the callback is
really after is when a new value is ready

**Comment by jarvisteach** [comment]
I"ve tested the `setEntrySubmitFunction()` - that seems to work here, if the Entry is in focus and I press **Enter** it calls my function.

For the double function call - the first is happening when the *<default value>* is removed, that shouldn't happen, so I'll dig a bit more...

**Comment by BlacKCaT27** [comment]
Ah, I was expecting Submit to be called once a file was picked, not after
hitting enter. Makes sense.

Yeah if that first call on clear gets resolved then onChange will work
perfectly as I expect. Thanks for digging into it!

**Comment by jarvisteach** [comment]
Should be resolved now

**Comment by BlacKCaT27** [comment]
Great, thanks! any eta on when 0.08 will be published out to pip/pypi/etc?

**Comment by jarvisteach** [comment]
Hopefully in the next couple of days
