### ISSUE TITLE
getOptionBox weird behaviour / doesn't return

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#229]
If you attempt to get a value from an option box that doesn't exist using getOptionBox, it doesn't actually return a value (not even None), no warnings are printed, any code following the call doesn't get executed.

``` 
foo = self.getOptionBox('thisoptionboxdoesnotexist')
print('Youwon\'t see this.')
```

**Comment by jarvisteach** [comment]
That is weird - the first thing (most of) the get functions do is `verify` the key - so it should throw an ItemLookupError.

I've just run a quick test in my build environment under python 2.7 & 3.6, and I get this error message:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/tkinter/__init__.py", line 1699, in __call__
    return self.func(*args)
  File "../../appJar/appjar.py", line 3117, in <lambda>
    return lambda: funcName(param)
  File "issue229.py", line 6, in press
    print(app.getOptionBox("ob2"))
  File "../../appJar/appjar.py", line 4681, in getOptionBox
    box = self.__verifyItem(self.n_options, title)
  File "../../appJar/appjar.py", line 3135, in __verifyItem
    raise ItemLookupError("Invalid key: " + item + " does not exist")
appJar.appjar.ItemLookupError: Invalid key: ob2 does not exist
```

Could you let me know what platform/version of python you are using?

And maybe test out this code, as it might be something to do with subclassing??

```
def press(btn):
    print(app.getOptionBox("ob"))
    print(app.getOptionBox("ob2"))
from appJar import gui 
app = gui()
a = app.addOptionBox("ob", ["a", "b", "c", "d"])
app.addButton("PRESS", press)
app.go()
```

**Comment by jarvisteach** [comment]
Have just tested it with subclassing - and get the same error message as above:

```
import appJar

class app(appJar.gui):
    def __init__(self, **kwargs):
        super().__init__()
        self.setTitle('main_win_title')
        self.main_widgets()

    def press(self, btn):
        print(self.getOptionBox("ob"))
        print(self.getOptionBox("ob2"))

    def main_widgets(self):
        self.addOptionBox("ob", ["a", "b", "c", "d"])
        self.addButton("PRESS", self.press)
    
app = app()
app.go()
```

**Comment by mpmc** [comment]
I think i know the reason.. Threading, which isn't at all surprising really
```
import appJar
from concurrent.futures import ThreadPoolExecutor 

class app(appJar.gui):
    def __init__(self, **kwargs):
        super().__init__()
        self.setTitle('main_win_title')
        self.main_widgets()
        self.executor = ThreadPoolExecutor(max_workers=1)
        
    def task(self, runnable, *args, **kwargs):
        """Add background task to queue.
        
           :param runnable: Method to run in the background.
           :param args: Optional positional args (for the runnable).
           :param kwargs: Optional keyword args (for the runnable).
        """
        future = self.executor.submit(runnable, *args, **kwargs)
        
    def press(self, btn):
        self.task(self.press_task)

    def press_task(self):
        print(self.getOptionBox("ob"))
        print(self.getOptionBox("ob2"))
        print('Won\'t get called..')

    def main_widgets(self):
        self.addOptionBox("ob", ["a", "b", "c", "d"])
        self.addButton("PRESS", self.press)
    
app = app()
app.go()
```

**Comment by jarvisteach** [comment]
Interesting - I've been doing a bit of reading on tkinter & threading - and the two don't play well together.

Interacting with the gui from a separate thread is unpredictable...

I've started implementing threading - and am using a Queue to link the threads and gui.

The gui monitors & processes the Queue, the threads add things to the queue. The Queue itself is 'threadsafe' - so this seems to the recommended way...

**Comment by jarvisteach** [comment]
Having played with the code - the exception is getting thrown with the second `.getOptionBox()` call, causing the function to exit immediately, hence the final print not happening

However, the thread seems to die silently, not displaying the error message. If you put a try/except around the call - you can deal with it more gracefully.

Or, if you have a read here: https://stackoverflow.com/questions/19309514/how-to-get-correct-line-number-where-exception-was-thrown-using-concurrent-futur/24457608#24457608 - they talk about how to use the ThreadPoolExecutor and show exception messages...

**Comment by mpmc** [comment]
Yeah, I saw that myself while looking into the problem. I need to rethink the design of the interface anyway. I tried using the TabbedFrame, but it looked out of place compared to everything else.

Hmm, I wonder if I can attach my own ttk.notebook to appJar - http://www.tkdocs.com/tutorial/complex.html

**Comment by mpmc** [comment]
I'm going to close this issue as it's not a problem with appJar. 

For now, until you've fully implemented threading, I'll use concurrent.futures but make sure I'm checking for exceptions from with in the threaded method, which I really should've been doing in the first place!

**Comment by jarvisteach** [comment]
OK, going to raise the notebook as a feature request.
