### ISSUE TITLE
Grid Improvements

### ISSUE THREAD

**Issue by hudarealg** [jarvisteach/appJar#232]
Is there any way that I can update the data that is in a grid? Right now, what I'm having to do is remove the previous grid and add a new one with the updated data set however this doesn't work as desired due to my application having tabs; instead of the old grid just being replaced by the new one, it creates itself at the bottom of the tabbed layout and so is visible in every tab. I do understand that this widget is still in beta and so there may not be a way to do this but I can't see any other way of doing this. Any help is appreciated!

P.S. You've done a great job with the module so far!

**Comment by jarvisteach** [comment]
Yeah, the grid is pretty basic right now - no easy way to modify the data. The labels containing the text aren't stored anywhere - so you'd have to query the ```gridContainer``` to get all the labels, then loop through them to update their text ```lab.config(text=val)```. They do have an attribute ```gridPos``` which might help.

Alternatively, you could try deleting all the labels from the ```gridContainer``` then calling ```.addRows()``` to add in the new data - again sounds a bit tricky.

However, you should be able to add the grid back to a specific tab, rather than outside the tabbed widget. You will need to use the code: ```app.openTab(frameName, tabName)``` to specify where to put it, before calling ```app.addGrid()``` with the new data - that might improve things a little.

**Comment by jarvisteach** [comment]
Useful functions to add to grid widget:
* ```deleteRow(pos)``` - remove the specified row
* ```deleteAllRows()``` - remove all the rows
* ```replaceRow(pos, data)``` - update the specified row with the provided data
* ```replaceAllRows(data)``` - remove all current rows, and add the new rows

**Comment by rhulha** [comment]
removing and adding the grid destroys the layout in my case.
Is there a way to remove all rows ? (I tried deleteRow(pos) without success)
If not, please add one.

Much appreciated, appJar rocks!

**Comment by jarvisteach** [comment]
Hi @rhulha - if you're using `app.hideGrid()` & `app.showGrid()` then it should keep all the data & layout. Have you got an example?

I've now implemented a `.deleteRow()` - it'll be in the next release

**Comment by rhulha** [comment]
I do not want to keep all the data, that is the point, I want to remove/replace all rows with new data.

Thanks for adding code to delete a row, much appreciated!

**Comment by rhulha** [comment]
I tested the new code to remove a grid row and it works great!

Here is an example of the old code where the layout gets destroyed:
[](https://gist.github.com/rhulha/6d0c789cc2025469f98b722e4c1774cf)

Here is an example of the new code where I use your new deleteRow function:
[](https://gist.github.com/rhulha/1c2b565bca2496d4e4698479982266a4)

**Comment by jarvisteach** [comment]
Ahh, having run your code I see the problem.

When you remove and then add a new grid, the new grid is lower down.

This is just to do with the layout. I think the new grid is being added in the next row of the layout manager.

If you change the code to be: `app.addGrid("g1", data, action=press, row=1)`
Then the grid will always be put back in the same row...

**Comment by rhulha** [comment]
Thanks for looking into this issue so thoroughly.

While it is good to know how to remove and re-add a Widget in the correct row, would you agree that the better approach to changing the data in the grid is to use the new deleteGridRow function ?

And if so, do you agree that there should be a function like: getGridNumRows()

My workaround is:
```
grid = app.getWidget(app.Widgets.Grid, "g1")
len(grid.cells)-1
```

**Comment by jarvisteach** [comment]
Well - there are use cases for both...

But, the more functionality the better I say!

So, a function to get the number of rows is an easy one, a function to remove all rows, and leave the header row sounds useful, maybe a function to remove a range of rows?

**Comment by jarvisteach** [comment]
Outstanding features:
* addColumn(name, position) - add a new empty column
* deleteColumn(position) - delete the specified column name or position

Plus, more fine-grained editing - how do we replace a single value in a specific cell?

Now we have a 2D list of cells, it's pretty easy - just update the text value of that cell, for now make it easy to get the cells, an add a wrapper around the config() function...

**Comment by jarvisteach** [comment]
Issue with setting colours/fonts - the config function receives the parameters and updates the Grid's stored colours - but doesn't iterate through the cells and update them.

I think I will move all colours/fonts into the cells themselves, so the grid doesn't store them. That means the config function will need to update all cells any time it's called - won't be often.

That will also allow the event bindings to be moved to the SimpleCell constructor.

Might consider an additional class for the header cells...

**Comment by rhulha** [comment]
Just tested the new app.deleteAllGridRows(title) and it works like a charm!

My code looks much cleaner now, thanks!

**Comment by rhulha** [comment]
Using def press(row): app.deleteGridRow("g1", row) in combination with app.addGrid("g1", data, action=press)

deletes the wrong row if you click around on the row buttons randomly for a bit.

I suspect that the row numbers that the row buttons use are not updated after a deleteGridRow.

A fix would be very appreciated.

**Comment by rhulha** [comment]
Using def press(row): app.deleteGridRow("g1", row) in combination with app.addGrid("g1", data, action=press)

deletes the wrong row if you click around on the row buttons randomly for a bit.

I suspect that the row numbers that the row buttons use are not updated after a deleteGridRow.

A fix would be very appreciated.

**Comment by jarvisteach** [comment]
Thanks - yes, the buttons need to be updated each time a row is added/removed!

on it...

**Comment by rhulha** [comment]
Hey Jarvis,

your project has been very helpful to me and your support is outstanding.

Is there anything I can do in return ?
What is a good way to support you ?

**Comment by jarvisteach** [comment]
Hey @rhulha , thanks :)

The best thing you can do, is keep using the library, spread the word, and let me know any problems you find or features you need.

And I'm always willing to accept additions/improvements!

**Comment by jarvisteach** [comment]
Closing this issue - see #266

**Comment by ajbenz18** [comment]
There are a couple rows in my grid that I don't want the user to be able to edit or delete. I'm currently using the right click menu to allow the user to edit or delete the rows, because some need to be able to be edited. Is there currently any solution to this besides simply writing my own methods to edit or delete cells/rows, that way I can check to make sure the user isn't changing the ones I don't want them to?

Thanks
