### ISSUE TITLE
Support ContextManagers for GUI & container start/stop...

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#234]
There's a lot of start/stop in appJar.

It would be nice to add in support for `with`, which would then add some nice indentation to help see what's going on...

Already in use for event raising & logging passing, notes here: http://effbot.org/zone/python-with-statement.htm

I'd like to be able to achieve:
``` python
with gui("my first gui") as app:
    with app.addLabelFrame("lf"):
        app.addLabel("l1", "some text")
        app.addLabel("l2", "some text")

    with app.addScrollPane("sp1"):
        app.addLabel("l3", "some text")
        app.addLabel("l4", "some text")
```

I'm sure it can be done easily on the main gui class, but imagine it'll take a bit more work for all the containers...

It shouldn't break backwards compatability!

**Comment by jarvisteach** [comment]
So, there are lots of interesting things available here.

This is a good read: http://preshing.com/20110920/the-python-with-statement-by-example/

We currently do the following:
```
def startLabelFrame(self, title, row=None, column=0, colspan=0, rowspan=0, sticky=W):
    return self.startContainer(self.C_LABELFRAME, title, row, column, colspan, rowspan, sticky)

def stopLabelFrame(self):
    if self.containerStack[-1]['type'] != self.C_LABELFRAME:
        raise Exception("Can't stop a LABELFRAME, currently in:", self.containerStack[-1]['type'])
    self.stopContainer()
```

And the user calls:
```
app.startLabelFrame("Frame 1, column=2)
app.addLabel("l1", "Some nice text")
app.stopLabelFrame()
```

We can replace the start/stop with a generator:
```
from contextlib import contextmanager
@contextmanager
def startLabelFrame(self, title, row=None, column=0, colspan=0, rowspan=0, sticky=W):
    fram = self.startContainer(self.C_LABELFRAME, title, row, column, colspan, rowspan, sticky)
    try:
        yield fram
    finally:
        self.stopContainer()
```

Then the user would call:
```
with app.startLabelFrame("Frame 1, column=2):
    app.addLabel("l1", "Some nice text")
```

I really like the look of this - but need to keep it backwards compatible.

It won't be necessary to have the container check, as the indentation manages the stops...

**Comment by jarvisteach** [comment]
Actually, as there is no stop, do we need a start?

Could simply have a bunch of functions - named after the container: ```with app.labelFrame()```

**Comment by jarvisteach** [comment]
Ha - this works a treat!

**Comment by jarvisteach** [comment]
Had a go with this commit: https://github.com/jarvisteach/appJar/commit/fb23e9030305b0286d5de391e9ba0115e1ad4a94

Seems to work...

**Comment by jarvisteach** [comment]
So, it actually worked!

It now just takes 2 lines to make a GUI:
```
with gui() as app:
    app.addLabel("l1", "Text")
```

This also support containers.

BTW - found out these are called `ContextManagers`

**Comment by jarvisteach** [comment]
I think the openContainer functions should also be supported by ContextManagers - if the name supplied is already in use, then simply modify that container...

**Comment by mpmc** [comment]
These are a nice addition! It's made me want to add support for ```with``` to my controller code too!

**Comment by jarvisteach** [comment]
Seems there is an issue with PanedFrames - Frames within Frames, all gets a bit confusing...
