### ISSUE TITLE
[feature req] trigger events when window resized/moved

### ISSUE THREAD

**Issue by FlaggedBrad** [jarvisteach/appJar#237]
Can i have the option to trigger a function when the user moves the window?
Also, may i an option to trigger a function when the user resizes the window?

**Comment by jarvisteach** [comment]
This is definitely possible, you can try the following (again going direct to tkinter):
```
def show(event=None):
    print(event)

app.topLevel.bind('<Configure>', show)
```

You will find this gets called a lot. You can examine the event object received to identify why - have a look here for more info: http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm

**Comment by FlaggedBrad** [comment]
Ok, thanks! I'll look into using that
