### ISSUE TITLE
next field/widget

### ISSUE THREAD

**Issue by keithterrill** [jarvisteach/appJar#238]
Do you have a means of advancing to the next field or widget when the end user presses return/enter. I am looking for something that would work like the tab key.

I have thought of keeping a list (array) of the entry fields in the correct sorted order and bind the return key to a function that would look up the next field in the list (+1 the current field) and set focus to that.

I was just wondering...

**Comment by jarvisteach** [comment]
Hopefully the tab key is working?

There are hidden functions that can achieve this, but nothing exposed through the API:
```
from appJar import gui
with gui("Entry Demo") as app:
    app.addEntry("e1").bind("<Return>", app._gui__focusNextWindow)
    app.addEntry("e2").bind("<Return>", app._gui__focusNextWindow)
    app.addEntry("e3").bind("<Return>", app._gui__focusNextWindow)
```
