### ISSUE TITLE
Change Entry Box to Integer

### ISSUE THREAD

**Issue by tellercook** [jarvisteach/appJar#240]
Is it possible to change the entries in entry boxes to be of type integer or long? Love AppJar and am just getting into coding and doing some engineering problems.

Thanks

**Comment by jarvisteach** [comment]
There is a numeric entry box you can use: `.addNumericEntry()` this returns a float and stops the user from typing non numeric characters.

**Comment by tellercook** [comment]
That's perfect! Thank you so much for the prompt reply.
