### ISSUE TITLE
Linux Mint installation

### ISSUE THREAD

**Issue by keithterrill** [jarvisteach/appJar#241]
Note: installing the appJar on a Linux Mint installation you may consider placing the appJar folder in:

`/home/<user>/.local/lib/python3.x/site-packages/`

where `<user>` is the name of the user's home folder and `python3.x` is the relevant python version (for example python3.4 or python3.5).

I believe the sys.path should contain a search line for the site-packages.

**Comment by jarvisteach** [comment]
Is this something to update the installation notes with, for manual installation? Or are you talking about where pip puts it?

**Comment by keithterrill** [comment]
pip puts the appJar folder in:

`/usr/local/lib/pythonx.x/dist-packages`

I was thinking in terms of you "Single-user Set-up" where you have:

`DOWNLOAD appjar and unzip it.
Put the appJar folder in your code folder, and you're done!`

If they were to place the appJar folder in their

`home/<user>/.local/lib/pythonx.x/site-packages/`

they would not need to place it in their working folder(s).
