### ISSUE TITLE
Link broken to install on Home page

### ISSUE THREAD

**Issue by cliverlong** [jarvisteach/appJar#244]
On http://appjar.info/ the link to "installation" tries to open: http://appjar.info/install

and gets 404.

The link should reference: http://appjar.info/Install

**Comment by jarvisteach** [comment]
Ouch! So it did! Thanks for letting me know, should be fixed now...

**Comment by cliverlong** [comment]
Blimey. That’s quick. Yep, it’s there.

Ta,

Clive

Sent from Mail for Windows 10
