### ISSUE TITLE
There should be a getAllValues() method.

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#245]
I noticed there's a method to return values for entries (and associated types) & wondered why there was no method that returns all values from the various other widgets (that accepts user input)?

**Comment by jarvisteach** [comment]
This has already been implemented and is in the next_release :) - have a look at issue #202

It's ready for release - but my build machine (raspberry pi) is broken, and my SD card reader on my Macbook is broken so I can't fix the build machine :( Will be trying again this weekend...

**Comment by mpmc** [comment]
Ah fantastic, sorry for the noise, I really should've checked the closed issues too, sorry about that.

On slightly unrelated notes, I'm finally happy with my [Controller](https://github.com/mpmc/hs602) class which means I can continue writing the appJar GUI. The eventual release of 0.08 just gives me an excuse to rewrite it again, using the new features! I've linked to appJar in my readme, hope you don't mind. I just need to decide if I should subclass or not in this time.

And, I'd like to thank you for reminding me that the BBC micro:bit exists. I was looking into MicroPython & saw the Pyboards but those require additional soldering to make them a little more useful - which I can't do unfortunately. I know the micro:bit is aimed at children but for my use case, it should work fine, and is a lot easier and cheaper than the Pyboards.

**Comment by jarvisteach** [comment]
No, keep them coming - the more requests I get, the better the library gets! I'm way behind on getting the next release out - so it's my fault really! And, please, do link to it :)

Yeah love the micro:bit! Use them for teaching python to year 8. In fact, literally today, I received a delivery of 12 breakout boards for the micro:bits - everything's now ready to kick off my makers club!
