### ISSUE TITLE
Allow empty LabelFrame name/title

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#246]
I noticed something while trying to create blank label frames..

It's not possible just to have a blank labelframe, startlabelframe always requires a name. You can pass an empty string ~~but this result's in a broken box rendered~~. 

![image](https://user-images.githubusercontent.com/2352508/30247127-562d4b6c-9604-11e7-870f-4433c7c18f53.png)

Would it be possible to add a name but hide it?

EDIT:

After zooming right into the box, I can see it's rendered correctly, I've gotten fooled by my very poor sight again, the embossing tricks me into seeing a broken box on the top right! I'm blaming my alternating strabismus!

Sorry!

**Comment by jarvisteach** [comment]
So, this creates a LabelFrame, with no title as desired - but is stored in the widget dictionary with no name - not ideal.

There *should* be a way to create a labelFrame but specify the title isn't displayed.

Issue #207 introduced a way to change the text/anchor of label frames in version 0.08 - so it would be better to create a named labelFrame and then set the label to be empty. As you cn then have multiple labelFrames.

These two steps can be bundled into one...

**Comment by jarvisteach** [comment]
Will just add a `hideTitle` flag to `.startLabelFrame()`
