### ISSUE TITLE
.addButton(title, function) description on site

### ISSUE THREAD

**Issue by cliverlong** [jarvisteach/appJar#247]
On: http://appjar.info/pythonWidgets/

Should : 
Add Buttons
.addButton(title, function)
Add a single button to the GUI, the text on the button will be the same as the button's title.
_A function should be specified, which will be called when the button is clicked._

Have the additional text:

_A function should be specified, which will be called when the button is clicked_ , **where the title is passed as the parameter to the function.**

**Comment by jarvisteach** [comment]
Definitely - thank you.

**Comment by cliverlong** [comment]
Richard,

You have done a fabulous job here, the code of course, but particularly: (I) ease of installation (ii)  the layout appearance, and “logical presentation” of the examples on your website. 

I have done the “GitHub Star” thing.

Clive

Sent from Mail for Windows 10

**Comment by jarvisteach** [comment]
Thanks for the feedback! It's definitely a work in progress, and held back a bit by the fact I only get time to work on it during school holidays - but it's getting close to what I want it to be!

**Comment by cliverlong** [comment]
I will try and work my way through all the examples on the site over the
next half term.

Every time I write a simple Python routine for the classes,  I will try a
build an appJar version and feedback any issues or observations via gitHub.

Ta,

CRL

**Comment by jarvisteach** [comment]
That will be most helpful, again, thank you!
