### ISSUE TITLE
Allow icons to be used anywhere?

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#248]
Pretty much as title, I'd like to use the built-in png icons before a label, I can't seem to find anything about doing this in the docs. :(

**Comment by jarvisteach** [comment]
A couple of thoughts here:

* Adding an image actually creates a label and embeds the image in it. You can simply call `.addImage()` and pass it the path to an icon - the icons live in `gui.icon_path`

* There's no support for mixing images & text in a single label - but you can access the label an image is embedded in and play around with it using the tkinter commands. The image labels all live in a dictionary called: `gui.n_images` (calling `.addImage()` returns the image object, not the Label).

**Comment by mpmc** [comment]
> Adding an image actually creates a label and embeds the image in it. You can simply call .addImage() and pass it the path to an icon - the icons live in gui.icon_path.

Ah, thanks! Could you add a note to the docs about this? :)

**Comment by jarvisteach** [comment]
Will do, will also look into options for labels with both images & text as a separate request...

**Comment by jarvisteach** [comment]
OK, decided to include an extra function - addIcon, it does the work for you...

**Comment by jarvisteach** [comment]
also addIconButton
