### ISSUE TITLE
import does not work

### ISSUE THREAD

**Issue by kuelshammer** [jarvisteach/appJar#251]
I installed appJar via

`sudo pip3 install appjar`

If I typ in `pip3 list` I can see that appjar (0.7.0) has been installed. But `import appJar`and `import appjar` does not work. I can use appJar by including the appJar folder from zip download.

**Comment by jarvisteach** [comment]
I'm not sure why that wouldn't work...

If you did `pip3 install appjar`, then `import appJar` should work - assuming you are running your code with python3

**Comment by jarvisteach** [comment]
Closing, as assume resolved.
