### ISSUE TITLE
Grid Size

### ISSUE THREAD

**Issue by keithterrill** [jarvisteach/appJar#255]
How do we define the size of the Grid?

app.addGrid("tbl",[["H1","H2","H3"],["1","2","3"]],action=press,addRow=press)
app.setGridWidth("tbl",800)
app.setGridHeight("tbl",800)

I thought the setGridWidth and setGridHeight would do this.

PS: I find it slightly confusing to call this Grid when the geometry manager is grid.

**Comment by jarvisteach** [comment]
Currently, these 2 config options are getting ignored, I'll get them included.

True, there is a bit of a conflict - but the majority of the audience won't know what geometry managers are, and those that do, can probably handle it :) One day, I have an alternative grid to implement, and I'll probably bring in some kind of simpler *waffle* class - that just gives a grid of labels, a bit like the micro:bit widget...

**Comment by jarvisteach** [comment]
Had a quick look at this - interesting issue with config implementation...

If a subClass class config on the superClass, and the superClass also calls config on its super - we get stuck in a recursive loop.

In this scenario:
* SimpleGrid isa ScrollPane isa Frame  
* When super.config() is called in SimpleGrid, it passes self as a parameter  
* When super.config() is called in ScrollPane, it uses the self parameter, which was the SimpleGrid - thereby calling the same config() function  

Might need to look at how super.config() is being used, and fix it for extended inheritance trees...

**Comment by keithterrill** [comment]
Regards GRID, Waffle Class. At this time I would consider naming it "Table". That would reflect the 2 dimensional aspect of the Grid, keep in line with other systems (such as dBASE and all of its relatives, example: Visual Foxpro), and be something that is not already named in appJar.

**Comment by jarvisteach** [comment]
Closing this, see #266
