### ISSUE TITLE
.SetPollTime(time)

### ISSUE THREAD

**Issue by tooManyArguments** [jarvisteach/appJar#257]
when using for example:

```
    def genericFunctionNamer():
        print("stuff")
    def superGenericFunction():
        print("other stuff")

    app.registerEvent(genericFunctionName)
    app.registerEvent(superGenericFunction)
    app.setPollTime(120)
```

This still runs the events constantly. Is .setPolltime(time) working as intended, or at all? (is my syntax off??)

**Comment by jarvisteach** [comment]
`app.registerEvent()` is specifically for creating infinite loops. So its purpose is to keep looping forever. Calling `app.setPollTime()` allows you to change how frequently it repeats

If you want to stop the functions from being called, you have two options:
* add a condition at the beginning of the function, telling it when not to not run
* Use `.after()` to simulate your own loops

I;ve recently updated the docs to try to explain all of this, have a read through: http://appjar.info/pythonLoopsAndSleeps/

**Comment by jarvisteach** [comment]
Closing this, as assumed resolved.
