### ISSUE TITLE
Can I position .addLabelEntry() on a grid layout?

### ISSUE THREAD

**Issue by chrisisbd** [jarvisteach/appJar#258]
Is it possible to use .addLabelEntry() (and the other functions with 'Label') on a grid?

I've tried:-

app.addLabelEntry("Date:", "dateEnt", 0, 1)

but it produces an error because it's expecting a string rather than an integer in those third and fourth parameters.

**Comment by jarvisteach** [comment]
Grid should work for all labelled widgets.

But there’s only 1 parameter when creating the widget. The text displayed will also be the widget’s name.

You can also try naming the 2 numeric parameters - `row=0, column=1`

**Comment by chrisisbd** [comment]
Yes, I've just worked that much out, so now I have:-


app.addLabelEntry("dailyChecks", 1, 0)

So how do I get the value entered now as the entry doesn't (seem to) have a name?  Is the name the same as the displayed text?

By the way appJar is *brilliant*!  I have written one program using PyQt but this is *so* much easier and I can concentrate on the 'business logic' rather than programming issues.

**Comment by chrisisbd** [comment]
Oops, sorry, I should have read your reply more closely:-

"...The text displayed will also be the widget’s name...."

Thank you.
