### ISSUE TITLE
SpinBox in reverse order

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#26]
SpinBox items are in the opposite order to expected

So the initial action is to scroll up - not right!

**Comment by frakman1** [comment]
This issue is still broken. I was able to get around it by reversing my list:
```python
app.addLabelSpinBox ( "Number of xxx", list(reversed(range(10))))
```

Any plans on fixing it?

**Comment by Ndr6** [comment]
Thanks @frakman1 for the workaround

**Comment by frakman1** [comment]
My pleasure. Glad I could help someone out.
