### ISSUE TITLE
useTtk bug

### ISSUE THREAD

**Issue by chrisisbd** [jarvisteach/appJar#260]
I know this is beta but I guess reporting problems is what you need.

I have the following rather trivial program:-
```

#!/usr/bin/python3 
from appJar import gui

# create the GUI & set a title 
app = gui("Boat Log")

def blExit(x):
    app.stop()

app.useTtk()


app.addLabelEntry("Daily Checks")

app.addButtons( ["Exit"], blExit)   
 
 
# start the GUI 
app.go() 
```
It gives an error traceback:-

```
# add labels & entries 
# in the correct row & column 
app.addLabelEntry("Log Date")Traceback (most recent call last):
  File "/home/chris/bin/aj.py", line 17, in <module>
    app.addButtons( ["Exit"], blExit)
  File "/home/chris/bin/pymods/appJar/appjar.py", line 6723, in addButtons
    frame.config(background=self.__getContainerBg())
  File "/home/chris/bin/pymods/appJar/appjar.py", line 10636, in config
    self.configure(cnf, **kw)
  File "/home/chris/bin/pymods/appJar/appjar.py", line 10652, in configure
    super(__class__, self).config(cnf, **kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1333, in configure
    return self._configure('configure', cnf, kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1324, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-bg"
```

Removing the app.addButtons( ["Exit"], blExit)  gets rid of the error.

While I'm about it I've just noticed that adding the app.useTtk() doesn't seem to actually change anything, the resulting GUI looks indentical.  This is on xubuntu 16.04, maybe I'm getting the tkinter widgets anyway.

**Comment by daun20** [comment]
I also get that error. Using
`app.addButton(...)`
instead of
`app.addButtons(...)`
will work. This is probably due to the -bg command which is not available in Ttk.

**Comment by chrisisbd** [comment]
On Thu, Oct 12, 2017 at 07:22:17AM -0700, daun20 wrote:
> I also get that error.

> Using app.addButton(...) instead of  app.addButtons(...) will work.

Aha, thank you, I wasn't using app.addButtons() for any particular
reason except that it was what was there before.  app.addButton()
actually makes more sense anyway.


> This is probably due to the -bg command which is not available in Ttk.
> 
I guess it's trying to set a background colour but why does it do it
for multiple buttons but not for a single one?

-- 
Chris Green

**Comment by jarvisteach** [comment]
Yes, adding the `ttk` flag has opened up a massive can of worms!

A lot of the grouped style widgets were broken under ttk. I think I've now gone through and fixed most of them. In my dev environment, I'm not getting any errors with the above code - can you double check what version of appJar you're running?

**Comment by daun20** [comment]
On my machines Windows 7 Python 3.6 and Windows 10 Python 3.6 both running appjar version 0.8.2 installed today with` pip install appjar`.

Error:

```
Traceback (most recent call last):
  File "appjar102.py", line 21, in <module>
    app.addButtons( ["Exit"], blExit)
  File "C:\ProgramData\Anaconda3\lib\site-packages\appJar\appjar.py", line 6723, in addButtons
    frame.config(background=self.__getContainerBg())
  File "C:\ProgramData\Anaconda3\lib\site-packages\appJar\appjar.py", line 10636, in config
    self.configure(cnf, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\appJar\appjar.py", line 10652, in configure
    super(__class__, self).config(cnf, **kw)
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1479, in configure
    return self._configure('configure', cnf, kw)
  File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1470, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: unknown option "-bg"
```

**Comment by chrisisbd** [comment]
On Thu, Oct 12, 2017 at 05:31:02PM +0000, Richard Jarvis wrote:
>    getting any errors with the above code - can you double check what
>    version of appJar you're running?
> 
I'm running version 0.82

-- 
Chris Green

**Comment by daun20** [comment]
Just a small notice: I found out that the OptionBox widget is not themed by ttk.

**Comment by jarvisteach** [comment]
There is already an issue for ttk ( #189 ) - going to close this and mention it there.

According to this, http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/ttk-widget-set.html , OptionBoxes aren't available in ttk. But I've added it to look into...
