### ISSUE TITLE
callFunction for Entry after submitting "Enter" with Keyboard

### ISSUE THREAD

**Issue by daun20** [jarvisteach/appJar#261]
Is it possible to have an Entry with a callFunction? For example I would like to update / re-create another Widget after pressing "Enter" inside an Entry.

Even if I use
```
app.addEntry("p1")
app.setEntry("p1", 0.5, myfunction)
```
the callFunction "myfunction" is never called - at least I couldn't figure it out yet. Of course I'm able to use an extra "Run" button for that functionality...

**Comment by jarvisteach** [comment]
Have a look here: http://appjar.info/pythonEvents/ - you need a **submitFunction**

**Comment by daun20** [comment]
Merci beaucoup!
