### ISSUE TITLE
PhotoImage in appJar

### ISSUE THREAD

**Issue by ian-moorhead** [jarvisteach/appJar#262]
I am getting Tkinter errors:
_tkinter.TclError: image "pyimage1" doesn't exist
with the following code using appJar. (using Python 2.7)

import numpy as np
import matplotlib.pyplot as plt
import Tkinter as tk
root = tk.Tk()

from appJar import gui

from PIL import Image, ImageTk

def press(btn):
	print(btn)

image = Image.open('C:\Users\sciVision\OneDrive\sciVisionRenaissance\software\Python\simVision\data\images\images.jpg')
photo = ImageTk.PhotoImage(image)

app = gui()
app.setFont(10)
app.addButton('One', press)
app.addButton('Two', press)
app.addImageData('im', photo, fmt='PhotoImage')
app.go()

**Comment by jarvisteach** [comment]
I'm not surprised!

You've created another instance of Tk() - that's going to throw everything...

Having multiple Tks doesn't work well - try getting rid of the `root=tk.Tk()` line, appJar is a Tk() instance, so you don't need a second one...

**Comment by jarvisteach** [comment]
But, then you'll have to move the image creation code inside appJar:

```
from appJar import gui 
from PIL import Image, ImageTk

def press(btn):
    print(btn)

app = gui()
app.setFont(10)
app.addButton('One', press)
app.addButton('Two', press)
photo = ImageTk.PhotoImage(Image.open("images.jpg"))
app.addImageData('im', photo, fmt='PhotoImage')
app.go()
```

**Comment by ian-moorhead** [comment]
Richard,

Many thanks and I much appreciate your quick response. I put the Tk 
instance in as a last resort to be honest.

Your code works but at present I can't see what is different from what I 
was trying before I logged the query but I'll work on it.

Your code is great btw - I've been working to learn PyQt but this is so 
much more straight forward! I'm a vision scientist modelling visual 
perception -  laser glare for example and so I need to be able to create 
visualisations of the outputs of the models.

Thanks again

Ian

**Comment by mpmc** [comment]
@ian-moorhead 
> Your code is great btw - I've been working to learn PyQt but this is so
much more straight forward! 

Indeed, I too looked at other modules & found them rather complicated. I initially was going to use plain tkinter but came across appJar!

@jarvisteach And whilst writing this I realised appJar doesn't have a logo? I'd like to link to appJar (using a logo) in the about dialog :).

**Comment by jarvisteach** [comment]
Hi @mpmc - you're right no logo :(

I'm not particularly gifted in the artistic department... although I do have a favicon...
