### ISSUE TITLE
Initial window doesn't size itself to fit a grid (not grid layout)

### ISSUE THREAD

**Issue by chrisisbd** [jarvisteach/appJar#263]
Again this is a beta issue but that's how things get fixed.

If I have an .addGrid() that is moderately wide then the initial GUI window isn't sized to fit it, there's a horizontal scroll bar.  Shouldn't the window size itself to fit the width of widgets in it?

Is there any way to get the initial GUI window to fit my grid?  It will vary in size according to the data in it but it would be nice if the main window could automatically accommodate it.

Plus a more general sizing question - do the size functions know about percentages, i.e. can I set a label or an entry field to be (say) 50% of the width of the column it's in?

**Comment by jarvisteach** [comment]
Totally agree, would love to have the grid resize to fill the container - just haven't worked out how yet :(
I'm pretty sure it's already mentioned in another feature request around the grid (it's my personal biggest bug bear with the grid), if not I'll add it in.

There's currently no support for percentages, although I think it's something that could be look into, I'll add it as a separate feature request.

**Comment by chrisisbd** [comment]
On Fri, Oct 13, 2017 at 09:14:28AM -0700, Richard Jarvis wrote:
>    Totally agree, would love to have the grid resize to fill the container
>    - just haven't worked out how yet :(

Well it's the other way round really isn't it?  The container needs to
resize so the grid fits into it.  :-)


>    I'm pretty sure it's already mentioned in another feature request
>    around the grid (it's my personal biggest bug bear with the grid), if
>    not I'll add it in.
> 
OK.


>    There's currently no support for percentages, although I think it's
>    something that could be look into, I'll add it as a separate feature
>    request.
> 
Thank you.  I've since done a little digging to find out what units
are used to set sizes and it turns out that they're "text units" which
are the width of an average sized character.  This actually makes
things rather easier and better than I thought.  Maybe the
documentation could mention this somewhere (or maybe it does and I've
missed it!).

-- 
Chris Green

**Comment by jarvisteach** [comment]
The grid is made up of a ScrollPane widget, that sits in the GUI like any other widget. The ScrollPane then contains a Canvas (which can be bigger than the ScrollPane, and hence the GUI). On the Canvas is a Frame that contains a grid of Labels.

At the moment, I'm trying to get the Frame of Labels to stretch to at least fill the ScrollPane - something like setting the Frame to be the biggest of the size of the Frame and the size of the Canvas.

That will make small Grids look a bit nicer.

I agree, it would be nice to have the GUI grow a bit to accommodate medium sized grids, but that's a lot trickier...

I can query the Canvas to find out its size, then the GUI to find out its size, then the screen to find out its size - compare them and make some guesses. But, if there are other widgets in the GUI, or if the user has already set a width, I might get it wrong...

I also want to be able to allow users to specify a width/height for the Grid - that will apply to the ScrollPane and in turn stretch the Frame of Labels if necessary.

At the moment, an easy solution is to simply specify a width/height for the GUI that will accommodate what you need, but I'll definitely still keep looking into this...

**Comment by chrisisbd** [comment]
> 
>    At the moment, an easy solution is to simply specify a width/height for
>    the GUI that will accommodate what you need, but I'll definitely still
>    keep looking into this...
> 
Yes, absolutely, I will probably end up with other things in the same
frame that make it wide enough to accomodate my grid without having to
explicitly set the width.

-- 
Chris Green

**Comment by jarvisteach** [comment]
Closing, see #266
