### ISSUE TITLE
useTtk can't be used with go() when sub-classing [widgets branch]

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#269]
Below is an example :)

```
import gettext
import uuid
import appJar

# Setup gettext.
gettext.install('Hs602util')

class Hs602util(appJar.gui):
    """Simple HS602 utility using appJar."""
    def __init__(self):
        super().__init__()
        self.win_main()

    def lang(self, key):
        """Return string value of the requested key in values.

        :param key: key of the value you want.
        """
        values = {
            "main_title": _('HS602 Utility'),
        }
        value = None
        try:
            value = values[key]
        except KeyError:
            pass
        return str(value or uuid.uuid4())

    def win_main(self):
        """Main Window."""

        # Settings.
        self.setTitle(self.lang('main_title'))

app = Hs602util()
app.go(useTtk=True)
```

useTtk must be called from within the class. Might want to put a note on the docs about this :).

**Comment by jarvisteach** [comment]
You're on the wrong branch... next_release has the ttk fixes, widgets is where I've been working on some other stuff

Although, I am  now merging them back together

**Comment by mpmc** [comment]
> You're on the wrong branch... next_release has the ttk fixes, widgets is where I've been working on some other stuff

Yep, I know :)

> Although, I am now merging them back together.

I wasn't sure what branch you were actively working on so went with the one with the newest commits (at the time). I like to test things, even if "broken", yes, I'm weird :rofl: 

I'll switch back to next_release & report any issues I find there :)
