### ISSUE TITLE
Excel-like Table Sorting And Filtering with Grid

### ISSUE THREAD

**Issue by cicor143** [jarvisteach/appJar#271]
Hello Sir,

I am very impressed with **appjar** its very simple and easy to code but still very powerful. Building gui with your new updates was fun. I was testing Grid last night and I like it so far. Is there any possibility that you might add Excel-like Table Sorting And Filtering in near future(pretty please ^-^). Quick google [image search](https://10tec.com/articles/screenshots/advanced-datagridview-excel-like-auto-filter.png)? I am in process from moving to cross platform development and your tool is just great because of "_no dependencies_" policy. I can just use your tool and python that's it.

So Far I have not seen any python gui that offers similar functionality with table or grid tried many like qt, wxWidget, pygubu, kivy etc you name it non has these kind of features. If you take my word and will make those features it will be big steps towards next generation of highly functional and user friendly gui for everyone. Thanks for creating this project, single cell brain people like me will greatly appreciate your efforts. If my question is bit here and there than I am sorry this is my first time asking on github 😅  also does your grid is GC (garbage collection) ready?

**Comment by jarvisteach** [comment]
Will add this to the grid feature request.

**Comment by jarvisteach** [comment]
@cicor143 could you explain a bit more what you're after with GC?

What does appJar need to do to support this?

**Comment by cicor143** [comment]
@jarvisteach wow that was quick reply and thanks for adding feature request. About GC (garbage collection) I have recently learned that every widgets have its limitations like grid or table have when we pull millions of data from database and feed that to table or grid some times it will overwrite each other based on how widgets are written. Most of the time python does cleanup afterwards but in some cases it does not. Take simple example we have 500 memory blocks to write in(allocated by default), when we pull 2000 data from database and put it in grid it will need 2000 memory blocks to write in, after 500 blocks written in memory either it will stop and pop up message like overflow or start overwriting same memory blocks again and thats not good. And its solution would be dynamic memory allocation and object destruction which are no longer needed to free up the memory. That was simple theory sometime because of poor implementation of the widgets it will just stop responding or fail to load. 

link to Knowledge ==> [effbot.org](http://effbot.org/pyfaq/how-does-python-manage-memory.htm)
[python.org](https://docs.python.org/3/library/gc.html). Because I am not expert on GC sorry, just trying to help 😓

**Comment by jarvisteach** [comment]
Thanks for this! In which case, I would say appJar is not GC ready!

I imagine appJar is quite memory inefficient - I've done no analysis on that at all (yet) - I'm sure there are a million places where things could be optimised, and cleaned up to improve memory management, I'll add it as a new feature request.

**Comment by jarvisteach** [comment]
Closing this - sorting implemented, efficiency raised as new issue.
