### ISSUE TITLE
Google Maps don't load - no Tooltip imported

### ISSUE THREAD

**Issue by House-Kitty-Mew** [jarvisteach/appJar#275]
![screenshot from 2017-10-17 00-52-12](https://user-images.githubusercontent.com/20118119/31653023-f1a53bca-b2d5-11e7-99e0-6c36a643b151.png)

**Comment by jarvisteach** [comment]
Is it a standard installation?

Could you let me know the appJar & python version as well as what platform.

It looks like a problem with the tooltips.. not seen that before...

**Comment by jarvisteach** [comment]
Hi @House-Kitty-Mew - this is definitely a bug!

I can't believe it got through testing! The tooltip class hasn't been imported - this was a feature added in the 0.8 release.

There are a couple of short-term fixes:

1) Add a tooltip to something, before adding the map (that will import the tooltip class, and is probably why testing did;t pick up on it):
```
app.addLabel("title", "Map Demo")
app.setLabelTooltip("title", "title")
```

2) You could roll back to 0.07:

```
pip3 uninstall appjar
pip3 install -Iv appjar==0.070
```

3) If you're feeling really adventurous - you could add a line of code to the `appjar.py` file. Find the `.addGoogleMap()` function, and add `self.__loadTooltip()` at the top, just after: `self.__loadURL()`.

---

I'll try to get an emergency path out in the next day or so.

**Comment by House-Kitty-Mew** [comment]
I am a long time python dev so i just added the code, its working fine now, I am creating a simple app pair with qpython3 on the phone to allow me to track and record my phones location every minute, it will have awesome features like history and logging and location stay time, its gonna be cool, but the only way to run the tracker app is through qpython3 on android lol

**Comment by jarvisteach** [comment]
Sounds really interesting - let me know how you get on.

I've got a lot more planned for the map widget - markers are there, but can probably be improved.

I think I've got a way to implement scrolling - just need to do it...
