### ISSUE TITLE
Message boxes are too small?

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#276]
Text that appears in message boxes is wrapped due to the window being too small, an example.

![image](https://user-images.githubusercontent.com/2352508/31784520-e65e286e-b4f9-11e7-8413-e9f0c93504f2.png)

Additionaly, could the buttons be changed to fill their container?

**Comment by jarvisteach** [comment]
These are generic tkinter dialogs - don't think there's any way to adjust them...

Instead, you could create your own custom popup, using subWindow.

**Comment by mpmc** [comment]
@jarvisteach Ah, I see, sorry for the noise!
