### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by SoraTheDev** [jarvisteach/appJar#277]
Hello. I'm currently having an issue with appJar. When I try to run my python file, it says there is no module in my system called tkinter. I checked my list of modules and tkinter was not in it. I also tried to find a website to download tkinter, but I couldn't find any. How can I solve this?

Thank you.

**Comment by mpmc** [comment]
What OS are you using? If ubuntu, try
```sudo apt install python-tk``` (python2) or ```sudo apt install python3-tk``` (python3).

**Comment by SoraTheDev** [comment]
I am using Windows 10. Should I try to use pip to install tkinter?

**Comment by mpmc** [comment]
If you have pip installed yes, that'll work too. :)

**Comment by jarvisteach** [comment]
As mentioned above - this isn't an appJar issue, but rather a missing package. appJar is tkinter, so if tkinter's not installed, appJar won't work.

Hopefully you got it installed.
