### ISSUE TITLE
Thread issues

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#281]
There seems to be some weird issues with thread (on next_release).

```self.thread(self.device_info_thread, None, **kwargs)``` 
result:
 ```TypeError: thread() got an unexpected keyword argument 'addr'```. 

Seems thread "eats" unpacked variables?

calling ```self.thread(self.device_info_thread, kwargs)``` 
result: 
```Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
TypeError: device_info_thread() takes 1 positional argument but 2 were given
```
The only positional argument is self.. ```def device_info_thread(self, **kwargs):``` thread always passes kwargs as args, an example.

```
self.thread(self.device_info_thread, None, kwargs)
def device_info_thread(self, *args, **kwargs):
        print(args) <-- this prints all args and kwargs!
        print(kwargs)
```
While testing this I crashed my machine (hard lock) & made Python die three times :rofl:.

**Comment by mpmc** [comment]
Sadly it doesn't. I now get..

```
xception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 599, in callit
    func(*args)
  File "/home/mark/.local/lib/python3.5/site-packages/appJar/appjar.py", line 1999, in thread
    t = Thread(target=func, *args, **kwargs)
  File "/usr/lib/python3.5/threading.py", line 778, in __init__
    assert group is None, "group argument must be None for now"
AssertionError: group argument must be None for now
```

Possible fix [here](https://stackoverflow.com/questions/39631335/python-multithreading-error-group-argument-must-be-none-for-now).

**Comment by jarvisteach** [comment]
third time lucky?

**Comment by mpmc** [comment]
Yep, ```self.thread(self.device_info_thread, None, **kwargs)``` works, thanks :)

**Comment by mpmc** [comment]
Discovered another kwargs issue :disappointed: 

```
self.after(100, self.thread, self.device_info_thread, **kwargs)
```
with error..
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "/home/mark/.local/lib/python3.5/site-packages/appJar/appjar.py", line 3151, in <lambda>
    return lambda: funcName(param)
  File "gui2.py", line 211, in connect_btn
    self.device_connect(**values)
  File "gui2.py", line 250, in device_connect
    self.after(100, self.thread, self.device_info_thread, **kwargs)
TypeError: after() got an unexpected keyword argument 'addr'
```

**Comment by jarvisteach** [comment]
Phew - I think this one isn't my fault :)

tkinter's `after` function doesn;t support `**kwargs` : http://effbot.org/tkinterbook/widget.htm

**Comment by mpmc** [comment]
> Phew - I think this one isn't my fault :)

It's not too much of an problem but I thought you should be aware so you can make a note of it in the "after" doc :).

I'll just call the methods directly instead of using after, my initial intention was to add a small delay so the operation could be cancelled.

**Comment by jarvisteach** [comment]
The docs only mention `*args` - so you can still pass arguments, just not named ones...

http://appjar.info/pythonLoopsAndSleeps/#sleeps

**Comment by mpmc** [comment]
> The docs only mention *args - so you can still pass arguments, just not named ones...

Yep, I know, but most people whenever they see *args, assume they can use **kwargs as well :tongue:

**Comment by jarvisteach** [comment]
Fair point!
