### ISSUE TITLE
Docs incorrect: questionBox (and maybe others) don't return True/False

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#283]
_Branch = next_release_

The docs say that all message boxes return True/False, for questionBox this isn't correct as it returns a yes/no string.

**Comment by jarvisteach** [comment]
Yup - there's a mistake there. The question box functions differently to all the others and returns the stings yes/no. I need to update the docs...

Or, I could change the functionality to have it also return true/false?

**Comment by mpmc** [comment]
> Or, I could change the functionality to have it also return true/false?

I think having all the message boxes output the same would be awesome :)

**Comment by jarvisteach** [comment]
Changed.
