### ISSUE TITLE
High Sierra - FinderKit FileProvider conflict issue?

### ISSUE THREAD

**Issue by popsquirrel** [jarvisteach/appJar#285]
Hi,

I'm a newbie to both appJar & Git so there's that.

I was experimenting with appJar and using the addDirectoryEntry widget on High Sierra (on my laptop) and on choosing a directory I get the following message in my Terminal window:

_objc[22336]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffa3f62a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x115da4cd8). One of the two will be used. Which one is undefined._

My python program continues to run and I can choose the directory and it's returned correctly so it seems to be an info message rather than a critical bug. 

On my Sierra desktop this message doesn't appear and the python program continues to work as expected. 

On Googling I came across similar issues reported by others but with reference to Java and other languages.

Has anyone else faced this and/or is there a solution?

Thanks!

**Comment by jarvisteach** [comment]
I think this has nothing to do with appJar or git - this sounds like the version of tcl/tkinter you're using isn't fully compatible with High Sierra. 

A quick Google shows similar issues reported on other tkinter tools - the dialog shown for choosing directories is straight out of tkinter, and looks like it has issues.

My Mac won't go past El Capitan, so I have no way of testing it - but you should look to update python/tkinter/tcl...

**Comment by popsquirrel** [comment]
You're right. I installed tcl-tk (8.6.7) and python 3.6.3 using homebrew and I get the same issue when simply running the following in python in a terminal window:

>>> from tkinter import filedialog
>>> from tkinter import *
>>> root = Tk()
>>> root.dirname = filedialog.askdirectory(initialdir = "/",title = "choose your directory")

message:
_objc[18327]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff93ba8a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x10a692cd8). One of the two will be used. Which one is undefined._

The dialog does work though and does return the chosen directory, but there's this unsightly 'mess'age.

Looks like an OS issue. I hope it gets cleared up in an update.

If anyone else has found a workaround/fix, that'd be great!

Thanks!

**Comment by popsquirrel** [comment]
Definitely a High Sierra issue - same thing happens using PyQt5 and the QtWidgets.QFileDialog.getExistingDirectory():

_objc[18793]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff93ba8a70) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1106fdcd8). One of the two will be used. Which one is undefined._

oh, well...

**Comment by jarvisteach** [comment]
Closing this issues as can't be resolved at this end.

**Comment by thiruthani** [comment]
Hi,

Is this issue fixed, as it was quoted earlier OS issue. I'm facing the same while using R console to save the history. 

Help is much appreciated. Thank you folks. !
