### ISSUE TITLE
Subwindow ListBox formatting issues

### ISSUE THREAD

**Issue by jnecus** [jarvisteach/appJar#291]
Hello, loving appJar so far!

My issue is that when loading a subwindow and initialising my ListBox, the ListBox doesn't snap to the edges. See image:

Here's my code:

```
      app.startSubWindow("Adding Variables", modal=True)
        app.setBg(colour)
        app.setFont(title_size,font)
        app.addLabel("addVarTitle", "Adding Variables")
        app.setLabelBg("addVarTitle",col)
        app.setLabelFg("addVarTitle", col)
        
        app.addListBox("var_options",all_vars)
        app.setStretch("both")
        app.setSticky("nesw")
        app.setListBoxMulti("var_options")
        app.setListBoxGroup("var_options")
```

Here's an image of my problem:
![window](https://user-images.githubusercontent.com/18306309/32505830-0ac600ec-c3db-11e7-983e-612d90273ab0.jpeg)

**Comment by jarvisteach** [comment]
I think it might just be the order of the commands - the `stretch` & `sticky` settings only take affect from the point they are set. Try moving them to be the first commands after starting the subWindow, and they should then apply to the list/label...

**Comment by jnecus** [comment]
That seemed to fix it! Thanks!

**Comment by jarvisteach** [comment]
Good news :)
