### ISSUE TITLE
more robust pin use on googlemaps

### ISSUE THREAD

**Issue by House-Kitty-Mew** [jarvisteach/appJar#293]
I was hoping that the placing of pins could be expanded, I have a project that would really help if i could place pins like this with these features.

.placepin(mapID, pinColor[hex], pinID, lat, long, removeLastPin[true/false])

for example, if I had a team of people and need to set a pin for a person in a color team i would

.placepin('map3', '#fffff', 33, 500.345654, 300.456743, true)

**Comment by jarvisteach** [comment]
A function already exists in the next_release branch: `.setGoogleMapMarker()`

I've updated it to receive more parameters:
* location - a string containing anything...
* size - optional size (tiny, mid, small)
* colour - optional colour, standard names, or hex in the format 0xffffff
* label - a single character (A-Z, 0-9)
* replace - if true, will replace the last added marker

**Comment by jarvisteach** [comment]
Additional function to remove a marker, based on the label.

**Comment by jarvisteach** [comment]
Will close this request, as an ongoing issue is open for Map features: #174
