### ISSUE TITLE
removeFileEntry leaving behind button

### ISSUE THREAD

**Issue by jnecus** [jarvisteach/appJar#302]
Hello,

As stated when I try to use app.removeFileEntry I am left with a grey button as per the screenshot below:

![screenshot from 2017-11-24 15-10-04](https://user-images.githubusercontent.com/18306309/33215940-9e0fe254-d129-11e7-9a94-1f657cbe55ca.png)

**Comment by jarvisteach** [comment]
What version of appJar are you on?

Try replacing it with `app.removeEntry()`.

The entry functions are all being merged into one - so that function no longer exists in the next release...

**Comment by jnecus** [comment]
I'm using version "0.82.1"

Tried what you said, but seem to get exactly the same result.

**Comment by jarvisteach** [comment]
Sorry, I tested this against my dev build. This issue has already been resolved in the upcoming release, so I'm going to close it.
