### ISSUE TITLE
Function keys? Arrow keys?

### ISSUE THREAD

**Issue by dicroce** [jarvisteach/appJar#303]
How do I specify the arrow keys or the F1-N keys when using bindKey()?

**Comment by jarvisteach** [comment]
You should be able to bind any of the keys using this function, check out the list here for the name of every key:

http://effbot.org/tkinterbook/tkinter-events-and-bindings.htm

The arrow keys are: `<Up>`, `<Down>`, `<Left>`, `<Right>` and the function keys will look like: `<F1>` etc...

For example:
```
from appJar import gui 

def press(btn):
    print(btn)

app=gui()
app.addLabel("title", "Red")
app.setBg("red")

app.bindKey("<Up>", press)
app.bindKey("<Down>", press)
app.bindKey("<Left>", press)
app.bindKey("<Right>", press)
app.bindKey("<Right>", press)
app.bindKey("<F1>", press)
app.bindKey("<F2>", press)

app.go()
```

**Comment by jarvisteach** [comment]
I'll update the docs to include some details on this...

**Comment by jarvisteach** [comment]
I'm also going to add two extra functions to `.bindKeys()` and `.unbindKeys()` that will both take a list of keys and call the bind/unbind function...

**Comment by dicroce** [comment]
Cool. That is exactly what was needed. :) I was able to get my app done with your help (a metadata tagger for VOC format image databases for deep learning).
