### ISSUE TITLE
Incorrect author attribution for tkinter-png

### ISSUE THREAD

**Issue by hokaze** [jarvisteach/appJar#307]
I appreciate your work in creating a more beginner-friendly GUI library for python and am flattered you're using my old code from when I was a first year student in your project, but the README.md for appJar attributes [tkinter-png](https://code.google.com/archive/p/tkinter-png/) to Johann C. Rocholl, not [myself](https://github.com/hokaze).

[Johann](https://github.com/jcrocholl) is responsible for [png.py](https://github.com/jcrocholl/pypng), without which tkinter-png wouldn't have been possible, and is more worthy of being credited than I am...but all the same, I'd appreciate if the readme was updated to attribute pypng/png.py to Johann and tkinter-png to myself.
Or at the very least, update it so he's not being blamed for my shoddy ancient code, the poor guy!

Thanks for your work both on appJar and in helping preserve tkinter-png since the Google Code archiving. Wishing you the best of luck with this project in the future.

**Comment by jarvisteach** [comment]
And thanks @hokaze for sharing your code! Back when I first started, only supporting one image type was causing all kinds of problems, I was desperate for a way to make it easier for kids to use any file type - and stumbled across your solution. It worked, so it stayed in!

I've updated the attribution in the next release!
