### ISSUE TITLE
Can i build gui with a "modern layout"?

### ISSUE THREAD

**Issue by abioneperhobby** [jarvisteach/appJar#310]
appJar looks like an awesome project,
but, also reading the documentation, i have not understand if i can build gui with a "modern look and feel" as, for example, transparency, rounded borders. etc
There is a way to obtain gui like this?
![image](https://user-images.githubusercontent.com/2149815/33332149-c388b97e-d463-11e7-8dd9-51c0b1563558.png)
thanks.

**Comment by jarvisteach** [comment]
appJar is a wrapper for tkinter. So, it supports all the features of tkinter. The widgets are a bit "old fashioned" looking, which is a shame, but it does have some features (like transparency).

I'm aiming to get ttk support fully working in the 1.0 release, but in the meantime you;re stuck with tkinter...

**Comment by abioneperhobby** [comment]
Thanks a lot.
Have a nice day.
