### ISSUE TITLE
accept images in memory from PILLOW?

### ISSUE THREAD

**Issue by wrishel** [jarvisteach/appJar#314]
(Closing this issue. I changed my mind.)

In would like to load and manipulate an image in pillow and then load them into an appJar UI. Is there a way to do this other than writing one out to a file and reading it back in?

Thanks

**Comment by WilfriedBl** [comment]
Yes, it does work. I am able to show a little thumbnail of JPG pictures.
`from PIL import Image, ImageTk

im = Image.open(full_name)
    size = (128, 128)
    im.thumbnail(size)
    img = ImageTk.PhotoImage(im)
    im_orientation = ""
    if image_item.orientation   == 1:   pass
    elif image_item.orientation == 3:   img = ImageTk.PhotoImage(im.transpose(Image.ROTATE_180))
    elif image_item.orientation == 6:   img = ImageTk.PhotoImage(im.transpose(Image.ROTATE_270))
    elif image_item.orientation == 8:   img = ImageTk.PhotoImage(im.transpose(Image.ROTATE_90))
    else:
        im_orientation = " ["+str(image_item.orientation)+"]"

    gui.openLabelFrame("Image " + item)
    gui.setImageData("Thumb" + item, img, fmt='PhotoImage')
    gui.stopLabelFrame()`

**Comment by wrishel** [comment]
@WilfriedBl -- thanks! Very helpful.
