### ISSUE TITLE
FileEntry/DirectoryEntry

### ISSUE THREAD

**Issue by unigraph1** [jarvisteach/appJar#315]
It would be nice to have ability to change text in button which is now set to "File"/"Directory" in FileEntry/DirectoryEntry widget.

![image](https://user-images.githubusercontent.com/33515016/33524125-f1eca0d0-d816-11e7-9035-2a3d368bcde0.png)

Sorry if this option already exists and I'm missing it.

**Comment by jarvisteach** [comment]
There's currently no direct support for this, however, you can go in and edit the button manually. When you add the file entry, it returns the widget, you can modify that widget:
```
fe = app.addFileEntry("e2")
fe.theButton.config(text="new text")
```

Or, in one line: `app.addFileEntry("fe1").theButton.config(text="new text here")`

You can also change the default text as follows: `app.setEntryDefault("e1", "new default")`

**Comment by unigraph1** [comment]
Okay. Thank you!
