### ISSUE TITLE
Add buttons with images

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#316]
Is it possible that you could add a new button or modify it to allow the user to add an image to it (similar to buttons on the toolbar) instead of or alongside text? An example would look something like this:

![button icons](https://user-images.githubusercontent.com/33980939/33810561-fcfbca22-ddfd-11e7-9f93-ccfa248ebc8a.PNG)

I feel that this feature would be useful, as it would liven up GUIs, and let you use a wider range of icons and images than what Unicode gives and what Python supports.

Thank you!

**Comment by jarvisteach** [comment]
There is already a feature to add image & icon buttons - but with the text hidden.

An optional parameter could be introduced - `align` - and if set will declare where to position the image relative to the text.

**Comment by pavi2410** [comment]
You can also use icon fonts
