### ISSUE TITLE
publish docs for next_release?

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#318]
Pretty much as title really :).

I understand they're still WIP but having them available compiled just like the release docs would be really really useful!

Opinions? :)

**Comment by jarvisteach** [comment]
I'm hoping to push out version 0.9 this coming weekend - so they'll be out then.

**Comment by mpmc** [comment]
OK awesome!

![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png)
