### ISSUE TITLE
Reference a widget by a variable

### ISSUE THREAD

**Issue by pavi2410** [jarvisteach/appJar#319]
Can this block of code be written

```
# add & configure widgets - widgets get a name, to help referencing them later
app.addLabel("title", "Welcome to appJar")
app.setLabelBg("title", "red")
```
as this?
```
title = app.addLabel("Welcome to appJar")
title.setBackgroundColor(Color.RED)
```

**Comment by pavi2410** [comment]
I mean referencing a widget by a variable rather than a string.

**Comment by pavi2410** [comment]
This is what I have tried

![image](https://user-images.githubusercontent.com/28837746/33998145-ae4ba962-e10c-11e7-832b-1a24570211fc.png)

**Comment by pavi2410** [comment]
@jarvisteach Please, can you look into this?

**Comment by jarvisteach** [comment]
Hi @pavi2410 - what you mentioned is not really how appJar is designed.

It was designed to encapsulate all the widgets, and to give you get & set functions for each widget.

However, it is possible to modify any of the widgets directly.

When you add the widget, it is returned, so you can then call any tkinter functions on it, including the config function:

```
title = app.addLabel("title", "This is a title")
title.config(bg="red")
```
