### ISSUE TITLE
TabbedFrame font size doesn't match.

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#324]
As tittle. Something I noticed while messing around.

![image](https://user-images.githubusercontent.com/2352508/34220901-0d475d44-e5ae-11e7-87b2-0b8c1ef8d4b1.png)

May be something to do with the larger font settings I have in Budgie?

Interestingly with ttk it's fine but the background doesn't match!

![image](https://user-images.githubusercontent.com/2352508/34220989-61d497dc-e5ae-11e7-8e8c-fbc436f7a77a.png)

**Comment by jarvisteach** [comment]
Yeah, that was never implemented. I'll make sure it is configurable, and link it to the rest.
