### ISSUE TITLE
TypeError: error() takes 2 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#326]
```Python
Traceback (most recent call last):
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 633, in setTtkTheme
    from ttkthemes import ThemedStyle
ModuleNotFoundError: No module named 'ttkthemes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui.py", line 190, in <module>
    sys.exit(main(sys.argv))
  File "gui.py", line 183, in main
    app = Gui()
  File "gui.py", line 41, in __init__
    self.setTtkTheme('clam0')
  File "/home/mark/.local/lib/python3.6/site-packages/appJar/appjar.py", line 637, in setTtkTheme
    self.error("ttk theme: %s unavailable. Try one of: %s", theme, self.ttkStyle.theme_names())
TypeError: error() takes 2 positional arguments but 4 were given
```

**Comment by jarvisteach** [comment]
You're on a roll! That line doesn't look like it should break - there are only two arguments there, and although the second one is a list, it should just be passed as a parameter, and converted to a string.

But, I guess that's not happening for you (I can't reproduce it) - either way, I'll cast the second param as a string before passing it to make sure...

**Comment by mpmc** [comment]
> You're on a roll! 

Translation: "Oh god not him again!" ![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f606.png)

Sorry, I must be doing some weird stuff with your code to cause it to break!

**Comment by jarvisteach** [comment]
Hopefully resolved.
