### ISSUE TITLE
Hide starting separator in menus

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#329]
As title, reference [here](http://www.tkdocs.com/tutorial/idle.html).

**Comment by jarvisteach** [comment]
`tearable` should be defaulting to False in all menus. So you shouldn't be seeing tearable menus.

Have a look here: http://appjar.info/pythonBars/#create-menus - there is a tearable parameter on `.createMenu()` which defaults to False...

**Comment by mpmc** [comment]
Sorry I meant the starting separator.

![image](https://user-images.githubusercontent.com/2352508/34339443-04056f3e-e96c-11e7-85bf-4e72eb74a45a.png)

**Comment by jarvisteach** [comment]
That separator has been put in deliberately, and only on linux - I don't remember why though...

Will have to have a play and work out why I did it

**Comment by mpmc** [comment]
> That separator has been put in deliberately, and only on linux - I don't remember why though...

Perhaps to split the built-in menu options from defined ones?

**Comment by jarvisteach** [comment]
The menu in the grid doesn't need this, so I'll remove it from the others...
