### ISSUE TITLE
Set FileEntry Widget

### ISSUE THREAD

**Issue by CanvasBag** [jarvisteach/appJar#330]
Greetings,

I'm starting to use this lib and I've experienced some difficulties regarding editing FileEntry and DirEntry widgets, specifically:

- is it possible to add a text before this kind of widget? There is label widget which have a text before the entry text box, but for this kind of widget I'm having trouble to find out in the documentation if it is possible to do that;

- in second is it possible to change the font for this specific widget? In the documentation there is the example to change specific fonts to label widgets with this line of code "app.getLabelWidget("l1").config(font="Times 20 italic underline")" but for the FileEntry is there a .confi property? I also have read the tkinter option at the end of the page, but can't figure it out how to use that.

thank you!

**Comment by jarvisteach** [comment]
appJar uses a grid layout, so you can position as many widgets (labels) as you like before the fileEntry.
You can also change the font of the entry:
```
app.addLabel("f1", "Choose a file:", row=0, column=0)
app.addFileEntry("file", row=0, column=1)
app.getEntryWidget("file").config(font="Times 20 italic underline")
```

**Comment by jarvisteach** [comment]
Alternatively you can add a `LabelFileEntry` to include a label on the `FileEntry`:
```
app.addLabelFileEntry("file")
app.getEntryWidget("file").config(font="Times 20 italic underline")
app.getLabelWidget("file").config(font="Times 20 italic underline")
```
