### ISSUE TITLE
.setScaleChangeFunction() ignore changes made by .setScale()

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#331]
Hi,
I'm creating a music player, with a scale to show how much of the music has played, and for it to be draggable so the user can skip to different parts of the song. I have an issue where when the scale is updated using `.setScale()`, the function in `.setScaleChangeFunction()` gets called, resulting in the music skipping slightly.
Is there any way for `.setScaleChangeFunction()` to ignore changes made by `.setScale()`?
Thanks!

**Comment by jarvisteach** [comment]
If you have a look at the docs, most (all?) set functions have a `callFunction` parameter. If you set this to False, it shouldn't call the associated change function: http://appjar.info/pythonWidgets/#set-scales

**Comment by The-Sleepy-Penguin** [comment]
Thanks - that worked. I guess this was a simple case of me not reading the docs!
