### ISSUE TITLE
Add new tab to existing?

### ISSUE THREAD

**Issue by AiAe** [jarvisteach/appJar#332]
I'm trying to add new tab after its made is that possible? I try everything to get it working.

**Comment by jarvisteach** [comment]
Should be possible, assuming there are only three tabs:
```
def press(btn):
     app.openTabbedFrame("tabs")
     app.startTab("Four")
     app.addLabel("t4", "Tab Four")
     app.stopTab()
     app.stopTabbedFrame()
```

**Comment by AiAe** [comment]
Hi, thanks for your answer but I get error when I try to do that, only works for the first tab and error.
Exception: Attempted to open invalid tabbedFrame: IRC
This is my code you can see on line from 40 to 47 I create the tab and on line 128 I call the function.

https://gist.github.com/anonymous/7207f9cd3f9a30c76f6b1f4a68d5143b

**Comment by jarvisteach** [comment]
Away from a computer now, but I think you need to change the `create_tab` function - get rid of the 1st and last 2 lines. All the starting/stopping is being done in the `on_welcome` function, so you don’t need to repeat it.

**Comment by AiAe** [comment]
So I try it no errors but the tabs do not get add on private message. The interface bugs out 

https://i.aiae.ovh/l/S57LQ6.png

It should get added there instead of doing the above thing.. https://i.aiae.ovh/l/QZ4UYX.png

https://gist.github.com/anonymous/869c2fca90710242a88e1ba01035fcec

**Comment by jarvisteach** [comment]
Ah, OK - it's because there's no start/stop tab in `on_privmsg` - I didn't see you were using the `create_tab` function from two places.

I would move the start/stop tab lines from the loop in `on_welcome` into the `create_tab` function. That way they can be shared by both`on_welcome` and `on_privmsg`.

**Comment by AiAe** [comment]
Yep thanks for the help :D, and Happy New Year

**Comment by AiAe** [comment]
I don't see it documented but is there a way to close/remove tab?

**Comment by jarvisteach** [comment]
To clear an entry, just call `app.clearEntry(entryName)`.

There's no way to remove a tab (yet) - I'll raise it as a new feature request.

You could implement it yourself for now:

```
def deleteTab(frameName, tabName):
    print(tabName)
    tabs = app.widgetManager.get(app.Widgets.TabbedFrame, frameName)

    tab = tabs.widgetStore[tabName][0]
    tab.pack_forget()
    tab.destroy()
    pane = tabs.widgetStore[tabName][1]
    pane.grid_forget()
    pane.destroy()

    del tabs.widgetStore[tabName]

    # to clean up the selected/highlighted tabs
    if tabs.highlightedTab == tabName:
        tabs.highlightedTab = None

    if tabs.selectedTab == tabName:
        tabs.selectedTab = None
        for key in list(tabs.widgetStore.keys()):
            if not tabs.widgetStore[key][0].disabled:
                tabs.changeTab(key)
                break

     tabs._TabbedFrame__colourTabs()
```

**Comment by AiAe** [comment]
This code is not working since there is no widgetManager in app?
AttributeError: 'function' object has no attribute 'get'

**Comment by jarvisteach** [comment]
Sorry, that code will only work against the next_release, my bad.

The line that gets the tabbedFrame (using the widgetManager) needs to be changed. When you start the tabbedFrame, it returns a pointer to the tabbedFrame, you could just use that instead.
