### ISSUE TITLE
Set Notebook Tab/Note?

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#334]
Hi,
Is there a way to change the currently selected Notebook tab/note? Like a Notebook version of `.setTabbedFrameSelectedTab()`
Thanks

**Comment by jarvisteach** [comment]
Have a look on here: http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/ttk-Notebook.html

**Comment by The-Sleepy-Penguin** [comment]
I've had a look and I think that `.select([tabId])` needs to be used, but I have no idea as to how I would use this with widgets created by appJar...

**Comment by The-Sleepy-Penguin** [comment]
Actually... I found that by doing `app.getNotebookWidget("title").select([tabId])` I managed to get this to work.
Thanks!
