### ISSUE TITLE
Button title should only be passed if the method accepts arguments

### ISSUE THREAD

**Issue by mpmc** [jarvisteach/appJar#335]
Say I have a button, this button calls method foo..

```python
def foo():
    print('I was called!')
```
Because the button title is always passed, but the foo function doesn't accept any - you get..

```python
TypeError: foo() takes 0 positional arguments but 1 was given
```
The obvious solution to this would be to handle this in the foo method like so.

```python
def foo(button=None):
    print('I was called!')
```
or 

```python
def foo(*args, **kwargs):
    print('I was called!')
```
While this works, the problem is that many analysers complain if an arg is passed but not used. An example of this is shown [here](https://www.codacy.com/app/hello_58/appJar/issues/index)

**Comment by jarvisteach** [comment]
Some ideas here: https://stackoverflow.com/questions/847936/how-can-i-find-the-number-of-arguments-of-a-python-function

In `MAKE_FUNC` `funcName` could be inspected, and if it receives no parameters, then we could pass None...

**Comment by jarvisteach** [comment]
This is now possible, and in fact affects all widgets that specify a function.

Now, if a function has no parameters, no arguments will be passed...

**Comment by jarvisteach** [comment]
There's an issue with this...
* If a function being referenced is part of a class, then it will have a parameter - `self`.
* The inspection didn't take this into account.
  * If it sees no args, then no parameter is passed
  * If it sees an arg, then the parameter is passed - so if the arg was `self` (required when building a class) things broke down.

For now, I will assume that if a variable is called `self` we treat it as not being present, and don't pass an argument.

However, users might not call the object parameter `self`, so this isn't a bulletproof solution. Can we inspect the function to determine if it is part of a class?

**Comment by jarvisteach** [comment]
A bit of googling reveals: `inspect.ismethod(object)` which returns True of the function is bound to a class, and will therefore contain a `self` parameter.

**Comment by jarvisteach** [comment]
Seems to do the trick.

Also, got rid of the need to specify **discard parameters**, args* will handle 0 or more parameters, so can set it to always discard.

Will need to go through and remove all references, and test them...

**Comment by jarvisteach** [comment]
The discard parameter has now been removed.
