### ISSUE TITLE
Configure properties for gui settings

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#340]
Pull request #320 introduced a `property` for the title.

There should be properties for many other settings:
---
* [x] title
* [x] icon
* [x] fg - set only
* [x] bg - set only
* [x] font - set only
* [x] labelFont - set only
* [x] buttonFont - set only
* [x] transparency - set only
* [x] size
* [x] fullscreen
* [x] visible
* [x] resizable
* [x] location
* [x] stretch
* [x] sticky
* [x] guiPadding - set only
* [x] padding - set only
* [x] inPadding - set only
* [x] row - not in configure function
* [x] stop function - set only
* [x] logLevel
* [x] logFile
* [x] r-click edit menu
* [x] ttkTheme
* [x] language
* [x] enter  

As well as a group function:
---
* [x] There should also be a `.configure()**kwargs)` function that will take all of these, and pass them to the various properties.

And container parameters:
---
`**kwargs` can then be included as a parameter in the start container functions (including the main constructor) and then passed to the `.configure(**kwargs)` function.
* [x] labelFrame
* [x] toggleFrame
* [x] tabbedFrame
* [x] tab
* [x] panedFrame
* [x] pane
* [x] pagedWindows
* [x] subWindow
* [x] frame
* [x] scrollPane
* [x] notebook
* [x] note

**Comment by mpmc** [comment]
>  labelFont - issue here, internal attribute

Start the with an underscore to avoid naming issues? labelFont becomes _labelFont

**Comment by jarvisteach** [comment]
`.configure(**kwargs)` & `.config(**kwargs)` now included that take each property above as a parameter, these then pass them to the relevant function.

This required renaming the configParser attribute.

**Comment by BlueKenny** [comment]
how can i use the "topmost" configuration off tkinter on my gui?

**Comment by WilfriedBl** [comment]
Not sure, this answers you question BlueKenny, I was able to access root level methods of Tkinter by using ".topLevel", for example:
```
gui = appJar.gui(" ....)
text_on_clipboard = gui.topLevel.clipboard_get()
```
"clipboard_get", as well as "clipboard_append" and "clipboard_clear" are methods provided by Tkinter on a root level. Similarly you should be able to access other methods of Tkinter.

**Comment by BlueKenny** [comment]
Thanks it works :) Do you know where to ask if i have other questions?

**Comment by WilfriedBl** [comment]
I only know to search on the Internet. The best is to try with varying search arguments. However I believe, I found the term ".topLevel" using code completion in the IDE (PyCharm), whereas the examples on the Internet usually use "root".
A good resource to ask questions is https://stackoverflow.com/  But most times I found the responses without asking a question - just by searching.

**Comment by jarvisteach** [comment]
This is pretty much done now.

All containers can take parameters, and they mostly work.
There is an issue with setting a couple of properties on containers (mainly `sticky`), as they currently take them as a parameter to apply when gridding widgets, this results in unexpected behaviour and will need revisiting (also see #328).

**Comment by jarvisteach** [comment]
See commit 4984dd5ef435c01078b987e86d465b5c77a81f7a

**Comment by jarvisteach** [comment]
Two issues to resolve:
* Fullscreen unhappy
* Transparency unhappy

**Comment by jarvisteach** [comment]
OK - gone as far as I want to go on this for now.

All properties in and tested. Nearly all have getters & setters (except stopFunction & enterKey)

There is an issue in testing where `size` stops working, but I can't reproduce it in a standard GUI, so going to ignore that for now.
