### ISSUE TITLE
favicon.ico not defined

### ISSUE THREAD

**Issue by rockstar8577** [jarvisteach/appJar#343]
I'm having issues with packing my script into an exe with pyinstaller. If I do a simple script it packs fine. However if I move to a more advanced script with more multiple windows and such it has an issue with

```python
Traceback (most recent call last):
  File "Bot.py", line 70, in <module>
  File "site-packages\appJar\appjar.py", line 4471, in startSubWindow
  File "site-packages\appJar\appjar.py", line 2444, in setIcon
  File "tkinter\__init__.py", line 1865, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\Josh\Desktop\Python\sandbox\dist\Bot\appJar\resources\icons\favicon.ico" not defined
[7488] Failed to execute script Bot
```

Now i've tried getting around this by including the appJar folder into my exe location. This does get it to start, but only for a debug build with pyinstaller. If i package it into a self-contained exe it just doesn't run and gives a message of "failed to execute script". Not sure how to get it to stop using the icon for the subwindow.

**Comment by jarvisteach** [comment]
By default, on Windows - appJar uses it's own icon for all windows.

To stop it using the icon, you can set it to None: `app.winIcon = None` straight after you create the gui object.

That should prevent subWindws from having an icon. But you might still have issues with the main window having an icon...

Let me know how you get on.

**Comment by jarvisteach** [comment]
I'll also include an option in the next release to turn off icons when appJar is created.

**Comment by fullmacht** [comment]
I have the same problem. Tried to set `app.winIcon = None`and by using pyinstaller set default icon to my file. When i use `showIcon = False` my program did not start.
