### ISSUE TITLE
Extra Toolbar options

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#346]
Hello (again!),
As the Toolbar is essentially made up of buttons, could you give the Toolbar the same options as buttons for various things such as foreground/background colour, relief, state etc. ?

**Comment by jarvisteach** [comment]
In the upcoming release, the buttons live in `app.WidgetManager.group(app.Widgets.Toolbar)` - so you can iterate through them and change them how you like.

In the current release they live in `app.n_tbButts` - but this will be removed soon...

**Comment by The-Sleepy-Penguin** [comment]
Hmm, I might be missing something here, but the following code (I'm using the `next_release` branch):
```python
from appJar import gui

def a(press):
    print(press)

with gui() as app:
    app.addToolbar(["A", "B", "C", "D"], a, findIcon=False)
    for button in app.WidgetManager.Group(app.Widgets.Toolbar):
        app.setBg("blue")
```
Produces this: `AttributeError: 'function' object has no attribute 'Group'`

**Comment by jarvisteach** [comment]
group should be lower case

**Comment by The-Sleepy-Penguin** [comment]
Must have left that typo in there when I was messing around - it still doesn't work when I use it correctly (it still gives me `AttributeError: 'function' object has no attribute 'group'`)

**Comment by jarvisteach** [comment]
Ha - sorry, I had a typo too:
```
    for button in app.widgetManager.group(app.Widgets.Toolbar):
        app.setBg("blue")
```

**Comment by jarvisteach** [comment]
Oh, and note that instead of `app.setBg()`, you'll need to do stuff to the buttons: `button.config(bg="blue")`

**Comment by The-Sleepy-Penguin** [comment]
I tried your solution, but it didn't work straight away - when looping, Python decided that it would only take the dictionary key and leave the object, so it would always throw an error. In the end I found that this worked (and so made the `A` button blue):
```python
var = app.widgetManager.group(app.Widgets.Toolbar)
var["A"].config(bg="blue")
```
I guess that this method is arguably more useful, as you can use the name of the button instead of having to loop through it...

**Comment by The-Sleepy-Penguin** [comment]
Just tried to set the background of the button with ttk - `_tkinter.TclError: unknown option "-bg"` is back again :(

**Comment by jarvisteach** [comment]
Ah, that won't work in ttk mode! Instead, you'll need to create a style, and add it to all the toolbar buttons:

```
# create a new style for the buttons
app.ttkStyle.configure("TB.TButton", background="blue", foreground="yellow")
# loop through all the buttons
buttons = app.widgetManager.group(app.Widgets.Toolbar)
for button in buttons:
    # and apply the style
    buttons[button].config(style="TB.TButton")
```

**Comment by The-Sleepy-Penguin** [comment]
Cheers! I think that everything is working now :)
