### ISSUE TITLE
Display Mouse position

### ISSUE THREAD

**Issue by nitroxplunge** [jarvisteach/appJar#348]
Quick question: Is there a way to get the current mouse position with appJar? Can I access the tKinter that appJar is creating and get the mouse position from that?

And i'm not talking about when theres a click - i'm trying to get a constant update of the mouse position.

**Comment by nitroxplunge** [comment]
Sorry - I didnt read

**Comment by jarvisteach** [comment]
Hi @nitroxplunge - the root is just stored as `app.topLevel`, so to get it to show the mouse coordinates in a label, try something like:

```
from appJar import gui 

def motion(event):
    app.setLabel("pos", str(event.x)+":"+str(event.y))

with gui("Show Position", "600x600") as app:
    app.topLevel.bind('<Motion>', motion)
    app.addLabel("pos")
```

**Comment by nitroxplunge** [comment]
Thanks - this works for what I am doing. It's a good thing to note that this will only tell you the position inside your grid block if you are using grid mode, though.
