### ISSUE TITLE
How to pass values from SubWindow1 to SubWindow2?

### ISSUE THREAD

**Issue by abhijit-dey** [jarvisteach/appJar#349]
I am trying to make the below code work, but I am not able to display name. It just shows "Welcome {}":

app = gui()

def press(name):
    if name == "Enter":
    	app.hideSubWindow("sb1")
    	app.showSubWindow("sb2")
    elif name == "Exit":
        app.stop()
        
app.startSubWindow("sb1") 
app.addLabel("lb1", "This is a label inside sb1.")
app.addLabel("lb4", "What is your name?", 1,0)
app.addEntry("e1", 1,1)
name = app.getEntry("e1")
app.addButton("Enter", press)
app.stopSubWindow()

app.startSubWindow("sb2") 
app.addLabel("lb2", "This is a label inside sb1.")
print(name)
name = ("Welcome", name)
app.addLabel("lb3", name)
app.addButton("Exit", press)
app.stopSubWindow()

app.go(startWindow="sb1")

**Comment by jarvisteach** [comment]
Hi @abhijit-dey - remember the code for constructing the GUI all gets run at the start, before the user even sees it. So the line `name = app.getEntry("e1")` runs before the user types anything in. And then later, these lines:
```python
print(name)
name = ("Welcome", name)
app.addLabel("lb3", name)
```

Also get run before the user has typed anything.

Instead you can get rid of most of those lines (except where you make `lb3`), and **set** the label when the user presses the button. Add these two lines to the `press()` function right in the first IF statement:
```python
name = app.getEntry("e1")
app.setLabel("lb3", "Welcome " + name)
```

**Comment by abhijit-dey** [comment]
Awesome, thanks I was able to fix it now, this is what I modified the code to:

app = gui()

def press(name):
    if name == "Enter":
    	name = app.getEntry("e1")
    	name = ("Welcome", name+".")
    	app.hideSubWindow("sb1")
    	app.openSubWindow("sb2")
    	app.addLabel("lb3", name, 1)
    	app.stopSubWindow()
    	app.showSubWindow("sb2")
    elif name == "Exit":
        app.stop()
        
app.startSubWindow("sb1") 
app.addLabel("lb1", "This is a label inside sb1.")
app.addLabel("lb4", "What is your name?", 1,0)
app.addEntry("e1", 1,1)
app.addButton("Enter", press)
app.stopSubWindow()

app.startSubWindow("sb2") 
app.addLabel("lb2", "This is a label inside sb1.", 0)
app.addButton("Exit", press, 2)
app.stopSubWindow()

app.go(startWindow="sb1")

This is now working as expected.
