### ISSUE TITLE
Feature click twice in list item?

### ISSUE THREAD

**Issue by BlueKenny** [jarvisteach/appJar#350]
Hey, this isn't a bug report, its a question or a feature proposition  ;)
Is it possible to call a function every time the user click two times on a item in a listbox ?

Ps appJar runs every day on every computer at my work :) good job

**Comment by jarvisteach** [comment]
Glad to hear you're using it :)

There's is no direct support for double-clicks, but you can add it yourself easily enough:

```
def press():
    print("double clicked")

lb = app.addListBox("dbc", [1, 2, 3, 4, 5])
lb.bind("<Double-1>", lambda *args: press())
```

Add the list box as normal (getting a reference to it), then bind the event.

**Comment by WilfriedBl** [comment]
Thanks a lot, Richard!  I had the same question, but didn't dare to ask ... just tried and it works fine.

**Comment by jarvisteach** [comment]
Glad I could help - don't be afraid to ask questions, that how's things get better!

And yes, anything you can do tkinter, you can do in appJar - appJar is just a wrapper to hide some of the complexities of tkinter, and include some extra features...

**Comment by BlueKenny** [comment]
Thanks a lot :)
