### ISSUE TITLE
More TabbedFrame options

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#351]
Hi,
I was just wondering - if the TabbedFrame is a custom widget (I guessing that it is - I haven't seen it anywhere else apart from here) could you add some extra options for it?
For example, having an option to put the TabbedFrame on the side instead of the top (perhaps for some slightly more modern looking applications... - I guess you still can't get too modern with tkinter) like this:

![image](https://user-images.githubusercontent.com/33980939/35240649-05c4d264-ffac-11e7-8f25-0877b538dead.png)

Also, allowing images/icons to be used on the tabs themselves could also be another option, along with changing various properties of the tab buttons and any other widget that is a part of the TabbedFrame (a similar solution to the Toolbar??).

I understand that this is quite a big ask, so feel free to not take it on board.

**Comment by jarvisteach** [comment]
Have a look at issue #342 - that's something I've started working on, gives a side menu...

The code is here: https://github.com/jarvisteach/appJar/blob/next_release/examples/issues/issue342.py

Once I'm happy with the functionality, I'll roll it into a new container, it also has some improvements on how the pages are changed that I'll roll into the tabbed frame.

The 1.0 release will bring much more configurability across all widgets/containers, allowing for more customisation of the tabbed frame.

**Comment by The-Sleepy-Penguin** [comment]
Sounds good! It looks like 1.0 is a pretty big update. 😃
