### ISSUE TITLE
Help menu (-h)

### ISSUE THREAD

**Issue by rodrigo-apoc** [jarvisteach/appJar#354]
Hi.
Well, I don't know if it's a really "Issue" but, I have a config.py with appJar Lib, just a window test, simple layout. 
And, I also have a main.py that I'm importing some things from config.py.

My main.py has a Help menu (-h) on command-line. However, when I'm importing config.py (with appJar), my Help menu turns into appJar's Help menu.
There is a way to ignore appJar's Help menu and using just mine?

**Comment by jarvisteach** [comment]
Have a look here: http://appjar.info/pythonCommandLine/#disabling

You should just be able to set the ’handleArgs’ flag to False.

**Comment by rodrigo-apoc** [comment]
Thank you Richard <3
