### ISSUE TITLE
Transparent image background?

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#357]
As said in the title, is there any way of displaying an image with a transparent background? Currently, appJar will display what *would* be transparent as the background colour like so:

![image](https://user-images.githubusercontent.com/33980939/35482694-07c02ad0-0431-11e8-8e5f-f8f34222b81a.png)

Here is my code:
```python
from appJar import gui
from PIL import Image, ImageTk

with gui() as app:
    app.addLabel("l1", "", 0, 0)
    app.setLabelBg("l1", "black")
    app.setLabelSticky("l1", "nesw")
    app.addLabel("l2", "", 0, 1)
    app.setLabelBg("l2", "red")
    app.setLabelSticky("l2", "nesw")
    photo = ImageTk.PhotoImage(file="lightning bolt.gif")
    app.addImageData("image", photo, fmt="PhotoImage", column=0, row=0, colspan=2)

**Comment by jarvisteach** [comment]
Hi @The-Sleepy-Penguin - so, the image *does* have a transparent background, unfortunately the image is in a label, and labels can't be transparent. The colour you are seeing is the bg colour of the label holding the image. Compare the 2 images below (I've also set sticky to "" for the image):

No BG colour set:
![lb2](https://user-images.githubusercontent.com/13473435/35484077-844d2f74-0442-11e8-8b74-ce2c7ee69aa6.png)

BG set to green:
![lb3](https://user-images.githubusercontent.com/13473435/35484076-841cf142-0442-11e8-873d-8aab11c9c55f.png)

The only way around this, is to play widgets onto a canvas...

**Comment by jarvisteach** [comment]
Issue #327 is looking at canvas support, feel free to have a play:

```
with gui("Transparent Demo", geom="400x400", sticky="news") as app:
        canvas = app.addCanvas("c1")
        app.addCanvasRectangle("c1", 0, 0, 200, 800, fill="black")
        app.addCanvasRectangle("c1", 200, 0, 200, 800, fill="red")
        photo = ImageTk.PhotoImage(file="lb3.gif")
        canvas.create_image(200, 200, image=photo)
```

This gives:
![lb4](https://user-images.githubusercontent.com/13473435/35484198-a9d3fa5a-0444-11e8-97da-03580a24ec20.png)

**Comment by The-Sleepy-Penguin** [comment]
I have had a go, but I can't seem to get rectangular shapes on the canvas - they always become squares.
eg. When I use this: `app.addCanvasRectangle("canvas", 0, 0, 100, 250, fill="green")`, I get this:

![image](https://user-images.githubusercontent.com/33980939/35485760-de411428-045b-11e8-9f68-960599ea805b.png)

**Comment by jarvisteach** [comment]
Yeah - I noticed the same thing, there's a bug where the code is using the same parameter for x & y width. I've already fixed it in the next_release branch (canvas has only just been added in, and has;t had a lot of testing!)

For now, you can use:
```
canvas = app.addCanvas("c1")
canvas.create_rectangle(0, 0, 100, 250, fill="green")
```

**Comment by jarvisteach** [comment]
Actually, I think that’s the generic GUI padding.

Have a look here: http://appjar.info/pythonGuiOptions/#gui-configuration

You can set the padding dive with: `app.setGuiPadfing(0,0)`

**Comment by The-Sleepy-Penguin** [comment]
I've already done that as I thought that it was the GUI padding initially, but the border still stays when I use `app.setGuiPadding(0, 0)`, so I think it's the canvas widget padding (according to [this](http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/canvas.html) there is a default border of 2 pix) - here's the code that gives me the border:
```python
from appJar import gui
from PIL import Image, ImageTk
from time import sleep

def show():
    sleep(1)
    app.show()

with gui(size="62x37") as app:
    app.setGuiPadding(0, 0)
    app.hideTitleBar()
    app.setBg("white")
    canvas = app.addCanvas("c")
    
    l = []
    count = 0
    for i in range(9):
        r = app.addCanvasRectangle("c", count, 0, 6, 35, fill="green", width=0)
        l.append(r)
        count += 6
    app.addCanvasRectangle("c", 54, 11, 7, 15, fill="grey", width=0)
    app.addCanvasImage("c", 27, 20, ImageTk.PhotoImage(file="lightning-bolt2.png"))
    app.setCanvasOverFunction("c", [app.hide, show])

**Comment by jarvisteach** [comment]
Try adding this:

```
canvas = app.addCanvas("c1")
canvas.config(bd=0, highlightthickness=0)
```

I will include that in the default settings for the widget in appJar.

**Comment by The-Sleepy-Penguin** [comment]
Thank you. That worked great! 👍
