### ISSUE TITLE
Immage

### ISSUE THREAD

**Issue by donm001** [jarvisteach/appJar#358]
I am trying to display a gif image using “.image(title, value=None)” but try as I may it will not work. Has anyone got this to work in Python?

**Comment by jarvisteach** [comment]
Could you include a sample of the code that doesn't work?

If you try the below (with a valid image file), it should work:
```
from appJar import gui 
with gui() as app:
     app.image("image1", "lb3.gif")
```

**Comment by donm001** [comment]
Hi Richard
Thanks for this. I ampleased to say that I have now got this to work. May I add that your coding andweb site are excellent, and I have learned a great deal from just playing with thecode, as part of my Python learning curve. It is fun.
Well done
Regards
Don

    On Tuesday, 30 January 2018, 17:36, Richard Jarvis <notifications@github.com> wrote:
 

 Could you include a sample of the code that doesn't work?If you try the below (with a valid image file), it should work:from appJar import gui 
with gui() as app:
     app.image("image1", "lb3.gif")

**Comment by jarvisteach** [comment]
Thanks for the feedback :)
