### ISSUE TITLE
Color Picker Widget

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#364]
Can we get a simple color picket widget that returns the color in RGB or HSBK when we click on a color? Something like below:

![image](https://user-images.githubusercontent.com/5826484/35773718-ef203e9c-0927-11e8-8fd5-7348bccff5ca.png)

**Comment by jarvisteach** [comment]
There is the [colour picker dialog](http://appjar.info/pythonDialogs/#other-boxes), which gives something similar, and returns a colour.

It should be possible to take the code out of that, and expose it as an embeddable widget.

Something to be looked into...

**Comment by frakman1** [comment]
Nice! Thank you. It looks really good on my Mac and works well for my needs:
![image](https://user-images.githubusercontent.com/5826484/35897295-7b23e67e-0b8e-11e8-8181-ade6b67c8efc.png)

**Comment by jarvisteach** [comment]
Closing this, as I think the widget is a platform widget.
