### ISSUE TITLE
Append new items to AutoEntry Wedgets

### ISSUE THREAD

**Issue by mohamed-okasha** [jarvisteach/appJar#366]
When I trying to execute this line 

app.appendAutoEntry('titile',[list of items])

This error appears:
```
File "/home/mohamed/PycharmProjects/transfer_tool/venv/lib/python2.7/site-packages/appJar/appjar.py", line 8601, in appendAutoEntry
    entry.addWords(value)
AttributeError: Entry instance has no attribute 'addWords'
```

I used Python 2.7

**Comment by jarvisteach** [comment]
I think that's because you're calling the function on an entry that's not an AutoEntry.

You have to first create an AutoEntry:

```
from appJar import gui 

with gui("AutoEntry", "400x400") as app:
    app.addAutoEntry("e", ["a", "aa", "aab", "cc", "d", "e", "f", "g"])
    app.appendAutoEntry("e", ["zzz"])
```

However, there should be a more friendly error message, I'll change that!

**Comment by jarvisteach** [comment]
Error messages now updated
