### ISSUE TITLE
log messages

### ISSUE THREAD

**Issue by luc35** [jarvisteach/appJar#367]
Thanks for appJar!My project uses the logging module.  Unfortunately appJar injects its own messages between mine.  

For example, it injects: [Line 400->3422/SET_WIDGET_BG]: Config Label BG to #eee [Line 400->3330/SET_WIDGET_FG]: SET_WIDGET_FG: Button - #000000 [Line 400->3422/SET_WIDGET_BG]: Config Button BG to #eee [Line 400->2636/configureWidget]: Configuring: Reset of 3 with: width [Line 400->2636/configureWidget]: Configuring: Reset of 3 with: background [Line 400->3422/SET_WIDGET_BG]: Config Button BG to #ccc .... (long text)

I'm assuming this behavior is useful for appJar development, but not for appJar users.  Can this behavior be turned off?

**Comment by jarvisteach** [comment]
This is definitely an issue that needs fixing.

appJar logs a bunch of messages at the debug level, so if you switch up a level, you can hide most of those.

However, I understand that other users might want to log their own debug messages, and not have appJar messages.

There's no way to achieve this right now, however, I would like to include this feature.

I guess their are two way to achieve this:
* add a flag, to turn off appJar debugging
* introduce a custom debug level, at a lower priority than debug - is this possible?

I like the idea of the second, but have no idea if it's possible - I'll add it to the future list!

**Comment by jarvisteach** [comment]
OK - found a way to create a new log level: https://stackoverflow.com/questions/2183233/how-to-add-a-custom-loglevel-to-pythons-logging-facility

So, will introduce a TRACE level below DEBUG, and log all appJar *debug* messages at that level

**Comment by jarvisteach** [comment]
New log level added - TRACE, 5 below DEBUG.

All appJar messages now logged at this level.

Should resolve this issue.
