### ISSUE TITLE
Select a rectangular region over an image

### ISSUE THREAD

**Issue by vianamp** [jarvisteach/appJar#370]
Hi.

I am using `app.topLevel.bind('<Motion>', motion)` to capture the mouse position over an image.

Now, I'd like to draw a rectangular region based on the coordinates the user clicked on. Is that possible?

Thanks,

**Comment by jarvisteach** [comment]
appjar doesn't have any specific features for this.

However, you can use the canvas widget, to show the image, then draw a rectangle on the canvas in response to the mouse actions:

```
from appJar import gui 
x = y = rect = -1

def press(event):
    ''' start a new rectangle at mouse click '''
    global x, y, rect
    x = event.x
    y = event.y
    rect = c.create_rectangle(x, y, x, y)

def drag(event):
    ''' redraw the rectangle, to new coorindates '''
    c.coords(rect, x, y, event.x, event.y)

with gui("Drawing") as app:
    c = app.canvas("canvas")
    c.bind("<ButtonPress-1>", press)
    c.bind("<B1-Motion>", drag)
```
