### ISSUE TITLE
[Request] Implement app.getXXXBg() API

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#373]
Currently, I can write a color to a label using this method:

        app.setLabelBg(title, col)

However, there is no equivalent 'get' method like:

        app.getLabelBg(title, col)

This would be very a useful and is highly desirable feature to have.

**Comment by jarvisteach** [comment]
Although not directly supported through appJar functions, you can easily find out the bg of a widget using standard tkinter functions, `get("bg")`:

```
from appJar import gui

def changeColour():
    app.label("DEMO", bg=app.colourBox())
    app.label("DEMO", app.getLabelWidget("DEMO").cget("bg"))

with gui("Colours", "400x400", sticky="news") as app:
    app.label("DEMO", submit=changeColour)
```

**Comment by jarvisteach** [comment]
`next_release` now has a `.getXXXBg()` function.

Long-term, I think a function called `.getXXXProperty()` will be easier to manage, just a wrapper on cget.
