### ISSUE TITLE
Configurable text on labelled widgets

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#377]
When adding a labelled widget, it should be possible to set the text, rather than using the title.

**Comment by jarvisteach** [comment]
This feature is used in all these places:
* [ ] `.addLabelEntry(title)`
* [ ] `.addLabelNumericEntry(title)`
* [ ] `.addLabelSecretEntry(title)`
* [ ] `.addLabelAutoEntry(title, words)`
* [ ] `.addLabelScale(title)`
* [ ] `.addLabelOptionBox(title, values)`
* [ ] `.addLabelTickOptionBox(title, values)`
* [ ] `.addLabelSpinBox(title, values)`
* [ ] `.addLabelSpinBoxRange(title, from, to)`

Will need a bit of refactoring to allow them all to support it.

**Comment by mpmc** [comment]
I was actually going to open an issue about this!

Right now I'm unpacking..

```python
        no_devices = {
            'title': '{}'.format(_('\u2639 No devices were found on '
                                   'your network.\nCheck your '
                                   'firewall, and/or reboot your '
                                   'device, then re-scan. \u261B')),
            'pos': (0, 0),
            'sticky': 'nesw',
        }
```
Where with the others that use a separate title, value, I'm doing..

```python
        device_list = {
            'title': 'addr',
            'value': result,
            'pos': (0, 0),
            'sticky': 'nesw',
        }
```
Don't forget label frames, they too only support title, but no value :+1:

**Comment by jarvisteach** [comment]
A bit of inconsistency has crept in across a number of areas in terms of parameter naming:
* `title` - generally the ID used to store the widget
* `name` - the text displayed in a widget (when configurable)
* `label` - the text shown in labels for widgets, and sometimes to set a `name` as above
* `value` - usually the data to display in the widget

ListBoxes, SpinBoxes & Properties take a `values` parameter instead of `value`
OptionBoxes take an `options` parameter
And other widgets have specifically named parameters

I think there's a job to be done here in terms of making them constant, which will unfortunately break some people's code - perfect for the 1.0 release :)

Oh, and BTW - you can (now?) set the text on LabelFrames with the `name` parameter...

**Comment by mpmc** [comment]
I would keep, title (or maybe name is better, as it's the name of the widget?), value, and label. All the rest where they differ (```options```, ```values``` etc) could be replaced with value?
