### ISSUE TITLE
Any ideas how to achieve this kind of GUI?

### ISSUE THREAD

**Issue by abhijit-dey** [jarvisteach/appJar#383]
Hi I am trying to build a tool to display some info in the following way:
![image](https://user-images.githubusercontent.com/28615926/36293581-dae612e8-1300-11e8-836f-c07d71baf306.png)

Want to create a table of lines.
I will have multiple pages, can be any number of pages. 
Want to add 2 buttons at the last column for every row, Details and Edit. 

I am struggling to figure out how to make this kind of table. 

Any idea is welcome.

**Comment by jarvisteach** [comment]
There's no widget in appJar that's going to look like that.

The only thing we have is the Grid (soon to be Table) widget, which over time may get a bit closer to that look and feel, and a bit more customisable.

If that's not enough, you're going to have to make your own - either do the whole thing in tkinter, or develop your own class (in tkinter, extending Frame) and then add it to appJar using `app.addWidget()`

**Comment by jarvisteach** [comment]
Going to close this.

The next release will have some slightly better styling, with better configurability.

It will also accept a list for the `actionButton` parameter, which will create multiple buttons in the final column, each passing 2 parameters to the associated function (buttonName & rowNumber)

I will also create a separate change request for allowing more configuration on the entry row:
* drop-downs containing a list of options
* numeric entries
* string entries
* uneditable entries

**Comment by abhijit-dey** [comment]
Thanks.
