### ISSUE TITLE
Add support for ImageTk.PhotoImage in .addImage

### ISSUE THREAD

**Issue by The-Sleepy-Penguin** [jarvisteach/appJar#393]
Hi,
As said in the title, it'll be great if you could allow `app.addImage()` to take a `ImageTk.PhotoImage` object, like done previously with images on a canvas.

**Comment by jarvisteach** [comment]
This should already be possible, have a look here: http://appjar.info/pythonImages/#add-images

There is a function `.addImageData()`

**Comment by The-Sleepy-Penguin** [comment]
My bad - perhaps I should read the docs properly ***first*** before opening an issue...
Thanks :)
