### ISSUE TITLE
TextArea

### ISSUE THREAD

**Issue by Lamera** [jarvisteach/appJar#394]
Hi Richard
Sorry for raising an issue, didn't know how to contact you.

1. I have a TextArea and want a frame around it. How can I do that?

2. In the TextArea is [cmd/ctrl + a] for text selection not working.

3. How can I read/write from/in the clipboard on any OS?

Thank you for making such a good tool!

**Comment by jarvisteach** [comment]
Hi @Lamera  - this is exactly where I want stuff like this :)

Actually, I think text-selection should be supported in the text area widget on mac/linux/etc - at the moment, it seems that it's not, and in fact ctrl-a replicates the command prompt action of sending the cursor to the beginning of a line.

It's easy enough to add in, either manually, or into appJar. The below code creates a function that can be registered to both entries & textAreas:

```python
from appJar import gui 

def select_all(e):
    try: e.widget.tag_add("sel","1.0","end")
    except:
        try: e.widget.select_range(0, 'end')
        except: gui.trace('Unable to select all')
        
with gui("Select-All", font={'size':20}) as app:
    with app.frame("frame"):
        ta = app.textArea("text")
        e = app.entry("entry")
        
        ta.bind('<Command-a>', select_all)
        e.bind('<Command-a>', select_all)
```

**Comment by jarvisteach** [comment]
If you want to give the textArea a border, you can set some config options on it:
```python
ta.config(relief='groove', bd=3)
```

**Comment by jarvisteach** [comment]
To access the clipboard, you can call the following three commands:
```python
app.topLevel.clipboard_get()
app.topLevel.clipboard_append("hello")
app.topLevel.clipboard_clear()
```

**Comment by jarvisteach** [comment]
According to this article: https://stackoverflow.com/questions/5870561/re-binding-select-all-in-text-widget

There are a bunch of interesting bindings in tkinter:
* Select all: Ctrl + / vs Ctrl + a
* Cut: Ctrl + w vs Ctrl + x
* Copy: Meta + w vs Ctrl + c
* Paste: Ctrl + y vs Ctrl + v

The left ones are the original tkinter bindings, the right are the windows bindings.

All but the first one has been mapped, so should work. But ctrl-a needs remapping.

**Comment by jarvisteach** [comment]
Another issue I've noticed, is that pasting doesn't scroll the widget, so the paste could be updated.

**Comment by jarvisteach** [comment]
I will apply these changes at the class level, and also look at adjusting some other bindings to apply at the class level, so widgets like tables & maps also inherit them:

```python
self.topLevel.bind_class("Text","<Control-a>", self._selectall)

def selectall(self, event):
    event.widget.tag_add("sel","1.0","end")
```

**Comment by jarvisteach** [comment]
Bindings to look into:
* Tab/ShitTab on lots of widgets
* Click giving focus
* Entry - UP/DOWN arrows

**Comment by Lamera** [comment]
Thank you for your inputs!

**Bug in TextArea**
I noticed an error in the TextArea when trying to do this thing with ctrl+a:

```
2018-03-02 13:32:57.984 Python[17435:1246223] *** Terminating app due to uncaught exception 'NSRangeException', reason: '-[__NSCFConstantString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff531edfcb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff79e8fc76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff5327f9ed +[NSException raise:format:] + 205
	3   CoreFoundation                      0x00007fff5316a146 -[__NSCFString characterAtIndex:] + 102
	4   Tk                                  0x00007fff5f672353 TkpInitKeymapInfo + 731
	5   Tk                                  0x00007fff5f6781b1 Tk_MacOSXSetupTkNotifier + 798
	6   Tcl                                 0x00007fff5f572a50 Tcl_DoOneEvent + 300
	7   _tkinter.so                         0x0000000104a51a6e init_tkinter + 9763
	8   Python                              0x00007fff5d745f89 PyEval_EvalFrameEx + 2917
	9   Python                              0x00007fff5d745232 PyEval_EvalCodeEx + 1551
	10  Python                              0x00007fff5d74b2b4 _PyEval_SliceIndex + 504
	11  Python                              0x00007fff5d745b45 PyEval_EvalFrameEx + 1825
	12  Python                              0x00007fff5d745232 PyEval_EvalCodeEx + 1551
	13  Python                              0x00007fff5d74b2b4 _PyEval_SliceIndex + 504
	14  Python                              0x00007fff5d745b45 PyEval_EvalFrameEx + 1825
	15  Python                              0x00007fff5d745232 PyEval_EvalCodeEx + 1551
	16  Python                              0x00007fff5d6ec935 PyFunction_SetClosure + 802
	17  Python                              0x00007fff5d6cf581 PyObject_Call + 97
	18  Python                              0x00007fff5d6d9c9e PyMethod_New + 1180
	19  Python                              0x00007fff5d6cf581 PyObject_Call + 97
	20  Python                              0x00007fff5d6cbd4d PyObject_CallFunctionObjArgs + 178
	21  Python                              0x00007fff5d74609a PyEval_EvalFrameEx + 3190
	22  Python                              0x00007fff5d745232 PyEval_EvalCodeEx + 1551
	23  Python                              0x00007fff5d744c1d PyEval_EvalCode + 32
	24  Python                              0x00007fff5d763ad1 PyParser_ASTFromFile + 287
	25  Python                              0x00007fff5d763b78 PyRun_FileExFlags + 130
	26  Python                              0x00007fff5d7636fa PyRun_SimpleFileExFlags + 706
	27  Python                              0x00007fff5d77496c Py_Main + 3064
	28  libdyld.dylib                       0x00007fff7aa7f115 start + 1
	29  ???                                 0x0000000000000002 0x0 + 2
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Process returned -6 (0x-6)	execution time : 28.951 s
```
The error occurs when I type in a lot of data quickly.

**Frame**
Tried that a couple of times. I couldn't set up the frame. Do I something wrong?
```
ta.config(relief="groove", bd=3)
AttributeError: 'str' object has no attribute 'config'

Process returned 1 (0x1)	execution time : 0.570 s
```

**Comment by jarvisteach** [comment]
Try this code for the border:

```python
from appJar import gui 
        
with gui("Select-All", font={'size':20}) as app:
    ta = app.textArea("text")
    ta.config(relief='groove', bd=3)
```

For the error, it doesn't look to be an appJar error, bit rather something in tkinter/python.

I've had a quick Google, and there's some suggestion it's caused by special characters, that tkinter struggles with, can you reproduce the error, and tell me what you typed?

**Comment by jarvisteach** [comment]
Actually, I just managed to reproduce it by pressing <alt> + e on my Mac!

**Comment by jarvisteach** [comment]
In fact pressing alt with a whole bunch of different letters crashes it.

They also crash IDLE - I think this is a long standing issue on MAC, with the built in version of tcl/tk

There is nothing that can be done, you have to update your version of tcl/tk.
