### ISSUE TITLE
Transparency not supported on LINUX

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#397]
`app.setTransparency(0)` <br>
`2018-03-01 16:14:40,750 appJar:WARNING [Line 817->2627/setTransparency]: Transparency not supported on LINUX`

Is there an equivalent thing I can use for Linux? I really just want to hide the window while a screenshot is being taken. Is there a `minimize` function I could use instead?

**Comment by jarvisteach** [comment]
appJar has functions to `hide()` & `show()` as well as the new `visible` getter/setter:

```python
from appJar import gui 

def hide():
    app.visible = not app.visible

with gui() as app:
    app.label("DEMO SHRINK AND GROW")
    app.registerEvent(hide)
```

**Comment by jarvisteach** [comment]
If you want to be able to hide the GUI, and then have it reappear after a certain time, try something like:
```python
from appJar import gui 

def hide(btn=None):
    app.visible = not app.visible
    if btn is not None: app.after(2000, hide)

with gui() as app:
    app.label("DEMO SHRINK AND GROW")
    app.button("HIDE", hide)
```
