### ISSUE TITLE
Question: Mouse Coordinates in Widget, Mouse Click Event - how to obtain?

### ISSUE THREAD

**Issue by aleksaleks** [jarvisteach/appJar#399]
Hi,
I need help with 2 items::
1) Bind a mouse click event into the GUI. To test this out I tried what was given on the events page:
app.getEntryWidget("widget_name").bind("<FocusOut>", function_name, add="+") - changed a bit to <Button-1> and other defined stuff ...
But then I got an error "ItemLookupError: Invalid widgetName: p1"
The code is:
```python
app=gui()
canvas = app.addCanvas("c1")
canvas.create_oval(10, 10, 100, 100, fill="red", outline="blue", width=3)
canvas.create_line(0, 0, 255, 255, width=5)
canvas.create_line(0, 255, 255, 0, dash=123)
app.setCanvasOverFunction("c1", [enter, leave])
app.getEntryWidget("c1").bind("<Button-1>", leftclick, add="+")
app.go()
```
But that does not matter since I have tried it with other code, just labels and such, same error message.
Also, when I print out help('appJar.gui") there is no funtion such as getEntryWidget which I find odd.

2) Getting the mouse location within a widget.
When I print out help("appJar.gui"), under static methods I find " MOUSE_POS_IN_WIDGET(widget, event, findRoot=True)        |     returns the mouse's relative position in a widget", so I think "Awesome!!!".
So I integrate this into code and I get the error message "
  File "C:\Users\aaleksov\AppData\Local\Continuum\anaconda3\lib\site-packages\appJar\appjar.py", line 330, in MOUSE_POS_IN_WIDGET
    master = master.master

AttributeError: 'str' object has no attribute 'master'"

Please help. In the end "all" I want is to register a mouse click and get the coordinates inside the widget.
Alternatively I need to get the coordinates of the widget as with the help of the win32 module I can get the absolute mouse location on the screen. Still need the relative widget coordinates and registration of a mouse click.
 
Thanks a lot!

**Comment by jarvisteach** [comment]
Regarding your second issue, I think you're probably getting the parameters wrong. It looks like you;re passing the name of the widget, rather than the actual widget.

If you add the line: `print(app.MOUSE_POS_IN_WIDGET(canvas, event))` to the `leftclick()` function, you'll see slightly different X/Y coordinates.

**Comment by aleksaleks** [comment]
Thanks a lot this works great! And thanks for the quick response.
This resolved both issue.
