### ISSUE TITLE
call function once GUI starts

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#402]
Should be able to schedule a function to run, once the GUI is built.

Can be done with: `app.topLevel.after_idle(func)`

Should be wrapped up in appJar function and documented.

**Comment by fr43nk** [comment]
Does there already exists a hook when reading of the settings is done? I think such a function would be useful to apply restored settings to widgets.

**Comment by jarvisteach** [comment]
You can enable/disable settings - have a look here: http://appjar.info/pythonSettings/
