### ISSUE TITLE
Question: regards creating our own validation functions...

### ISSUE THREAD

**Issue by keithterrill** [jarvisteach/appJar#405]
I do not know if you have covered this but I am interested in creating my own specific Tkinter Validation function much like you have __validateNumericEntry(). Or as you used it in _entryMaker().

If possible something where we could register our own validateFunction and then pass it in via parameters: validate,validateFunction,d, i, P,s, S, v, V, W.

This is only needed for an Tkinter.Entry() field.

**Comment by jarvisteach** [comment]
You could add your own validate function to an entry...

Create your validate function: look at appJar’s `_validateNumericEntry()` for format. 

Then call `.config()` on an entry widget, passing the validate & validatecommand parameters.

**Comment by keithterrill** [comment]
Thank-you. After posting this question I began to wonder if this would be the answer. I will try to do this. You can close this. ;-)
