### ISSUE TITLE
TypeError: 'NoneType' object is not callable - in app.go() 

### ISSUE THREAD

**Issue by UmbertoCorvaglia** [jarvisteach/appJar#406]
I had this error when i tried to divide my code into 2 file: first one called "Gui.py" and second one called "BusinessGui.py". In the first i've put only the Gui-components without data and with the second file (BusinessGui) i fill these Gui-components.

Instead when i put all the code into a single file.py it works!

Traceback (most recent call last):
  File "Gui.py", line 179, in <module>
    __main__()
  File "Gui.py", line 176, in __main__
    G = Gui()
  File "Gui.py", line 172, in __init__
    self._app.go()
  File "../lib/appJar/appjar.py", line 1675, in go
    self.__poll()
  File "../lib/appJar/appjar.py", line 2051, in __poll
    e()
TypeError: 'NoneType' object is not callable

**Comment by jarvisteach** [comment]
I’ll need to see a simple sample of code to reproduce this...

**Comment by UmbertoCorvaglia** [comment]
Thank you for the answer but I've resolved the problem.

The bug was on my implemented code.
