### ISSUE TITLE
Connecting a database to a table

### ISSUE THREAD

**Issue by SergeiDrew** [jarvisteach/appJar#407]
I'm creating a school project for a simple employee management system, and i currently have a database that holds all of the information about a specific employees shift times, Im trying to display it within a table and i saw there were beta widgets for this, however when trying to use it i don't seem to be getting a table and no errors either,

my code:

`with app.labelFrame('MyShifts'):
         app.addDbTable("My Shifts", "users.db", "user_"+RealEN)`

I'm using SQLite3 and "RealEN" is a unique number given to each employee however SQLite doesn't allow tables within a database to start with a numerical value, any help would be appreciated. Thanks

**Comment by jarvisteach** [comment]
Are all the details in one table? If so, the third parameter should be the name of the table you are querying.

**Comment by SergeiDrew** [comment]
After adding in the code again i got this error?


![spelling](https://user-images.githubusercontent.com/7934958/37053510-40f0d484-2174-11e8-97d0-1a17adc68943.png)

**Comment by jarvisteach** [comment]
Are you on the latest version? Grids were renamed to tables in 0.91, if you’re on 0.9 you’ll need `addDbGrid()`
