### ISSUE TITLE
impossible to set height or Anchor or Align for  FileEntry widgets

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#412]
Hello New to appJar sorry if silly question.

I'm unable to set height of a file entry widget. My problem is that button to open file selector is too tall compared to field displaying file name. also since file paths are long I tried to ensure last part of path os always visible using Align and Anchor without success here is what I did. what is wrong with this?
```
app.addFileEntry("myEntry",1,4)
app.setEntryAlign("myEntry", "right")#"left", "right", "center"
app.setEntryAnchor("myEntry", "e") #"center", "n", "s", "e", "w", "ne", "nw", "se", "sw"
app.setEntryWidth("myEntry", 40)
```

getting console message:  Error configuring myEntry: unknown option "-anchor"

Thanks in advance

**Comment by jarvisteach** [comment]
Hi @pg-doceapower  - setting `anchor` & `align` both modify the `anchor` property of the widget.

Entry widgets have to have their `anchor` property set as 'LEFT' or 'RIGHT', they don't support 'e' & 'w'.

If you pass `e` or `w` to the `align` function, it'll change them to `LEFT` & `RIGHT`. The `anchor` function doesn't.

Entry widgets don't support the `height` setting, their height is determined by the size of the font. So, if you want to increase the height, you should change the font.

Setting `width` shouldn't have any issues...

So, this *should* work fine:

```
app.addFileEntry("myEntry",1,4)
app.setEntryAlign("myEntry", "right")#"left", "right", "center"
app.setEntryWidth("myEntry", 40)
```

**Comment by pg-doceapower** [comment]
Thanks!
