### ISSUE TITLE
Database refresh function not working

### ISSUE THREAD

**Issue by SergeiDrew** [jarvisteach/appJar#413]
After implementing a Database table into my code i found that it didn't refresh on it's own so i needed to use the refresh function, however when looking at the appJar website on the function it simply says i need to use `.refreshDbTable(Title)` however I followed this and i seem to get a weird error that gets called from within appJar saying:
![bug](https://user-images.githubusercontent.com/7934958/37177229-bdca70f2-2316-11e8-9242-2f78547e4bf8.png)

this is my code as follows:
![bug3](https://user-images.githubusercontent.com/7934958/37177245-cb6cf8d8-2316-11e8-9fb9-42605189be86.png)
![bug2](https://user-images.githubusercontent.com/7934958/37177240-c8ba79da-2316-11e8-8633-c13cc697a670.png)

Any idea to what's going on, am i using the refresh function wrong, I can't seem to find anything about it? thanks

**Comment by jarvisteach** [comment]
Yup - this is a bug, I'll push out a patch this weekend.
