### ISSUE TITLE
Entry's with same title.

### ISSUE THREAD

**Issue by jacobthetechy** [jarvisteach/appJar#414]
I have a app that I need to get similar data from the user in different windows, such as their name. But there does not seem to be a way to have several Entry's with the same title, or a way to differentiate between them. What would be a good way to get around this?

**Comment by jarvisteach** [comment]
Definitely can't have different entries with the same name - their name is a key in a dictionary.

I realise that this causes issues, especially across containers, where it makes sense to have widgets with the same name, and the container to be able to group them. But appJar doesn't support that right now, and I don't think it will for a while.

Instead, you'll just need to come up with a naming scheme - maybe the name of the container, followed by the widget's purpose?

**Comment by jacobthetechy** [comment]
I guess my problem was using addLabelEntry(), and the name for the entry is the same as the label. Could there be a optional label kwarg to be able to set the label text instead of the entry name?

The other work around would to have a label with the same text as all the other entries but a new name for the entry itself.

**Comment by jarvisteach** [comment]
Ah, OK - with the new naming conventions, this is already possible.

Try:
```python
app.entry('data1', label='AAA:')
app.entry('data2', label='AAA:')
app.entry('data3', label='AAA:')
```

That will create 3 labelEntries, each with the same label, but different titles.

At some point, post 1.0 release, I'll normalise all the functions, so that the old 'add' functions all support the same options.
