### ISSUE TITLE
user action still possible on a fileEntry widget

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#415]
I create a fileEntry then upon a condition want to enable/disable the widget. on version 0.91 when field is disabled, user can still 
* edit in the text area or
* click the button to open the file chooser

the field background is grayed out this is how I know the disable command was processed. I was expecting the button to be disabled and the file chooser to never open when field is disabled.

Am I doing something wrong?

**Comment by jarvisteach** [comment]
Definitely not doing something wrong!

The file entry is a compound widget, so I've never implemented disabling the whole thing. You can disable the entry: `app.disableEntry()` but that won't affect the button or remove the mouse event.

I'll need to add that in as a new feature.

**Comment by jarvisteach** [comment]
resolved in next release

**Comment by pg-doceapower** [comment]
Thanks!
