### ISSUE TITLE
is it possible to refresh/regenerate layout of a gui subset?

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#419]
in my cas I have tabs and toggleframes withing tabs. I need to add or remove a row or a column. do I need to refresh the entire gui when I do this or refreshing a the toggleframe of interest is possible?

Thanks in advance

**Comment by jarvisteach** [comment]
It's possible to add items to a container with either:
```python
with app.toggleFrame('tog1'):
    app.label('g')
```

Or:
```python
app.openToggleFrame('tog2')
app.label('h')
app.stopToggleFrame()
```

**Comment by jarvisteach** [comment]
Assuming resolved.
