### ISSUE TITLE
Anchor on Label not working

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#420]
```
    app.addLabel("blah", "Cool", row=startingRow+11, column=columnIdx+3, colspan=1)
    app.setLabelAnchor("blah", "e" )
```

I would expect text "Cool" to be justified right but it is centered

**Comment by jarvisteach** [comment]
I've never had any issues with this, and have just tested it, and it works fine on my Mac.

The issue with selectableLabels is a problem - labels use `anchor` but a selectableLabel is an entry, and they use `justify` - I've updated the functions to resolve selectableLabels

**Comment by jarvisteach** [comment]
Assuming this is resolved.
