### ISSUE TITLE
Anchor on SelectableLabel cause error

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#421]
this code (v0.92)

```
app.addSelectableLabel("blah", "Heat", row=startingRow+11, column=columnIdx, colspan=1)
app.setLabelAnchor("blah", "e" )
```

causes this unnexpected error
2018-03-19 11:04:01,474 appJar:WARNING [Line 1885->2989/configureWidget]: Error configuring blah: unknown option "-anchor"

**Comment by jarvisteach** [comment]
This is resolved in the next release
