### ISSUE TITLE
reading TickOptionBox not working from change event function

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#422]
from the example below I can access the content of a tickOptionBox from the main thread but not in a function that is called on event
```
def tickOptionBox_has_changed(widgetFullName):
    print("DEBUG: widgetFullName=" + str(widgetFullName))
    try:
        optionBoxContent=app.getOptionBox(widgetFullName)
        print("DEBUG:optionBox content=" + str(optionBoxContent))
    except:
        print("DEBUG: ??? expected dictionary with option name and associated status http://appjar.info/pythonWidgets/#optionbox")
    
app = gui()
# feedback objects
myTitle="test"
options=["val1", "val2", "val3"]
optionsTicked=[False, False, False]
ent=app.addTickOptionBox(myTitle, options, row=1, column=1, colspan=1 )
app.setOptionBoxSticky(myTitle, "both")
for idx in range(len(optionsTicked)):
    print("idx=" + str(idx))
    app.setOptionBox(myTitle, options[idx], value=False, callFunction=False, override=True)#optionsTicked[idx]
#ent.customFieldWhoAmI = guiObjName
app.setOptionBoxSubmitFunction(myTitle, tickOptionBox_has_changed)
optionBoxContent=app.getOptionBox(myTitle)
print("DEBUG:optionBox content from main=" + str(optionBoxContent))
```
Console output
```
idx=0
idx=1
idx=2
DEBUG:optionBox content from main={'val3': False, 'val2': False, 'val1': False}
DEBUG:optionBox content from submit event=
DEBUG: widgetFullName=val2
DEBUG: ??? expected dictionary with option nama and assotiated status http://appjar.info/pythonWidgets/#optionbox
```
what would be the workaround?

**Comment by jarvisteach** [comment]
Interesting - this works fine on a regular option box, but not on a tick option box.

It looks like the tick option box is returning the item you ticked, rather than the name of the option box.

A workaround would be to use `myTitle` instead of `widgetFullName` - to get the values.
If there are multiple option boxes, link each one to a different change function, so you know where the change originated.

**Comment by pg-doceapower** [comment]
Thanks. Unfortunately I don't know how many such fields there are as they
are user created and in my case the options are the same on each optionbox.
Only the user sets different ticked items on each instance

Le mar. 20 mars 2018 à 22:30, Richard Jarvis <notifications@github.com> a
écrit :

**Comment by jarvisteach** [comment]
I've made a change, so this now returns the name of the optionBox, rather than the option being ticked.
