### ISSUE TITLE
setGeometry documentation error

### ISSUE THREAD

**Issue by vinokumark** [jarvisteach/appJar#425]
Unknown function: <setGeometry> Check your spelling, do you need more camelCase?

**Comment by ChaosCreaterx** [comment]
I got exactly the same error, I hope we'll find a fix .. 

Unknown function: <setGeometry> Check your spelling, do you need more camelCase?

**Comment by vinokumark** [comment]
Hi,

     I tried the reference document in appjar for subwindows.

     Also tying like this.Please provide some idea


""from appJar import gui

def launch():
    app.startSubWindow("onet", modal=True)
    app.setBg("orange")
    app.setGeometry("400x400")
    #app.setTransparency(25)
    #app.setStopFunction(checkDone)
    app.addLabel("l1", "In sub window")
    app.stopSubWindow()


app=gui()

# these go in the main window
app.addButtons(["one"], launch)

# this is a pop-up
# app.startSubWindow("one", modal=True)
# app.addLabel("l1", "SubWindow One")
# app.stopSubWindow()

# this is another pop-up

app.go()""

**Comment by jarvisteach** [comment]
Sorry about this, it's not a bug in the code, but a bug in the documentation.

`.setGeometry()` has been replaced by two functions:
`.setLocation()` and `.setSize()`

This must have got missed when the docs were updated.

These new functions also exist in the new [parameters](http://appjar.info/simpleProperties/) section as well.

So, you can call:
```python
app.setSize("200x200")
app.size = (200,200)
app.size = "200x200"
```

**Comment by jarvisteach** [comment]
I found this reference in the following docs:

```sh
./pythonContextManager.md:68:    app.setGeometry(250, 300)
./pythonGuiOptions.md:30:* `.setGeometry(geom)` & `.setGeometry(width, height)`  
./pythonGuiOptions.md:32:    * Either as a single String `.setGeometry("200x100")` (widthxheight)  
./pythonGuiOptions.md:33:    * As two separate parameters `.setGeometry(200,100)`
./pythonGuiOptions.md:34:    * Or to go *Fullscreen* `.setGeometry("Fullscreen")`  
./pythonGuiOptions.md:46:    app.setGeometry("fullscreen")
./pythonSubWindows.md:106:app.setGeometry("400x400")
./pythonWidgetGrouping.md:467:app.setGeometry(280,400)
```

**Comment by vinokumark** [comment]
How to initiate new window, like window one for login, window two for main
window.

**Comment by jarvisteach** [comment]
So, you need to create the `subWindow` then show it.

```python
app.startSubWindow("PopUp")
app.addLabel("SubWindow")
app.stopSubWindow()

app.showSubWindow("PopUp")
```

I recommend creating the `subWindow` before calling `.go()`, and then having a function to `show` it.

In the code above, you;re missing the call to `show` it.

**Comment by vinokumark** [comment]
Need some example. when click Addbutton function  create multiple textentry box.

**Comment by jarvisteach** [comment]
Try this:
```python
from appJar import gui 

count = 0 
def press():
    global count
    app.entry("NEW" + str(count))
    count += 1

with gui() as app:
    app.label('hello world')
    app.button("ADD ENTRY", press)
```
