### ISSUE TITLE
how to set column width

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#431]
Hello, I'm making quite good progress on my little GUI thanks to appJar and I'm no developer. 
I still have a few GUI glitches one of them is I don't know how to control column or line width. For instance:

1/ I have a large text area below which I'd like to add 2 options (a checkbox and a entry field) I wanted to pack these tightly to the bottom right of the text rea as they control the vertical scrolling of it. but appJar spans them on the entire line.
2/ the layout has tabs with each tab has many entry fields and below the tab I want a big run button that does not belong to the bas it is just on the first line below the tabs. since there are 2 line in the canvas to display, appJar sets the tabbedFrame height to be the same as the "run" button which looks odd since the tab frame has lot more widgets to display. Any recommendation?

**Comment by jarvisteach** [comment]
There are two parameters to play with here: `sticky` & `stretch` (http://appjar.info/pythonWidgetLayout/#widget-positioning)

In simple terms: 
* `stretch` configures how rows should expand to fill the available GUI space
* `sticky` configures how widgets stretch & position in their cell

Both cases above require these to be configured:
* In the first, you only want the editor to `stretch` to fill `both` while the other widgets should `stretch` to only fill their `column`. It will also want the widgets after the editor to only `sticky` to the `e` side.
* In the second, the tabs should `stretch` to fill `both`, the button stretch to fill `none`

Eg.
```python
from appJar import gui 

with gui("EDITOR", "400x400", bg="red", fg="white", stretch="column") as app:
    app.label('Text Editor')
    app.stretch = "both"
    app.text("editor")
    app.stretch = "column"
    app.sticky = "e" 
    app.check("ed1")
    app.entry("ed1")
```

**Comment by jarvisteach** [comment]
Closing, as assume resolved?
