### ISSUE TITLE
.setBg(color) doesn't work after one change

### ISSUE THREAD

**Issue by DRD7Bloo** [jarvisteach/appJar#434]
I created a neat little program that translates a secret code I made and added a few features for my coding practice in Python. I did all of these with AppJar because I needed a GUI. I used many features of the library. One of which is the .setBg(color) function that I would operate through a small command parser from the Entry object. The problem I'm having seems to have no correlation to how I coded the  function, since I've tried placing it in every possible space in my code.

After changing the GUI colors once:
![image](https://user-images.githubusercontent.com/37978227/38679558-5b6ae450-3e64-11e8-937e-13bacdf3391f.png)

After changing the GUI colors twice:
![image](https://user-images.githubusercontent.com/37978227/38679615-7764eb1a-3e64-11e8-8016-2451fa6070ec.png)

I don't feel like sharing the entirety of my code, so if you could check by yourself and see if its the library's fault or mine that would be lovely.

Thanks in advance!

**Comment by jarvisteach** [comment]
I'm a bit unsure what the problem is here?
In the first image the BG is black, in the second the image is silver.
What is the expected behaviour?

**Comment by DRD7Bloo** [comment]
The expected behaviour is for the entire GUI to change colors. The GUI is divided into two parts, a scroll pane that is on top and the main GUI frame that holds the Entry. Both of the labels inside the scroll pane, the scroll pane itself and the main GUI frame are expected to change colors.

Everything else works but the .setBg(color) which should set the color of the main GUI frame and all its widgets (except entries etc.).

**Comment by jarvisteach** [comment]
So, `app.setBg()` should update the whole GUI, although it won;t update input widgets.
To update the textArea, you'd call `app.setTextAreaBg()`

I've knocked up a quick bit of code to test:

```python
from appJar import gui 

def process():
    c = app.entry("command")
    if c.lower().strip().startswith("bg"):
        col = c.split("=")[1].strip()
        app.bg = col 
        app.text("text", bg=col, state='normal')
        app.setTextArea('text', "BG set to: " + col + "\n")
        app.text("text", state='disabled')

with gui("Translator", "600x400", bg="black") as app:
    app.text("text", border=1, relief='sunken', state='disabled')
    app.entry("command", submit=process, focus=True)
```
If you run it, and type `bg=red` it updates the bg and the textArea.

If you remove the line that updates the textArea, the app's BG still changes.

**Comment by jarvisteach** [comment]
Interestingly, I had issues updating the textArea while it was disabled, I think it should be possible to update the textArea even when disabled...

**Comment by jarvisteach** [comment]
I've updated appJar to allow textAreas to be set even when `disabled`.

This reduces the above code to:

```python
from appJar import gui 

def process():
    c = app.entry("command")
    if c.lower().strip().startswith("bg"):
        col = c.split("=")[1].strip()
        app.bg = col 
        app.text('text', "BG set to: " + col + "\n", bg=col)

with gui("Translator", "600x400", bg="black") as app:
    app.text("text", border=1, relief='sunken', state='disabled')
    app.entry("command", submit=process, focus=True)
```

**Comment by DRD7Bloo** [comment]
I tried through app.bg, but I'm out of luck. Could it be from the additional widgets I have in my GUI? I've decided to scrap the idea of changing the main GUI frame since it doesn't work. 

Thanks for the help though.

**Comment by jarvisteach** [comment]
What widget are using to display the notifications? Is it a textArea or label?
You mention it's in a scrollPane - are you calling app.setBg() while inside the scrollPane?
In which case, it would only change the scrollPane...

**Comment by DRD7Bloo** [comment]
It's using labels within the scroll pane and I was calling app.setBg() outside of app.openScrollPane(name) and also within it.

**Comment by jarvisteach** [comment]
There is a tiny border around the edge of the app - that stays black the whole time. So you must not be getting the topLevel setBg(), but just the scrollPane's setBg(). Have you called app.closeScrollPane()?

**Comment by DRD7Bloo** [comment]
Version 0.92.0

**Comment by jarvisteach** [comment]
Ha, sorry my bad - it should have been `stopScrollPane()`

**Comment by DRD7Bloo** [comment]
Also, since I don't see any other way of contacting you on the website, is there a function that reads out the Background RGB values? I need it to change the Foreground according to the "brightness" of the background color and I'm struggling to see any other way to do it.
