### ISSUE TITLE
Center and stretch Message to the border of the window

### ISSUE THREAD

**Issue by stephanepiriou** [jarvisteach/appJar#435]
I can't figure out how to stretch the message widget on the whole width of the window

```python
app = gui("Login Form")

app.addMessage("Message","Veuillez entrer les parametres de votre système d\'équation.", 0, 0, colspan=2)

app.addLabel("nbrEquations", "Nombre d'équations:", 1, 0)
app.addNumericEntry("userEnt", 1, 1)

app.addLabel("nbrUnknowns", "Nombre d\'inconnues:", 2, 0)
app.addNumericEntry("passEnt", 2, 1)

app.addButtons(["Create", "Cancel"], None, colspan=3)
```
![selection screen shot53](https://user-images.githubusercontent.com/20599429/38693826-62da306e-3e88-11e8-9c05-82da0cec033b.jpg)

**Comment by mpmc** [comment]
Use a label instead :)

```python
from appJar import *

app = gui("Login Form")

app.addLabel("Message","Veuillez entrer les parametres de votre système d\'équation.", 0, 0, colspan=2)

app.addLabel("nbrEquations", "Nombre d'équations:", 1, 0)
app.addNumericEntry("userEnt", 1, 1)

app.addLabel("nbrUnknowns", "Nombre d\'inconnues:", 2, 0)
app.addNumericEntry("passEnt", 2, 1)

app.addButtons(["Create", "Cancel"], None, colspan=3)

app.go()
```

**Comment by jarvisteach** [comment]
Actually, quite an interesting one...

Long answer short, as @mpmc says, just use a label!

But, after a bit more research - the message has been stretched, add this line to check:
```app.setMessageBg("Message", "blue")```

According to [this](http://effbot.org/tkinterbook/message.htm), message widgets are just labels with one extra feature, they split the text over multiple lines.

If you want to control how the text is split, you can either give it a new width value: ```app.setMessageWidth("Message", 200)```

Or you can change its aspect ratio:
```
mess = app.addMessage("Message","Veuillez entrer les parametres de votre système d\'équation.", 0, 0, colspan=2)
mess.config(aspect=500)
```

I will add a new function for setting the aspect on messages, and update the documentation to better explain it.

**Comment by jarvisteach** [comment]
Yes, appJar is just a wrapper around tkinter, grouping together multiple calls, to try to make life a bit easier. A lot of tkinter hasn't been implemented, and probably never will. You can always get at the tkinter widgets and work with them directly...

Have a look here if you need more information: http://appJar.info

For your question about anchor/justify/align, have a look here: http://appjar.info/pythonWidgetOptions/#advanced-looks

The command you need is:  `app.setMessageAlign("Message", "right")`

eg.
```python
def align(btn): app.setMessageAlign("Message", btn.lower())
app.addButtons(["Left", "Right", "Center"], align, colspan=3)
```
