### ISSUE TITLE
app.setGeometry method not working

### ISSUE THREAD

**Issue by NikhilDesaiCs** [jarvisteach/appJar#438]
.setGeometry method is not working
It throws the error
Unknown function: <setGeometry> Check your spelling, do you need more camelCase?

 It doesn't even resize subwindow and shows the same error.
Thanks

**Comment by jarvisteach** [comment]
This was raised in issue #425 - the function was changed in a recent release, but the docs have not been fixed yet.

It should be `setSize()`
