### ISSUE TITLE
Update documentation. 

### ISSUE THREAD

**Issue by ChaosCreaterx** [jarvisteach/appJar#441]
Please update the documentation, in comparison with others documentations it is far more better, so it would be perfect it you kept it healthy. 
For example setGeometry is replaced with app.size and is not mentioned. 

Furthermore because I am not sure where to find this thing, I would like to ask how can I add three labels in one row for example label1 in row 0, label2 in row 0, label 3 in row 0. I can't add all the data in a single label because they are different types of data and some are non type so I can not turn them into something else.

Thank you in advance, please answer quickly it  is for a school project.

**Comment by othoma** [comment]
@ChaosCreaterx I think you might find what you're looking for in the docs. 

[This link should help you](http://appjar.info/pythonWidgetLayout/#grid-layout)

Regards

**Comment by jarvisteach** [comment]
Closing as assume resolved.
