### ISSUE TITLE
[Question] Minimize to system tray

### ISSUE THREAD

**Issue by frakman1** [jarvisteach/appJar#444]
I know this is a Windows-specific functionality, but there is a need to minimize an app to the system tray (bottom right hand corner icons).

Is it possible to add such functionality to appJar?

**Comment by jarvisteach** [comment]
I assume it's possible, but my Windows machine is not great for developing on, and I'd have no idea where to start...

I had a quick search, and found these:
* http://www.brunningonline.net/simon/blog/archives/001835.html
* https://sourceforge.net/projects/pysystray/

They may be enough to get started?

**Comment by frakman1** [comment]
Yes, I looked into pysystray and there is a SysTrayPython.py example that I've used successfully in the past. I was wondering how appJar could use it. The above programs make a separate entity for the system tray with all sorts of functionality. I was just thinking of minimizing the app to the tray so it doesn't take up task bar real-estate.

**Comment by jarvisteach** [comment]
You could look into running the SysTrayIcon.py with a single option - which launches your GUI. Then override the minimise function of the GUI to close it...

Or, when launching the GUI, also have it launch SysTrayIcon.py, and find a way to not show the GUI in the task-bar, then link SysTrayIcon to "deiconify" the gui...

**Comment by jarvisteach** [comment]
Managed to have a quick play with this. SysTrayIcon.py has no problem launching an appJar gui - doesn't seem to cause the main program to hang... So it seems feasible.

Didn't get as far as trying to hide the GUI - but killing it and starting it again each time, was fairly responsive...

**Comment by jarvisteach** [comment]
@frakman1 I've just committed the example code

**Comment by jarvisteach** [comment]
Closing as no plans to follow on...
