### ISSUE TITLE
[Question] Button Width/Spanning

### ISSUE THREAD

**Issue by kamilm** [jarvisteach/appJar#448]
How can I force a button to span the width of a window / container? I'd like all my buttons to have a certain width irrespective of the label. 

Thanks!

**Comment by kamilm** [comment]
Would that be accomplished via colspan in .addButton() or somewhere else? I’ve been looking for an example to help me understand. I’ll keep looking.

**Comment by jarvisteach** [comment]
Have a look here for some info:

http://appjar.info/pythonWidgetLayout/#widget-positioning

**Comment by kamilm** [comment]
Thanks, I got it to work.
