### ISSUE TITLE
getOptionBox separator refinement

### ISSUE THREAD

**Issue by natfast** [jarvisteach/appJar#450]
Hi Again!

Was working with the option box and I had items that started with numbers, including -1. This caused a problem in that the option box code checks for a leading "-". 

Could this be extended to leading and trailing "-", so that negative numbers could be supported?
- Separator item -

Or... pass in an optional Separator Value?!

``` if box.kind == "ticks":
            val = self.widgetManager.get(self.Widgets.TickOptionBox, title, group=WidgetManager.VARS)
            retVal = {}
            for k, v in val.items():
                retVal[k] = bool(v.get())
            return retVal
        else:
            val = self.widgetManager.get(self.Widgets.OptionBox, title, group=WidgetManager.VARS)
            val = val.get().strip()
            # set to None if it's a divider
            if val.startswith("-") or len(val) == 0:
                val = None
            return val
```

**Comment by jarvisteach** [comment]
Yes, good point! I think having a `-` at each end sounds like the simplest fix. This will, however, affect people's existing code, so may need to be done with an option to configure (a boolean flag perhaps)...

**Comment by jarvisteach** [comment]
Actually, to keep it simpler, I will just include a parameter where the user sets the character, and default it to the dash.
