### ISSUE TITLE
Issue with AjRectangle in v0.93

### ISSUE THREAD

**Issue by kamilm** [jarvisteach/appJar#455]
I can't load this latest version, v0.93, because I cannot import AjRectangle. This is strange, as I have no problem with v0.92. Is anyone else experiencing this?

libs\appJar\__init__.py", line 5, in <module>
    from appJar.appjar import AjRectangle, AjPoint
ImportError: cannot import name 'AjRectangle'

**Comment by kamilm** [comment]
Sorry, maybe I wasn't clear. I can't load v0.93 because AjRectangle is holding it back. It's being loaded in AppJar/__init__.py and the software gets held up at that import.

**Comment by kamilm** [comment]
@jarvisteach 
I am using Win10 with Python installed via the Anaconda Distribution. 

I've sort of narrowed down my problem to my project structure:
./libs
./libs/__init__.py
./libs/appJar/
./libs/appJar/__init__.py
./libs/appJar/appjar.py
./libs/appJar/... all others
./main.py

I launch main.py

in main.py i have:
from libs.appJar import gui
with app as gui():
    app.addLabel('Show Me')

this doesn't work. 

When I shift my project so that it all lives inside of ./libs/ it works. 

What makes all this a bit puzzling is that it worked just fine in the previous version, 0.92.

**Comment by jarvisteach** [comment]
Not sure what the issue was - closing.
