### ISSUE TITLE
TreeView doesn't support XML objects

### ISSUE THREAD

**Issue by durgesh23** [jarvisteach/appJar#457]
I have an XML file. I have parsed the file via ElementTree and trying to get a view of my XML file.
But i am getting an error as:

 parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'ElementTree'

`xml=et.Element(root)
#Here i add more subElement to the root....
	
xmltree= et.ElementTree(xml)
app.startFrame('bottomleft',1,0,2)
app.setBg('orange')
app.setSticky('news')
app.setStretch('none')
app.addTree('REGISTER', xmltree)`

**Comment by jarvisteach** [comment]
I'm not entirely sure what's going on here... but, I think it's just the case that you should pass the text of your XML file, rather than the parsed version. appJar will parse the text for you.

**Comment by durgesh23** [comment]
Ok thanks for the help.

But what if the text that we want to represent in tree structure is present
in file. We have parsed the file and want to represent some of the parsed
data in a tree structure.. not here whole file.
Is there a option for that!?

Regards,
Durgesh.

**Comment by durgesh23** [comment]
Thanks for the help.

**Comment by jarvisteach** [comment]
I've now removed the `.addTreeObject()` function, `.addTree()` should now handle both data types.
Docs & testing are updated.
I will close this issue, as issue #403 already raised to allow trees to be updated.
