### ISSUE TITLE
Issue with modal sub-window and errorBox

### ISSUE THREAD

**Issue by chrisw-thomas** [jarvisteach/appJar#461]
Just learning appJar so this could be an "issue" with me.

I have a simple application with a "main" window which defines a sub-window to request a username and password. The sub-window is modal and runs "on top".

If the user submits an invalid username/password combination the sub-window launches an errorBox.

If I launch the errorBox without defining the parent or use parent=None then the errorBox is hidden by the modal/on-top sub window... but when I use select the "OK" button on the errorBox it closes cleanly and control passes back to the sub-window.

If I specify the parent using parent="Authenticate" then the errorBox opens on top of the sub-window - i.e. the behaviour I want. But when I select the "OK" button on the errorBox I get an error:

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python27-32\lib\lib-tk\Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 3574, in <lambda>
    return lambda *args: funcName(param)
  File "C:\Users\ChrisThomas\Documents\Python\GUI\testing.py", line 26, in authenticate_press
    win.errorBox( 'Error', 'Invalid userid or password', parent='Authenticate')
  File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 10824, in errorBox
    self._bringToFront(parent)
  File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 2326, in _bringToFront
    top = win.attributes('-topmost')
AttributeError: 'str' object has no attribute 'attributes'`

How is the name of the parent sub-window supposed to be passed to the errorBox? I have used the name of the sub-window when it's created. The error message implies that it's expecting a more complex structure as opposed to the name of the sub-window.

**Comment by jarvisteach** [comment]
This is now resolved in the next release.
