### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by GoldenEagle66** [jarvisteach/appJar#464]
tell me what widget can do my job
I need to load the sqlite table into a table and work with the information from the table it is desirable that it would be possible to select several elements and a drop-down menu

**Comment by GoldenEagle66** [comment]
Is it possible to add several columns to the listbox, and not just one?

**Comment by othoma** [comment]
I would you .getentry instead of a dropdown. That would filter trough the column of the Table. 

One getentry by column you wanna filter through.

**Comment by GoldenEagle66** [comment]
@jarvisteach Can I add a checkbox to the table?

**Comment by jarvisteach** [comment]
Not currently - but I'll raise it as a new feature request.
