### ISSUE TITLE
Can't disable Scale Widget in TTK-Mode

### ISSUE THREAD

**Issue by adtzlr** [jarvisteach/appJar#465]
Hello,

I found out that appJar does not disable a Scale Widget in TTK-mode.
Minimal (not :blush: ) working example:

```python
from appJar import gui
app = gui(useTtk=True)

app.addLabelScale("scale")
app.setScaleRange("scale",0,10,1)

app.disableScale("scale")

app.go()
```
whereas in normal (non-TTK) mode everything is fine. Thank you @jarvisteach !

**Comment by jarvisteach** [comment]
Hi @adtzlr - yup there are lots of little things like this where the standard functions don't work on ttk widgets.

Luckily, you can just call the ttk functions directly on the widgets once you've added them:
```python
# adding widgets always returns the widget
sc = app.addLabelScale("scale")
app.setScaleRange("scale",0,10,1)
sc.state(["disabled"])
```

**Comment by jarvisteach** [comment]
Should now be resolved.
