### ISSUE TITLE
Menus - Remove menu item?

### ISSUE THREAD

**Issue by chrisw-thomas** [jarvisteach/appJar#467]
Is there a way to remove a menu item or a SubMenu after it's been created?

I spotted that there's a .remove XXX (name) function but it didn't work when I set XXX to SubMenu or MenuCheckBox for example.

I suspect it's not "good practice" to be manipulating menu structures live in a GUI but for my particular application it works quite nicely to have some menu trees configure themselves depending on what the user is working on.

If not I'll need to build something in a sub-window using widgets that I can manipulate.

**Comment by jarvisteach** [comment]
This hasn't been implemented (yet).

For now, you can access the underlying tkinter call, and delete the item directly:

```python
from appJar import gui 

MENU_NAME = "Checkers"
SUB_MENU = "SubMenu"
ITEMS = ['a', 'b', 'c', 'd']

def checker(men):
    for i in ITEMS: print(i, app.getMenuCheckBox(MENU_NAME, i)) 
    for i in ITEMS: print(i, app.getMenuCheckBox(SUB_MENU, i)) 
    # delete menu items
    app.widgetManager.get(app.Widgets.Menu, MENU_NAME).delete("d")
    app.widgetManager.get(app.Widgets.Menu, SUB_MENU).delete("b")
    app.widgetManager.get(app.Widgets.Menu, MENU_NAME).delete(SUB_MENU)

with gui() as app:
    app.label('Menus')
    for i in ITEMS: app.addMenuCheckBox(MENU_NAME, i, checker)
    app.addSubMenu(MENU_NAME, SUB_MENU)
    for i in ITEMS: app.addMenuCheckBox(SUB_MENU, i, checker)
```

**Comment by jarvisteach** [comment]
*NB.* you won't be able to put the menus back, unless you also remove them from the widget store:

```
app.widgetManager.remove(app.Widgets.Menu, SUB_MENU+"cb"+"b", group='vars')
app.widgetManager.remove(app.Widgets.Menu, SUB_MENU)
```

**Comment by jarvisteach** [comment]
New feature - ability to delete menus.

**Comment by jarvisteach** [comment]
Closing this, now referenced in menu refactor.
