### ISSUE TITLE
setProperty to an Entry

### ISSUE THREAD

**Issue by knowledge1st** [jarvisteach/appJar#468]
Hello everyone, first post in GitHub...

I'm using appJar to create a gui to my py bot.

I'm trying to create readonly Entrys so... i've tried this:

`app.addEntry("ANI")`
`app.setProperty("ANI",prop=readonly ,value=True)`

but it's not working... 

I need some help with this.

Thank you in advance

**Comment by jarvisteach** [comment]
Welcome @knowledge1st to GitHub!

Have a look here for the options on widgets: http://appjar.info/pythonWidgetOptions/

The code you're looking for is:
```python
app.setEntryState('ANI', 'disabled')
```

**Comment by knowledge1st** [comment]
Thank you so much! I’m gonna try this tomorrow. I recall that i can’t use this func cause my entry haven’t a name. Is that possible?
