### ISSUE TITLE
Problem with buttons

### ISSUE THREAD

**Issue by knowledge1st** [jarvisteach/appJar#469]
Here i go again:

I'm in troubles with button. They actually seem like they are clicking them selves.

I have this:

```import selen
app = appJar.gui()
app.setOnTop(stay=True)
app.setMinSize(size='100x100')
app.setTitle("The Bandex Killer")
app.setResizable(canResize=False)
app.setGuiPadding(1, 1)
app.setLocation("CENTER")
app.setSize(200,200)
app.hideTitleBar()
app.startTabbedFrame("TabbedFrame")
#app.setSticky("ew")
app.startTab("Inicio")
app.bindKey("<F5>", keyPress)
app.bindKey("<F8>", keyPress)
app.addButton("False", Change)
app.addLabel("state3","En este momento: Inactivo")
app.addButton("Start", selen.Starting())
app.label("state3",fg="red")
app.setButton("False", PLAY)
app.stopTab()
```

And the GUI doesn't appear in my screen, it just open a chrome window, but no gui(this is intended, is the code that "selen.Starting() should do when clicked.) 

Any ideas why this is happening?

**Comment by jarvisteach** [comment]
The line:
```python
app.addButton("Start", selen.Starting())
```
Is assigning the result of the function call to the button.
Instead, you need to assign the actual function (by not including the brackets):
```python
app.addButton("Start", selen.Starting)
```

You also need to call:
```python
app.go()
```
At the end...

**Comment by zagaroth777** [comment]
Spent at least an hour troubleshooting this issue just to find this post and fix the issue in 10 seconds. Thank you Jarvisteach!
