### ISSUE TITLE
tabbedFrame tab order

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#473]
Is it possible to alter the order in which a tab is displayed in tabbedFrame? I am wanting allow a user to add new tabs from a button placed on a generic tab. Once the add the new tab I would like it to come before the generic tab.

**Comment by jarvisteach** [comment]
OK - I found a useful feature in the pack geometry manager - you can specify a widget to pack before/after: https://www.tcl.tk/man/tcl/TkCmd/pack.htm#M7

So, i'll add an option to be able to specify the name of the tab to add a tab before/after

**Comment by Binxlola** [comment]
Awesome thank you. I did think about deleting and adding the tab as well. However I wasn't sure how to get the tab as when I used app.widgetsmanager.get(app.Widgets.Tab, name) It wouldn't work haha.

**Comment by jarvisteach** [comment]
OK, I've pushed out some new code, you can now set a `beforeTab` or `afterTab` parameter when starting a new tab:
```python
with app.tabbedFrame("tabs"):
    with app.tab("new tab", beforeTab="generic"):
        app.label("new tab")
```

**Comment by Binxlola** [comment]
Will that come out with the next update?

**Comment by jarvisteach** [comment]
It'll definitely be in the next version. It's also available now in the `next_release` branch if you want to give it a try...
