### ISSUE TITLE
Asynchronous tasks interacting with widgets

### ISSUE THREAD

**Issue by chrisw-thomas** [jarvisteach/appJar#474]
Is there a safe way to run a long-running task from a menu item or button and have it interact safely with widgets?
I updated my application to run the long-running task as a separate thread using the Python Thread module and it now runs asynchronous to the main application but when it tries to interact with widgets I get apparently random errors:

  ```
File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 8538, in addLabel
    self._positionWidget(lab, row, column, colspan, rowspan)
  File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 3841, in _positionWidget
    gui.SET_WIDGET_BG(widget, self._getContainerBg())
  File "C:\Python27-32\lib\site-packages\appJar\appjar.py", line 3790, in SET_WIDGET_BG
    widget.config(bg=bg)
  File "C:\Python27-32\lib\lib-tk\Tkinter.py", line 1330, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Python27-32\lib\lib-tk\Tkinter.py", line 1321, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
TclError: unknown color name "expected boolean value but got "??""
```
The errors change each time I run it but are always in the same vicinity - either adding a label or changing the attributes of the label - e.g. foreground colour.

If I run the long-running task as a thread and remove the interaction with the widgets in the main application then I get no errors - so it looks like it's definitely the interaction with the GUI elements that's causing the problem.

Any recommendations welcome - Python 2 rather than Python 3 if possible.

**Comment by jarvisteach** [comment]
Have a read through this page:

http://appjar.info/pythonThreads/

**Comment by chrisw-thomas** [comment]
Doh - slaps forehead. Sorry. Why couldn't I find that yesterday?!?

Thanks.

**Comment by chrisw-thomas** [comment]
I've incorporated the threading in as per the link you pointed me at and it works fine but for one problem...
I need to add an item to a ScrollPane and so I need to open the ScrollPane, add the item and then close the ScrollPane... so it's not a simple atomic operation on the GUI and other items are appearing in the GUI queue and popping into my ScrollPane.
The reason I'm using a ScrollPane is that I'm trying to present logging information to the user so want to be able to keep appending text entries to something with a scroll bar. I did briefly experiment with a scrollable TextArea but I couldn't get the layout of that to work neatly - it needs to fill the area presented by a tab in a Tabbed Frame and the TextArea wanted to squish the text together and occupy as little space as possible... or am I just not configuring that correctly?

**Comment by jarvisteach** [comment]
Interesting dilemma...

I've had a play with creating a tab that logs errors, and didn't have the issues you mentioned with layout:

```python
import time
from appJar import gui

def press():
    app.text("log", app.entry("Text:")+"\n")
    
def logText():
    while True:
        app.queueFunction(app.text, "log", "new data\n")
        time.sleep(1)
        
with gui() as app:
    with app.tabbedFrame("tabs"):
        with app.tab("Log"):
            app.text("log", scroll=True)
        with app.tab("Data"):
            app.entry("Text:", label=True, submit=press)
            app.button("Submit", press)
            
    app.thread(logText)
```

**Comment by jarvisteach** [comment]
However, there should also be a way to achieve what you're trying to do with the ScrollPane. Opening/Closing the pane shouldn't need to be done via the queue, as they shouldn't be making any changes to the GUI. I'll have to have a ply with that...

**Comment by jarvisteach** [comment]
Going to close this, and raise a new issue for interacting with a container from the queue.
