### ISSUE TITLE
Possible bug with DbTable actionButton

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#475]
Running the code below for create a tab, filled with a specified table by a user. The action button does not fill up its column.

    try:
        with app.tabbedFrame("Item Inventory"):
            with app.tab(table, beforeTab="View table"):
                app.addDbTable(table, "test.db", table, actionHeading="Checkout", actionButton="Item", action=toolbar)
    except LookupError:
        pass

<img width="989" alt="screen shot 2018-06-30 at 10 39 21 pm" src="https://user-images.githubusercontent.com/38807670/42124432-86118b60-7cb6-11e8-9151-43fda77a7830.png">

**Comment by jarvisteach** [comment]
What platform are you on?

**Comment by Binxlola** [comment]
Currently on Mac OS X

**Comment by jarvisteach** [comment]
Hi @Binxlola - this is definitely a bug. A new feature was added where multiple action buttons could be included, which changed the layout from pack to grid. I've made sure buttons stretch to fill the column now.

**Comment by jarvisteach** [comment]
Also, the edits have no affect on the underlying data yet, you'll have to d that yourself for now...

**Comment by jarvisteach** [comment]
OK, been doing a bunch of work on this.

There is already an issue, #396, to document an example DB app, so I'm going to close this issue, and continue to work on that issue.

The file `issue396_db.py` in `examples\issues` contains the code I have so far, along with `issue396.sqlite`
