### ISSUE TITLE
can't input Chinese chars in input widgets

### ISSUE THREAD

**Issue by liupsdp** [jarvisteach/appJar#476]
Hi, guys I can display Chinese chars using setEntry in code, but can't input Chinese when the app is running, I change input method to Chinese but it seems keystrokes goes directly to the widget, please help thanks!
Mac high sierra, python 3.6.3

**Comment by jarvisteach** [comment]
This is most likely an issue with your python and/or tcl/tk versions.

According to this: https://stackoverflow.com/questions/28747976/is-it-possible-to-input-chinese-text-into-tk-text-and-entry-widgets-with-tkinter

You need to upgrade tcl/tk

If you run an appJar app with the `-v` flag, it'll show you your tcl/tk version

**Comment by liupsdp** [comment]
upgraded tcl/tk, problem solved, thank you very much!
