### ISSUE TITLE
Move widgets from one grid cell to another

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#477]
Is it possible to pack up a frame and it's contents and unpack them elsewhere? I have accomplished this my destroying a frame and it's contents and re-added with slightly different names.

**Comment by jarvisteach** [comment]
So - you want to have a frame of widgets, and move it from one part of the GUI to another?

**Comment by Binxlola** [comment]
Yes pretty much. Below is an example of a major frame and 3 minor frames. What I would like to do is move frames and its contents between the minor frames. So for example when I click in progress button it will pack up that frame that the button is in and move it to the minor frame that is in progress.
(Hopefully that explanation is clear? P.S name are all wonky as this is my test code.)
        with app.frame("to-do"):
            with app.labelFrame("To do", 0, 0):
                app.setSticky("nsew")
                app.setStretch("column")
                with app.frame("test_frame", sticky="w", colspan=2):
                    app.addLabel("test_frame", "This is the frame for to-do", 0, 0)
                    app.setSticky("e")
                    app.addIconButton("In progress", drag, "in_progress_btn", 0, 1)

            with app.labelFrame("In progress", 0, 1):
                app.setSticky("nsew")
                app.setStretch("column")
                with app.frame("test_frame_2", sticky="w", colspan=2):
                    app.addLabel("In progress", "this is a test for the in progress tab.", 0, 0)
                    app.setSticky("e")
                    app.addIconButton("done", drag, "done_btn", 0, 1)

            with app.labelFrame("Done", 0, 2):
                app.setSticky("nsew")
                app.setStretch("column")
                with app.frame("test_frame_3", sticky="w", colspan=2):
                    app.addLabel("Done", "Done test", 0, 0)
                    app.setSticky("e")
                    app.addIconButton("remove", drag, "remove_btn", 0, 1)

**Comment by jarvisteach** [comment]
I think what you're after is directly supported in appJar, but is easy enough to achieve using tkinter functions.

All the widgets are in a grid. So you can call `.grid_forget()` on a widget to remove it. And then call `.grid(row, column)` to put it back somewhere else...

**Comment by Binxlola** [comment]
Yes I did use grid_forget() and grid at one stage. The only issue I had, was not that it didn't work but rather that I had to grid it in. Now if you can image a 3 column to-do list with frames moving back and forth... it's a lot of positions to keep track of. Thank you anyway, I may end up going back to that grid method.

**Comment by jarvisteach** [comment]
@Binxlola - I think if each column were it's own separate frame, configured so that its rows collapse when empty. You could create a fairly nice looking interface where clicking an item removes it from one column and adds it to the bottom of the next...

**Comment by jarvisteach** [comment]
I'd like to leave this open for now, as I want to make this a new feature, and document how to do it....
