### ISSUE TITLE
request: multiple file selection in openBox()

### ISSUE THREAD

**Issue by kamilm** [jarvisteach/appJar#479]
I would like to be able to select multiple files using openBox(). 

I was able to accomplish this for the time being by hacking openBox(). 

`
     def openBox(self, title=None, dirName=None, fileTypes=None, asFile=False, parent=None, multiple=False):
...
        if multiple:
            return filedialog.askopenfilenames(**options)

`

I'm not sure if this breaks the asFile option, or if this is the best way, but it's a start.

**Comment by jarvisteach** [comment]
@kamilm - I didn't even know that was an option, but looks like a nice solution...

It looks like this may work differently on windows & linux, with one returning a string and the other a list - so you might want to think about that.

Feel free to issue a PR :)
