### ISSUE TITLE
can't use .setFocus on TextAreas widget

### ISSUE THREAD

**Issue by marcellmueller** [jarvisteach/appJar#480]
This is probably a feature and not a bug but it would be very useful.

**Comment by jarvisteach** [comment]
Hi @marcellmueller, there should be a function:
```
app.setTextAreaFocus("ta")
```
To give focus to a TextArea.

If it's not built into appJar, you can always do it directly to the widget:

```python
app.addTextArea("ta").focus_set()
```
Adding a widget should always return it, so you can keep a reference to it and manipulate it later.

Using the new functions, you can also pass it as a parameter:
```python
app.text("ta", focus=True)
```

**Comment by marcellmueller** [comment]
You're right, I don't think .setTextAreaFocus was in the docs. Really appreciate your help and hard work on appJar.
