### ISSUE TITLE
Issue(s) with table rendering after .deleteTableRow

### ISSUE THREAD

**Issue by bitassassin** [jarvisteach/appJar#482]
Okay, bear with me as this may be two bugs:

In .addTable, I have set the following function:
`def fDeleteRow(dRow):
	app.deleteTableRow("entryTable", dRow)`

The .addTable looks like this:
`app.addTable("entryTable", [["Item", "Description"]], action=fDeleteRow, addRow=fAddRow, actionHeading="Delete", addButton="Add Item", actionButton="X", showMenu=True)`

The window looks as follows:
![pre-anything](https://user-images.githubusercontent.com/5567620/42734273-b892b43a-8830-11e8-98da-fe47f571aadd.PNG)

You'll notice the Add Item button doesn't render. It does that once you hover over it:
![mousehover_over_button](https://user-images.githubusercontent.com/5567620/42734280-e72ddc7a-8830-11e8-954a-152cda1fae2b.PNG)

So, the next step is to insert test entries:
![test_entries](https://user-images.githubusercontent.com/5567620/42734297-0fb20694-8831-11e8-9b61-92ab2dba0441.PNG)

And to click the 'X':
![clicked_delete_row_2](https://user-images.githubusercontent.com/5567620/42734303-1d62bd9c-8831-11e8-9b80-c34fd3b684fe.PNG)

Which generates the following error:
![clicked_delete_row_2_dbg](https://user-images.githubusercontent.com/5567620/42734341-ad856604-8831-11e8-8fce-0a9a61a16cb1.PNG)

The bonus round is deleting all entries and trying to remove that last pesky null row:
![bonus_upon_final_item_deletion](https://user-images.githubusercontent.com/5567620/42734318-3e4b168a-8831-11e8-80b7-642552f20500.PNG)

Which generates the following:
![bonus_upon_final_item_deletion_dbg](https://user-images.githubusercontent.com/5567620/42734345-babd6c22-8831-11e8-8c79-7f876ca2b176.PNG)

If these are not bugs, my apologies, I haven't used python in quite some time.

Regards,
Bits

**Comment by jarvisteach** [comment]
Closing this as main issue has been resolved. I can;t reproduce the issue with the add button, if you have anything to add (platform, python version, etc) - please add it to the new issue I created #502
