### ISSUE TITLE
Ask for help, I am a newbie! ide is Pycharm

### ISSUE THREAD

**Issue by zainbeau** [jarvisteach/appJar#483]
![image](https://user-images.githubusercontent.com/31034244/42774398-ec37d7d2-8931-11e8-9a5d-c588888d5111.png)

**Comment by zainbeau** [comment]
###This problem, let me crash!! Please kindly help me.!###

**Comment by zainbeau** [comment]
![image](https://user-images.githubusercontent.com/31034244/42774569-5501d038-8932-11e8-9391-6dcb299a35c0.png)

**Comment by jarvisteach** [comment]
I was just about to say it looks like an installation issue...

Then I noticed your program is called `appJar.py` - that will definitely stop it form working, as your program is replacing the appJar library when it's run.

Try renaming your program to something else...

**Comment by Binxlola** [comment]
And that is why Jarvis is a teacher! haha

**Comment by zainbeau** [comment]
The problem is so simple!!!I am too stupid....
