### ISSUE TITLE
Unable to packaging the .py app via pyinstaller (installed through python setup.py)

### ISSUE THREAD

**Issue by md4956** [jarvisteach/appJar#485]
Hi,
cant packaging the app, 
```
Traceback (most recent call last):
  File "md_app.py", line 1, in <module>
ImportError: No module named appJar
[95932] Failed to execute script md_app
logout
```

I tried so much to import appJar from my venv folder in the app's directory.
could you please tell me how should i import it ?

this is what i'm entering in mac terminal:
`pyinstaller -F -w -p venv/lib/python3.6/site-packages/appJar/  md_app.py`

**Comment by Binxlola** [comment]
Have you tried moving the appJar folder out of venv folder? I tried to package once before on Mac and it worked, however my appJar folder was not in the venv folder but rather in the projects folder.

**Comment by md4956** [comment]
Thank you so much for your solution,
It worked on my Mac now.
