### ISSUE TITLE
Disabling Menu Item doesn't disable shortcut

### ISSUE THREAD

**Issue by robertmlinden** [jarvisteach/appJar#486]
When disabling a menu item (source: http://appjar.info/pythonBars/#menubar) using `.disableMenuItem(menu, name)`, its corresponding keybind shortcut is _not_ disabled! That seems like an issue to me!

**Comment by jarvisteach** [comment]
Yes, this has been an issue for a while. The shortcuts and menus are completely unconnected in tkinter - the menus are created just like any other widget, then the shortcuts are applied to the GUI. There is an outstanding feature request somewhere, to get this resolved - I'll raise the priority.

**Comment by jarvisteach** [comment]
Closing this, part of menu refactor.

**Comment by robertmlinden** [comment]
Let me add that when I open a subwindow (the main window containing the menu), the keybinds are _still_ active in the main window, even if the subwindow is `modal`.

**Comment by robertmlinden** [comment]
But I want to clarify that this is _only_ the case with **menu** keybinds, not normal keybinds attained with `self.bindKey(key)`.
