### ISSUE TITLE
Subwindow blocking not working

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#491]
I am trying to set blocking on a sub-window, so that a widget will not be created until a user clicks submit and hides the sub-window. However I get the following error message.

`Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Jason Smit\AppData\Local\Programs\Python\Python36-32\lib\tkinter\__init__.py", line 1702, in __call__
    return self.func(*args)
  File "C:\Users\Jason Smit\PycharmProjects\Project-X\appJar\appjar.py", line 14072, in <lambda>
    command=lambda row=val, *args: self.action(row)
  File "C:/Users/Jason Smit/PycharmProjects/Project-X/main.py", line 74, in to_checkout
    app.showSubWindow("quantity selection")
  File "C:\Users\Jason Smit\PycharmProjects\Project-X\appJar\appjar.py", line 5498, in showSubWindow
    tl.block()
  File "C:\Users\Jason Smit\PycharmProjects\Project-X\appJar\appjar.py", line 13705, in block
    self.parent.wait_window(self.killLab)
AttributeError: 'SubWindow' object has no attribute `'parent'``

However modal does work, so I am confused as to why one accepts that there is a parent window and the other does not.

**Comment by jarvisteach** [comment]
Hi @binxola - could you post some example code, so I can test this out?

**Comment by Binxlola** [comment]
The sub-window that I am referring to:

`with app.subWindow("quantity selection"):
      app.setResizable(canResize=False)
      global current_quantity
      current_quantity = 1
      app.setStretch("column")
      app.setSticky("ew")
      app.addLabel("quantity_description", "Please select the desired quantity to checkout.", 0, 0, 2)
      app.addLabel("selected_quantity", current_quantity, 1, 0, 2)
      app.addButton("+", quantity_select, 2, 0)
      app.addButton("-", quantity_select, 2, 1)
      app.addButton("Select", quantity_select, 3, 0, 2)`

Here are the handlers for the sub-window:

`def quantity_select(btn):
    """Functionality for adding and removing quantity from quantity selection."""
    global current_quantity, max_quantity, checkout_quantity
    if btn == "+":
        if current_quantity == max_quantity:
            pass
        else:
            current_quantity += 1
            app.label("selected_quantity", current_quantity)
    elif btn == "-":
        if current_quantity is 1:
            pass
        else:
            current_quantity -= 1
            app.label("selected_quantity", current_quantity)
    elif btn == "Select":
        checkout_quantity = current_quantity
        current_quantity = 1
        app.label("selected_quantity", current_quantity)`

I will also note that I am starting the application in another sub-window

`app.go(startWindow="Login")`

Let me know if there is anything else I am missing, or that you would like.

**Comment by jarvisteach** [comment]
Should be resolved now.
