### ISSUE TITLE
appJar with OO format

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#494]
How would I be able to get each window to be their own class, with their own methods. For example a class for the main GUI, then a class for the login window.....etc? I have tried over and over, but can not seem to get anything to work.

**Comment by jarvisteach** [comment]
Hi @Binxlola - that's really not how appJar is meant to be used. The whole original idea was to make it accessible to middle school kids, so, if anything, its meant to hide away the need for OO.

Through appJar, you can configure and access new windows just like any other widget.

appJar uses a *container stack* - you tell appJar which container you're working on by calling:
```python
# push a subWindow onto the top of the stack
app.startSubWindow('Login')
# you're now configuring the subWindow
app.setBg('blue')
app.addLabel('title', 'Login')
# pop the subWindow off the stack
app.stopSubWindow()
# you're now configuring whatever container was previously on the stack
```

Alternatively, you can use context managers:
```python
# push a subWindow onto the top of the stack
with app.subWindow('Login'):
        # you're now configuring the subWindow
        app.setBg('blue')
        app.addLabel('title', 'Login')
# dedenting will pop the container off the stack
```
