### ISSUE TITLE
NextRelease branch - replaceAllTableRows not working

### ISSUE THREAD

**Issue by jbhurst** [jarvisteach/appJar#498]
I'm not sure if you want bug reports on the NextRelease branch, but when I updated to that to try a fix to removeAllWidgets, I noticed replaceAllTableRows wasn't working.  There isn't an error, but when I run it in .93, it works, and when I run it in NextRelease (7/27/2018) nothing happens.  

If it matters, in my case I first build the table with headers but now rows in a hidden subWindow, then I call the replaceAllTableRows function when the window is opened.

**Comment by jarvisteach** [comment]
Oh dear! Are you running python2 by any chance?

**Comment by jarvisteach** [comment]
Looks like I broke it, making changes to the DB table functions...

**Comment by jarvisteach** [comment]
Should now be resolved.

**Comment by jbhurst** [comment]
And yes, I am running Python 2.7... I'm trying to get off it, but I have an open source dependency that I'll need to rewrite first, which is un-fun.
