### ISSUE TITLE
Question: Matplotlib Interactivity

### ISSUE THREAD

**Issue by kamilm** [jarvisteach/appJar#500]
I'm looking for a quick example of any sort of interactivity with a matplotlib figure/plot being implemented with appJar -- I know that MPL is not intended for interactive visualization, but my needs aren't very complex. I'm really just looking to implement : 
https://github.com/anntzer/mplcursors 
into my appJar app. I haven't dug deep yet, but was putting this out as more of a feeler than anything else.

**Comment by jarvisteach** [comment]
You should be able to use mplcursors with appJar.

There are issues running matplotlib and tkinter side-by-side, so you won't be able to import mplcursors until after the GUI is created, but it should work:

```python
from numpy import sin, pi, arange
import random
from appJar import gui 

with gui() as app:
    x = arange(0.0, 3.0, 0.01)
    y = sin(random.randint(1,10) * pi * x)
    axes = app.addPlot("p1", x, y)
    axes.set_title("Click somewhere on a line.\nRight-click to deselect.\nAnnotations can be dragged.")
    axes.legend(['The curve'])
    axes.set_xlabel("X Axes")
    axes.set_ylabel("Y Axes")

    import mplcursors
    mplcursors.cursor(axes)
```

**Comment by kamilm** [comment]
wonderful, thank you for the code snippet as well.

**Comment by jarvisteach** [comment]
No worries - let me know how it works out for you!
