### ISSUE TITLE
Docs Website Search Menu is Flakey

### ISSUE THREAD

**Issue by robertmlinden** [jarvisteach/appJar#509]
Not sure if this has been brought up yet, but wanted to give my take on it.

The search bar on the docs site is EXTREMELY useful (even considering how neat and navigable the site is). However, it almost never works, even with great internet connectivity. It just hangs; no results appear. _Sometimes_ it works, but I can't tell you when or why.

**Comment by jarvisteach** [comment]
The docs site is all written in markdown, and then built using [mkdocs](https://www.mkdocs.org) - searching is a built in feature, so I don't even know where to begin resolving this!

According to [this](https://www.mkdocs.org/user-guide/configuration/#search) mkdocs uses [lunar.js](https://lunrjs.com), so it looks like it should be quite a robust plugin. I've never had any issues in my dev environment, and although I think I have seen what you describe a couple of times on the live site, I'd need some kind of error message to know where to start.

Next time you see this, if you could inspect the page, and check the error logs - maybe there's a missing JS file?

**Comment by robertmlinden** [comment]
I'm having no problems with Chrome now, the problem seems to be with Microsoft Edge!

**Comment by jarvisteach** [comment]
Going to close this - there may well be an issue with Edge & MkDocs search - but it will be upstream with MkDocs - and the next release will be using a newer version, so it may have been resolved.
