### ISSUE TITLE
Get Active Window

### ISSUE THREAD

**Issue by robertmlinden** [jarvisteach/appJar#510]
Is it possible to get the currently active (sub)window's id? I tried a number of things, including `app.getActiveWindow()` but to no avail.

**Comment by jarvisteach** [comment]
OK - so came up with a solution...

Whenever a widget receives the focus, a function is called to store the widget's ```winfo_toplevel()```. Then, there is a function and property exposed to get these: ```getLastFocus()``` & ```lastFocus```

If the current window is a subWindow, it'll return the name of the subWindow, otherwise it will return None.
