### ISSUE TITLE
Tables: Vertical Orientation Support

### ISSUE THREAD

**Issue by robertmlinden** [jarvisteach/appJar#511]
Hi,

Can you support Vertical orientation for tables in future beta releases (headers appear in **column** 0, entries occupy columns, not rows.

Thanks!

**Comment by robertmlinden** [comment]
If you don't mind, I'll use this as a thread for question suggestions regarding Tables, as they are still in beta:

In the image below, I have set the table background to be red for clarity. It seems that the table is _expecting_ N (15-or-so) rows and is leaving space for them. Is there a way to confine the space that the table takes up to the minimum necessary?

![table_capture](https://user-images.githubusercontent.com/9124381/43922898-109bbc50-9bee-11e8-8e76-8b0080d84bdc.PNG)

**Comment by jarvisteach** [comment]
Definitely something we can look into, but will take a while!

**Comment by jarvisteach** [comment]
Adding this to the table backlog - #266

**Comment by robertmlinden** [comment]
Just an after thought, this would be useful for key value pair display.
