### ISSUE TITLE
Hello World [documentation] [old non working methods]

### ISSUE THREAD

**Issue by muhammad-al-baqir-khalid** [jarvisteach/appJar#516]
http://appjar.info/pythonLessons/#/2/9
code:
app.setGeometry('400x300') #not working
app.setResizable(False) #not working

app.setSize(200,300) #working
app.setResizable(canResize=False) #working

**Comment by jarvisteach** [comment]
Thanks for pointing that out!

I've updated the docs to show setSize instead of setGeometry, although I haven't made the other change as both should work.
