### ISSUE TITLE
Table Coloring?

### ISSUE THREAD

**Issue by robertmlinden** [jarvisteach/appJar#517]
Is there a way to style Tables? There doesn't seem to be documentation for this beta widget.

EDIT: documentation **on styling**

**Comment by robertmlinden** [comment]
Specifically, individual table rows. I mean there's highlighting, but there's no custom coloring so far as I can see. I would like to give the table a dark theme with light text, perhaps!

**Comment by jarvisteach** [comment]
There is a way to do it, using the new 1.0 syntax.

![tbl](https://user-images.githubusercontent.com/13473435/44083647-86cd1218-9fac-11e8-9e69-800098087ab7.png)

You can set any of: `activeFg`, `inactiveFg`, `activeBg`, `inactiveBg`:

```python
from appJar import gui 

with gui() as app:
    app.table("g1",
        [["Name", "Age", "Gender"],
        ["Fred", 45, "Male"],
        ["Tina", 37, "Female"],
        ["Clive", 28, "Male"],
        ["Betty", 51, "Female"]],
        inactiveBg='red', inactiveFg='yellow',
        activeBg='blue', activeFg='white'
        )   
```

**Comment by jarvisteach** [comment]
There are other properties that *could* be set, they;re just not implemented yet...

**Comment by robertmlinden** [comment]
Can such properties _only_ be assigned in the table's 1.0 constructor or is there a way to recolour afterwards?

e.g. `.setTableActiveFg()` (which isn't recognized)

**Comment by jarvisteach** [comment]
Closing, noted in backlog #266
