### ISSUE TITLE
drawing inside form using turtle built-in module[request]

### ISSUE THREAD

**Issue by muhammad-al-baqir-khalid** [jarvisteach/appJar#525]
I'm using turtle built-in module to make a circle but it's using another window. I would like to drawing it inside the same form that appJar use.
about turtle built-in module:
The turtle module provides turtle graphics primitives, in both object-oriented and procedure-oriented ways. Because it uses **Tkinter** for the underlying graphics, it needs a version of Python installed with Tk support.
https://docs.python.org/3.7/library/turtle.html

**Comment by muhammad-al-baqir-khalid** [comment]
import turtle as draw
from appJar import gui

app = gui('Draw')
drawing = draw.Turtle()
drawing.circle(30)
app.go()
draw.done()

if you close one of the forms u will get an error.

**Comment by muhammad-al-baqir-khalid** [comment]
Traceback (most recent call last):
  File "C:\Users\PC\Desktop\Learning\eiu.py", line 9, in <module>
    draw.done()
  File "<string>", line 8, in mainloop
  File "C:\Users\PC\AppData\Local\Programs\Thonny\lib\turtle.py", line 813, in mainloop
    TK.mainloop()
  File "C:\Users\PC\AppData\Local\Programs\Thonny\lib\tkinter\__init__.py", line 557, in mainloop
    _default_root.tk.mainloop(n)
AttributeError: 'NoneType' object has no attribute 'tk'

**Comment by jarvisteach** [comment]
Ah, OK, I see.

Have you seen this:  http://appjar.info/outputWidgets/#turtle

**Comment by muhammad-al-baqir-khalid** [comment]
Nice work it's worked :D
