### ISSUE TITLE
[Help]Remove Label entirely

### ISSUE THREAD

**Issue by muhammad-al-baqir-khalid** [jarvisteach/appJar#526]
Thank you for your work on this project  ❤️ 💓 
I'm new in programming and sorry about the last question I'm a little bit lazy, but this time I search a lot about on your website but I don't find anything.
*I want to delete a label entirely.
or at lease stop a label from flashing.
---------------------------------------------------------------------------
https://gist.github.com/muhammad-al-baqir-khalid/b4d4a31580d6b6c6fca505f5e3c42313

**Comment by jarvisteach** [comment]
A `FlashLabel` is just a `Label` - so to remove/hide/show them you can use the functions:
* win.hideLabel('Lbb1')
* win.showLabel('Lbb1')
* win.removeLabel('Lbb1')

This may not be clear in the docs, I'll have a look at them later.

**Comment by muhammad-al-baqir-khalid** [comment]
Thanks so much :) to fast replay and your hard work into this whole project. 💓
