### ISSUE TITLE
StackOverflow appJar tag creation

### ISSUE THREAD

**Issue by muhammad-al-baqir-khalid** [jarvisteach/appJar#528]
StackOverflow appJar tag creation instead of help in the issues tab.
there already nearly **100** questions asked on StackOverflow.
https://stackoverflow.com/search?q=appJar

**Comment by jarvisteach** [comment]
You need 1500 reputation to create a tag: https://stackoverflow.com/help/privileges/create-tags

Any volunteers?

I also think a lot of those questions may be related to jar files in java...
