### ISSUE TITLE
Add custom text to the select entry 

### ISSUE THREAD

**Issue by cristianmarian95** [jarvisteach/appJar#533]
Add args in addFileEntry were you can set your on custom text for the select buttons  

>    if selectFile:
>             command = self.MAKE_FUNC(self._getFileName, title)
>             vFrame.theWidget.click_command = self.MAKE_FUNC(self._checkFileName, title)
>             text = "File"
>             default = "-- enter a filename --"
>         else:
>             command = self.MAKE_FUNC(self._getDirName, title)
>             vFrame.theWidget.click_command = self.MAKE_FUNC(self._checkDirName, title)
>             text = "Directory"
>             default = "-- enter a directory --"

**Comment by jarvisteach** [comment]
There is already a request for this feature (#170) which has been moved to the entry backlog (#527).

I think the text, default & command should all be customisable.

Will close this, and update #527.
