### ISSUE TITLE
In versions of Python where TK is bundled (starting in 3.6.5-3.7), Tooltips do not show up 

### ISSUE THREAD

**Issue by tazzben** [jarvisteach/appJar#541]
I'm not positive if this is question or a bug.  I've notice (at least in macOS Mojave) that tooltips seem to not function with versions of python that bundle TK. They don't produce an error, they are simply not triggered.

Example:

```
from appJar import gui 

with gui() as app:
    app.label('test')
    app.addLabel("l1", "text")
    app.setLabelTooltip("l1", "text")

```
This is true of the latest version appJar.  Probably related to issue #428

**Comment by jarvisteach** [comment]
Thanks for raising this - we've got some nice new virtualboxes at school running the latest version of python, I'll have a dig around next week.

**Comment by jarvisteach** [comment]
Fixed in next release
