### ISSUE TITLE
Sub-window with Meter generates dimension error

### ISSUE THREAD

**Issue by chrisw-thomas** [jarvisteach/appJar#543]
# Bug Report
`2018-10-12 09:35:59,986 appJar:WARNING [Line 25->2283/setSize]: Specified dimensions (400, 25) less than requested dimensions (378, 265)`

I create a sub-window, set its size using .setSize and then add a progress widget using .addMeter. When I start the Python application I get the error shown above.

## Context
---
 The simple code is below.

    
```
    win.startSubWindow('progress', modal=True)
    win.setSize('400x25')
    win.setResizable(False)
    win.setOnTop(stay=True)
    win.setStretch('both')
    win.setSticky('nsew')
    win.addMeter('progress')
    win.setMeter('progress', 0, text=None)
    win.setMeterFill('progress', 'Gray')
    win.stopSubWindow()
```
   
```
appJar: 0.93.0 Python: 2.7.14 TCL: 8.5, TK: 8.5 Platform: Windows pid: 18668
locale: en_GB

**Comment by jarvisteach** [comment]
Thanks for this, I;ve been noticing it a lot more recently. It was a warning I added a long time ago, to point out to students that their requested dimensions were off, but I think the logic got a bit broken somewhere long the way, and I'm just going to remove it.

**Comment by chrisw-thomas** [comment]
No problem... when is the next appJar release due? Presumably this will be v1.0?

**Comment by chrisw-thomas** [comment]
Excellent - thank you.
