### ISSUE TITLE
Running processes as threads to allow for GUI updates

### ISSUE THREAD

**Issue by simonjharris** [jarvisteach/appJar#550]
I doubt this is really an 'issue', but I've read all the documentation and I really can't seem to get my head around how to run processes as threads to allow for GUI updates. I would really appreciate it if someone could take a look at my code.

The problems I'm having are summarised here: https://stackoverflow.com/questions/53085433/appjar-threading-to-allow-for-gui-updates

Cheers,
Simon

**Comment by jarvisteach** [comment]
I’ve put an answer on StackOverflow.
