### ISSUE TITLE
Table Column names are not appearing 

### ISSUE THREAD

**Issue by Binxlola** [jarvisteach/appJar#553]
# Bug Report
---

## Context
---
Trying to display a table that is coming from a sqlite3 connection.  

## Expected Behaviour
---
It's expected that the table will show all data, with the actual column names at the top. Like you might find in an EXCEL sheet. The expected display should have column names Item, Amount, Cost.

## Actual Behaviour
---
The display is cutting off the column names, and using the first row in the table as the column names. Any rows after the first are displayed correctly.
![table_bug](https://user-images.githubusercontent.com/38807670/48456577-493cfb00-e824-11e8-8660-7a07511e5b0d.png)

## Any error messages produced by appJar
---
Replace this with any error messages that are produced.  

## Sample code, demonstrating the issue
---
 ```
with app.frameStack("main", start=0):
![table_bug](https://user-images.githubusercontent.com/38807670/48456377-bb611000-e823-11e8-82d7-58607e677516.png)

        with app.frame():
            # Tabbed page for displaying info for each category
            with app.labelFrame("Item Inventory"):
                app.setSticky("nwe")
                app.addDbTable("stock", "main.db", "stock", 0, 0, 0, action=to_checkout,  actionButton="Checkout",
                               actionHeading="Checkout", border="solid", showMenu=True)
                app.setTableEditFunction("stock", table_edits)
                app.setSticky("s")
                app.addButton("Add Item", add_item, 10, 0)
```

## What steps are needed to reproduce the bug
---
Replace this with the steps we should follow to reproduce the bug.  

## Version Information
---
Using python 3.7

**Comment by jarvisteach** [comment]
Hi @Binxlola - can I check what version of appJar this was with? And could you provide a simple table that I can use to replicate the issue? Thanks!
