### ISSUE TITLE
Warning Message after executing deleteTabbedFrameTab

### ISSUE THREAD

**Issue by jcolom64** [jarvisteach/appJar#554]
# Bug Report
---

## Context
---
I noticed that Tabbed Frames can now be delete so I created a very simple test using the sample code from TabbedFrames (http://appjar.info/multiplePages/#tabbedframes), and added a delete button that will delete the first tab "Homer" using deleteTabbedFrameTab. The code seems to have deleted the tab, but I am getting a message warning:

Is this a warning that I can ignore or is it really not cleaning all the widgets?

## Expected Behaviour
---
Delete Tab without any warning or error messages 

## Actual Behaviour
---
Message Warning display in console  

## Any error messages produced by appJar
---
"appJar:WARNING [Line 10->5479/cleanseWidgets]: Unable to destroy Frame, during cleanse - no match" 

## Sample code, demonstrating the issue
---
from appJar import gui

data = [["Homer", "Simpson", "America", 40],
        ["Marge", "Simpson", "America", 38],
        ["Lisa", "Simpson", "America", 12],
        ["Maggie", "Simpson", "America", 4], 
        ["Bart", "Simpson", "America", 14]]

def btnCallback(btn):
    app.deleteTabbedFrameTab("Address Book", "Homer")

with gui("Updating Labels") as app:
    with app.tabbedFrame("Address Book"):
        for pos in range(len(data)):
            with app.tab(data[pos][0]):
                app.entry(str(pos)+"fName", data[pos][0], label="First Name")
                app.entry(str(pos)+"lName", data[pos][1], label="Last Name")
                app.entry(str(pos)+"country", data[pos][2], label="Country")
                app.entry(str(pos)+"age", data[pos][3], kind='numeric', label="Age")
    app.addButton("Delete", btnCallback)

## What steps are needed to reproduce the bug
---
Click the Delete button to remove the first Tab 

## Version Information
---
"0.93.0"

**Comment by jarvisteach** [comment]
Thanks for raising this.

I think it’s actually fixed in the next release.
