### ISSUE TITLE
TextArea tags not showing tag ranges

### ISSUE THREAD

**Issue by mtalimanchuk** [jarvisteach/appJar#558]
Hi! I am doing some text parsing and need to tag text in the TextArea on the go. I can do so by selecting a range, then pressing a button. 
The problem is, `getAreaTextTag` returns only the tag config and I haven't found a way to get the actual ranges, except for using tkinter's `tag_ranges()` and your `widgetManager`:

`app.textAreaTagSelected('main_TextArea', 'Tagged')`
`ta = app.widgetManager.get(app.Widgets.TextArea, 'main_TextArea')`
`print(ta.tag_ranges('Tagged'))`

Which IMHO is not very Pythonic.
I see you used a lot of similar functions calling other tkinter's `tag_xxx()` methods but not `tag_ranges()`. Maybe it is worth implementing?

**Comment by jarvisteach** [comment]
Thanks for this, the text areas tag features is something I've not used much, so always happy to find out how people use it. This is definitely something we can add!

**Comment by mtalimanchuk** [comment]
@jarvisteach thanks for your reply! I'm glad to see the project is up. May I send a pull request with possible text area enhancements?

**Comment by jarvisteach** [comment]
Yes please! Can you make sure it's against the latest version of the `next_release` branch.

**Comment by jarvisteach** [comment]
Pull reuest #572 merged
