### ISSUE TITLE
icon/image shifted up in buttons in ttk themes

### ISSUE THREAD

**Issue by tph002** [jarvisteach/appJar#560]
# Bug Report
---
icons/images are shifted up in buttons in ttk themes (clearlooks, radiance, plastik) when i used the functions addIconButton(), addImageButton()). 

## Context
---
Usage of functions addIconButton(), addImageButton()). 

## Expected Behaviour
---
icon/image centered in buttons.  

## Actual Behaviour
---
icon/image shifted up in buttons.  

## Any error messages produced by appJar
---
no error messages produced.  

## Sample code, demonstrating the issue
---
I found a fix for this issue. I replaced in the appjar.py file all of the occurrences of "COMPOUND=TOP" with "COMPOUND=CENTER". And everything turns out OK.

Thanks for your great work.

## Version Information
---
appjar version 0.93

**Comment by jarvisteach** [comment]
Great, thanks, I'll get that added to the next release - so many little tweaks needed to get ttk support fully working!

**Comment by jarvisteach** [comment]
This should be resolved in the next release...
