### ISSUE TITLE
version 1.0

### ISSUE THREAD

**Issue by pg-doceapower** [jarvisteach/appJar#562]
Hi @jarvisteach I'm not seeing much activity these days. I'v been using appJar and found it great. do you know when version 1.0 will come out?

**Comment by jarvisteach** [comment]
hi @pg-doceapower  - yeah things have been a bit quiet recently, lots of life stuff getting in the way!

I should be able to find a bit of time to go through the issues backlog, and look at tidying that up - and potentially get a release out over Easter.

As to the *big 1.0* release - that probably won't be done until the summer time, unless I can free up more time in between...

**Comment by jarvisteach** [comment]
Everything is ready for the 1.0 release (and in the 0.9x releases) - I just need to rewrite the docs...
