### ISSUE TITLE
Problem report on official website

### ISSUE THREAD

**Issue by inmaldrerah-e** [jarvisteach/appJar#564]
# Problem Report
This is actually not a bug report for appJar, but one for its official website (appjar.info)
---

## Context
The problem is at [http://appjar.info/pythonLoopsAndSleeps/#advanced-loops](http://appjar.info/pythonLoopsAndSleeps/#advanced-loops).
You will find:
```python
# global variable to store the count
counter = 10

def acceleratingCountdown():
    global counter
    if counter > 0:
        app.setLabel("counter", str(counter))
        counter -= 1
        app.after(100*counter, myLoop)

app.after(0, acceleratingCountdown)
```
However, 
```python
        app.after(100*counter, myLoop)
```
should be
```python
        app.after(100*counter, acceleratingCountdown)
```
in my opinion.

**Comment by jarvisteach** [comment]
Definitely - good spot, will get that sorted ASAP.
