### ISSUE TITLE
Create Meter object without gradient?

### ISSUE THREAD

**Issue by tnsolley** [jarvisteach/appJar#565]
# Bug Report
---

## Context
---
Implementing the Meter object in a UI, as a form of "Progress Bar".  

## Expected Behaviour
---
Expected to be able to set the fill-type as one color, and this color would be without gradient.  

## Actual Behaviour
---
No control exists over this aspect of the widget.  

## Any error messages produced by appJar
---
No errors are produced.  

## Sample code, demonstrating the issue
---
```
app.meter("m1", row=2, column=2, colspan=7, sticky="ew")
app.setMeterFill("m1", "green")
```  
To update the meter;
```
for i in range(0, 10):
  val = 10*(i)
  app.thread(app.setMeter, "m1", val)
# End for-loop
app.thread(app.setMeter, "m1", 100)
```

## What steps are needed to reproduce the bug
---
Add this to a GUI object of your choice.

## Version Information
---
appJar: 0.93.0 Python: 3.7.2 TCL: 8.6, TK: 8.6 Platform: Windows pid: 6692
locale: en_US

**Comment by tnsolley** [comment]
Question:
Can a feature be added to give users more control over the "Meter style", and by that I mean make `app.setMeterFill()` allow-for the option to enable or disable the black-to-white gradient?

**Comment by jarvisteach** [comment]
Definitely something I can look into - should be fairly trivial to remove the gradient feature...

**Comment by jarvisteach** [comment]
Implemented in the next release.
