### ISSUE TITLE
Google Maps requires API key

### ISSUE THREAD

**Issue by wilt00** [jarvisteach/appJar#567]
# Bug Report
---

## Context
---
I'm interested in using appJar as part of a workshop for presenting geographical data, and so was very excited about the Google Maps widget. This appears not to be working due to the external APIs it relies on (see also #566 ).

## Expected Behaviour
---
Google Maps widget appears.

## Actual Behaviour
---
Google Maps widget appears, but without any map.

## Any error messages produced by appJar
---
```
2019-01-30 16:41:06,680 appJar:ERROR [14542/getMapData]: Unable to contact GoogleMaps
```
Repeated every second or so.

## What steps are needed to reproduce the bug
---
The default URL returned by `GoogleMap._buildQueryURL()` (using the default Marlborough location) is `http://maps.google.com/maps/api/staticmap?center=Marlborough%2C+UK&zoom=16&size=500x500&format=gif&maptype=Roadmap&sensor=false`. Visiting this address returns the following text:

`The Google Maps Platform server rejected your request. You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account`

That link points to https://cloud.google.com/maps-platform/user-guide/account-changes/, which states that all Google geolocation API calls must now include an API key attached to a billing account.

## Version Information
---
appJar: 0.93.0 Python: 3.7.2 TCL: 8.6, TK: 8.6 Platform: Windows pid: 9080
locale: en_US

**Comment by jarvisteach** [comment]
Ouch, looks like Google have changed how maps works - everyone now needs an API key connected to a credit card!

You get the first $200 worth of requests free, but after that they start charging you.

I will make a change, so an API key can be set, and update the docs, showing how to get an API key.

I'll also investigate if there is a free, open source alternative - maybe OSM?

**Comment by jarvisteach** [comment]
Resolved in next_release

**Comment by MoesLab** [comment]
Is there any update for 2020 ? Is version 1 out yet?
