### ISSUE TITLE
[Feature request] Adjustable Canvas size

### ISSUE THREAD

**Issue by zombiestruck** [jarvisteach/appJar#568]
# Feature Request
---
## Current situation
---
Canvas size is static
## Suggested Behavior
---
Canvas should be resizeable
app.setCanvasSize(canvasName, x, y)

**Comment by jarvisteach** [comment]
Hi @zombiestruck - I'm not sure I'm seeing the same behaviour.

At the moment, the canvas widget fills its space, so if you stretch the GUI, the canvas stretches to fill it.

You can set a specific width & height:
```
app.setCanvasWidth(name, width)
app.setCanvasHeight(name, height)
```

And you can configure it to not resize with the GUI:
```
app.setSticky('')
```
