### ISSUE TITLE
wrong import into examples: rwbatools

### ISSUE THREAD

**Issue by alex-pancho** [jarvisteach/appJar#569]
# Bug Report
14 point was find https://github.com/jarvisteach/appJar/search?q=rwbatools&unscoped_q=rwbatools
but when I run examples - I  get error 
ModuleNotFoundError: No module named 'rwbatools'

## Context
any examples and code into repo where is present
 rwbatools import

## Expected Behaviour
just need replace rwbatools import to appJar import

**Comment by jarvisteach** [comment]
Yup - a hangover from the early days, I'll get that changed...

**Comment by jarvisteach** [comment]
Have changed most of them - that's some really old code, and has a few unsupported functions.

There is also no database/net module on appear anymore.... so a couple can't be fixed

**Comment by jarvisteach** [comment]
Think I got them all.
