### ISSUE TITLE
ClearAllLabels

### ISSUE THREAD

**Issue by Simoneu01** [jarvisteach/appJar#570]
There is a way to clear all labels??

Currently I do:
`app.clearLabel (name_of_label)`

 but if I have N label should write N app.clearLabel (N)

**Comment by jarvisteach** [comment]
Yes, currently no way to clear *all* labels.

Labels are usually for information that doesn't change so much, and usually at least some of them will have titles or other static information.

I therefore never added a `clearAllLabels()` function. I could add it, but it would clear *all* the labels in the app - not sure how useful that is?
