### ISSUE TITLE
Unable to change font through config in ttk mode

### ISSUE THREAD

**Issue by EnderDas** [jarvisteach/appJar#575]
# Unable to change font through config in ttk mode
I noticed that having Ttk theme enabled causes `setFont` and functions called in it to fail and not update fonts

`.config()` does however work, mind that size does not work with `.config` if not given `family` keyword.

###### EDIT:
> to clarify the above sentence as i now realize its hard to read 
> doing `app.getButtonWidget("button").config(font="Arial 20"))` works
> but `app.getButtonWidget("button").config(font="20"))` does not

**Comment by jarvisteach** [comment]
I'm not sure that either of those should work in ttk mode. In ttk mode, you need to apply different styles: http://appjar.info/pythonTtk/

**Comment by jarvisteach** [comment]
To be clear, you can use the following to change the style of buttons:
```
app.ttkStyle.configure("TButton", foreground="green", background="blue", font=('Helvet    ica', 20))
```

**Comment by jarvisteach** [comment]
Closing, as no more discussion
