### ISSUE TITLE
GUI blank on startup

### ISSUE THREAD

**Issue by tnsolley** [jarvisteach/appJar#576]
# Bug Report
---

## Context
---
I am using AppJar to build a test UI, without Login permissions (since not required). I want to control the first Tab, and subsequent Tabs normally.  

## Expected Behaviour
---
On startup, GUI should load my first tab, "Setup", with no restrictions on access.

## Actual Behaviour
---
UI is Blank, Tabs are disabled, Menubar is disabled...  

## Any error messages produced by appJar
---
N/A.  

## Sample code, demonstrating the issue
---
Remove the "Login" tab from <showcase.py>, edit line 147 to not have "Login", comment lines 36 and 37 in <logout()>.

## What steps are needed to reproduce the bug
---
See above.  

## Version Information
---
Python 3.7.2

**Comment by jarvisteach** [comment]
The UI starts in logged out mode - you need to start it in logged in mode. Comment out the final line...
