### ISSUE TITLE
Changing toolbar background color

### ISSUE THREAD

**Issue by nwfistere** [jarvisteach/appJar#577]
Hello,

I've been trying to change the background color of toolbars with no avail. I was wondering if it is even possible at the moment? Any help would be greatly appreciated!

**Comment by jarvisteach** [comment]
Definitely possible, although there is no direct function.
Try: ```app.tb.config(bg='red')```

Depending on your platform, you may have to change the bg on the buttons too...
```
 for child in app.tb.children.values():
     child.config(highlightbackground='red')
```

**Comment by jarvisteach** [comment]
This is now implemented in the next release
