### ISSUE TITLE
Rename CheckBox Text

### ISSUE THREAD

**Issue by chrisw-thomas** [jarvisteach/appJar#578]
# Query
---

## Context
---
I need to define a sub-window containing several named check boxes.

I want to use this sub-window at various points and so need to change the text associated with each check box. The text will be created dynamically as the application is used so I can't just create one or two sub-windows and pop them up.

There doesn't seem to be any way to update the text associated with a check box once it's been created?

I could just keep creating new sub-windows each time but this doesn't seem to be an efficient approach. I seem to recall that deleting widgets doesn't always work or is not supported?

There was a similar request for renaming an option in an option list.

Ideally it would look something like app.renameCheckBox(name, new_title)

**Comment by jarvisteach** [comment]
This can definitely be added, for now you can use the tkinter ```config``` function to manipulate widgets: ```app.getCheckBoxWidget('check').config(text='new text')```

**Comment by jarvisteach** [comment]
Implemented in the next release: `app.setCheckBoxText(title, text)`
