### ISSUE TITLE
setSize("Fullscreen") does not work in Raspberry Pi

### ISSUE THREAD

**Issue by jrullan** [jarvisteach/appJar#580]
## Context
---
Just installed in a fresh Stretch Raspbian image and tested out ok. The problem is that when I try to set it to fullscreen by using setSize("Fullscreen") it returns an error:

```python
Traceback (most recent call last):
  File "<pyshell>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/appJar/appjar.py", line 2274, in setSize
    geom, loc = gui.SPLIT_GEOM(geom)
  File "/home/pi/.local/lib/python3.5/site-packages/appJar/appjar.py", line 360, in SPLIT_GEOM
    width = int(float(geom[0]))
ValueError: could not convert string to float: 'fullscreen'
```  

## Expected Behaviour
---
Replace this with what you expect to happen.  

## Actual Behaviour
---
Replace this with what does happen.  

## Any error messages produced by appJar
---
Replace this with any error messages that are produced.  

## Sample code, demonstrating the issue
---
```python
from appJar import gui

app = gui()
app.setSize("Fullscreen")

# start the GUI
app.go()
```
## What steps are needed to reproduce the bug
---
Just use the code above in a Raspberry Pi Raspbian Stretch

**Comment by jarvisteach** [comment]
Hi, thanks for raising this. If you try: ```app.setSize("fullscreen")```

I'll change the online docs to reflect this, and update the code to be case insensitive...
