### ISSUE TITLE
Delete Table Warning for Each Cell

### ISSUE THREAD

**Issue by weiggwp** [jarvisteach/appJar#584]
# Bug Report
---
Removing Table cause warning for every cell inside of it

## Context
---
I have a Table inside a Frame, 
when I empty the frame, which remove the table, many warning is thrown, one for each cell in the table, slowing down the program...

## Expected Behaviour
---
Delete Table without any warning or error messages

## Actual Behaviour
---
One warning for each cell in console, slow down program
.......

## Any error messages produced by appJar
---
appJar:WARNING [Line 189->5802/cleanseWidgets]: Unable to destroy GridCell, during cleanse - NO APPJAR TYPE

## Sample code, demonstrating the issue

from appJar import gui
app = gui()

app.startFrame(title="demo")
app.addTable('t', [[2,4],[1,4]] )
app.stopFrame()

app.emptyFrame("demo")

app.go()

---

## What steps are needed to reproduce the bug
---
run the code and look at console for 4 warnings

## Version Information
---
appJar: 0.94.0 Python: 3.7.0 TCL: 8.6, TK: 8.6 Platform: Darwin pid: 1519
locale: en_US

**Comment by jarvisteach** [comment]
Yes - definitely an issue here.

You can turn off warnings for now, by adding their code at the start: `app.setLogLevel('ERROR')`

**Comment by jarvisteach** [comment]
Resolved in next_release
