### ISSUE TITLE
AutoEntry remains in focus when value is not manually selected

### ISSUE THREAD

**Issue by mcevoymike** [jarvisteach/appJar#598]
I have a simple Multi Tabbed GUI i'm building where a function that is linked to a button press loads a number of elements in from a previously built 'config' (essentially information stored in a .txt file) to populate various widgets.

One of these elements sets an AutoEntry to a set text.

Whilst the AutoEntry has its value set correctly, the drop down box does not disappear, and even shows as an overlay, when i have another tab that does not contain the widget in focus,

This does not produce any error messages as the content of the AutoEntry is being set correctly and is valid.

To replicate have a multi tabbed Gui, an Auto entry on one tab and a button to populate it on another, the auto entry is populated but the drop down remains open.

as an aside is there any way to force the AutoEntry drop down 'width' to be larger?
you can set the number of rows displayed using .setAutoEntryNumRows(title, rows) but the width doesn't seem to be amendable.

appJar: 0.94.0 Python: 3.7.3 TCL: 8.6, TK: 8.6 Platform: Windows pid: 15444
locale: en_GB

Many Thanks

**Comment by jarvisteach** [comment]
Hi @mcevoymike - thanks for raising this, definitely a bug.

I think a couple of things need to be looked at here:
* Not showing the drop-down when the entry is set from a function
* Making sure the drop-down is removed, when other widgets are clicked

**Comment by jarvisteach** [comment]
The next_release branch has a couple of fixes now: the drop-down isn't shown when a function is used to set the entry.

A new function/property has also been introduced to set the width of the drop-down.
