### ISSUE TITLE
v1.0?

### ISSUE THREAD

**Issue by ghost** [jarvisteach/appJar#613]
hi i really like AppJar and think its one of the best libereries to python and as i'm have seen in the docs version 1.0 is in progres i also saw that you said in another Issue that you just needed to rewrite the docs. I know that it is a really bad time for asking this because of the Covid-19 outbreak but could you please say a date or at least a month when the 1.0 realese is coming because i can't wait for it.

ps. sorry english is not my native language

**Comment by jarvisteach** [comment]
Hi @kowal05 - all the new style, 1.0 features are in the current release, and there is basic documentation on how to use them online here: http://appjar.info/simpleAppJar/

So, you can go ahead and start using them...

**Comment by ghost** [comment]
oh thank you
