### ISSUE TITLE
Transparent Backgrounds

### ISSUE THREAD

**Issue by kristof2020FaE** [jarvisteach/appJar#615]
# Bug Report
---
Hey, not really a bug but is there a way to make label backgrounds transparent?

## Context
---
Im trying to make an app with a .png background and the text labels were a bit annoying  

## Expected Behaviour
---
Text which has no background, only pure text, like this sentence  

## Actual Behaviour
---
the text not matching with the background 

## Any error messages produced by appJar
---
no error messages, it just doesnt look good 

## Sample code, demonstrating the issue
---
from appJar import gui
app = gui("login", "100x100")
app.addLabel("asd")
app.setBgImage("xy.png")
app.go()

## What steps are needed to reproduce the bug
---
code above
## Version Information
---
![asd](https://user-images.githubusercontent.com/62730002/80755189-a9b31b80-8b30-11ea-94e6-a048e377b330.png)

python:3.8
appJar: 94.0

**Comment by jarvisteach** [comment]
Hi @kristof2020FaE, it's not possible for Labels to be 'transparent' in tkinter/appJar.

However, you could tell the labels not to 'stick; to the sides of the GUI, so you don't get that whole grey bar. Have a read of this: http://appjar.info/pythonWidgetLayout/#setting-stretchiness
