### ISSUE TITLE
is it possible to remove deafult command line arguments?

### ISSUE THREAD

**Issue by ghost** [jarvisteach/appJar#623]
I have made a notepad app and i am trying to make it open a file just by double-clicking the file but it gives me an error

error: 
```
usage: script.py [-h] [-v] [-c | -e | -w | -i | -d | -t] [-l LANGUAGE.ini] [-f file.log] [-s [SETTINGS]] [--ttk [THEME]]
temp.py: error: unrecognized arguments: C:\Users\user\deskop\file.txt
```

I am thinking it is because it has the default arguments form the appJar, is there a way to remove or disable them? 
I don't know if this is important or not but I am using sys.argv to get the arguments

**Comment by jarvisteach** [comment]
Have a look here: http://appjar.info/pythonCommandLine/#disabling <http://appjar.info/pythonCommandLine/#disabling>

**Comment by ghost** [comment]
oh, thanks 
I don't know why I totally couldn't see this when I tried to find about it in the docs
