### ISSUE TITLE
tkinter introduction of values to read

### ISSUE THREAD

**Issue by guillermocol** [jarvisteach/appJar#624]
hello, I was trying to create a function to read data and to store it using tkinter. Basically I would like to introduce a value from console using tkinter and to store it in an array or a variable.
Do you know the best function to use with tkinter?

## Version Information
3.6

Thanks,
G

**Comment by guillermocol** [comment]
Hi @jarvisteach would you recommend me to use another library perhaps?

**Comment by jarvisteach** [comment]
Hi there, I'm not really sure what your question is...

You can use an [entry](http://appjar.info/inputWidgets/#entry) to capture input in a GUI, and save the results of that to any type of variable.

If you want to learn more about how to do that, have a look through [lesson 3](http://appjar.info/pythonLessons/#/lesson_3) in our learning resources.

**Comment by guillermocol** [comment]
Thank you jarvisteach, it is very useful.
