### ISSUE TITLE
Can we set the length of entry?

### ISSUE THREAD

**Issue by leonarduz** [jarvisteach/appJar#625]
# Bug Report
---
hi is it possible do set the lenght of entry widget?
I am not talking  about .setEntryMaxLength, cause it sets maximum number of letters, that can be written in entry. I would like to have entry that cant be resized by changing the size of window
Is it possible?

## Actual Behaviour
---
Replace this with what does happen.  

## Any error messages produced by appJar
---
Replace this with any error messages that are produced.  

## Sample code, demonstrating the issue
---
Replace this with a cut-down version of code, that demonstrates the issue.  

## What steps are needed to reproduce the bug
---
Replace this with the steps we should follow to reproduce the bug.  

## Version Information
---
Replace this with the result of running your code with the -v flag: `python myCode.py -v`

**Comment by jarvisteach** [comment]
Yes, it's definitely possible, you can call `app.setEntryWidth('name', 20)` to set the width of the entry box. However, by default, widgets stick to the sides of the column, so will expand to fill the column they are in. So you all have to turn off 'stickiness' by calling `app.setSticky('nw')` right before you add the entry box. Have a look [here](http://appjar.info/pythonWidgetLayout/#widget-positioning) for more info:

**Comment by leonarduz** [comment]
Thanks a lot
