### ISSUE TITLE
Add button capability or show how to add buttons

### ISSUE THREAD

**Issue by Sharan-Python** [jarvisteach/appJar#634]
Is there a way to add buttons with this module or has it not been created yet, if it has not been created I would like to to be made

**Comment by jarvisteach** [comment]
Yes, there’s definitely a way to add buttons. If you have a red through the documentation here <http://appjar.info/inputWidgets/#button> you’ll see there re a few options.

**Comment by Sharan-Python** [comment]
Sorry this was a really stupid question
