### ISSUE TITLE
Implement Split/Dual Meters

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#65]
Want 3 types of meter:
- Basic meter - shows progress from 0 - 100%
- Split meter - show 2 colours, with midline, midline moves left & right to show 'possession'
- Dual meter - shows midline with colours moving out left & right - showing progress towards finish

All should use same getters/setters
All should use gradiated colours
All should be able to show text on the meter

**Comment by maestroi** [comment]
If i put a timer in a loop and run it will crash the gui.

`def press(btn):
if btn == "Test":
        teller()`


`def teller():
    for i in range(1,100,1):
        test2 = i + 1
        print test2
        app.setMeter("teller2",test2)
        time.sleep(0.5)`

`app=gui(naam, "400x450")
app.setExpand("both")
app.setFont(10)
app.setSticky("news")
app.addButton("Test", press, 16, 3, 0)`

**Comment by maestroi** [comment]
http://appjar.info/pythonDevWidgets/ missing normal Meter info

**Comment by jarvisteach** [comment]
That's right - you can't have loops in your code, as they will cause the GUI to hang. This is a common theme with most GUIs - calling ```app.go()``` starts a loop, that is checking for events. If you then start another loop (especially with a sleep), the event loop will hang waiting for the second loop to finish.

In order to have background processes run, you need to register them with the GUI, and have the [GUI call them](http://appjar.info/pythonEvents/#repeating-events )

In this case, call ```app.registerEvent(teller)```
You can change the frequency of events, by calling ```app.setPollTime(xxx)```

If you want the event to stop after a certain number of calls, add a global variable to count each time the function is called, then don't perform the action when you reach the target.
