### ISSUE TITLE
TextArea Features

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#69]
Useful features:
* [x] Default message
* [x] Support for adding tags
* [x] Support for setting style on tags
* [x] Style options: bold/italics/underline/strikethrough/subscript/superscript/bg/fg/size/font
* [x] Functions to set style
* [x] Right-click menu to set style - moved to #430
* [x] Search option
* [x] Implement independent font for each text, with tags for different styles.
Links:
* http://effbot.org/tkinterbook/text.htm
* https://www.tutorialspoint.com/python/tk_text.htm

**Comment by maestroi** [comment]
Can you also make it asc or desc, for now if put text inside with app.setTextArea("Log", text) it wil do the oldest at last

**Comment by jarvisteach** [comment]
Have made one major change to TextArea - `.setTextArea()` now appends text to the end.

If you want to keep the original functionality, you'll need to set the`end` flag to be False

**Comment by jarvisteach** [comment]
TextAreas currently wrap lines by splitting words - would be nice to have the option to wrap on spaces...

According to: http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/text.html

There is a `wrap` config that can be set:
* the default behavior, wrap=tk.CHAR, any line that gets too long will be broken at any character.
* set wrap=tk.WORD and it will break the line after the last word that will fit.

**Comment by MessuKilkain** [comment]
I started to use appJar and I am truly satisfied for what I want to do: write quick and simple GUI for my little scripts. I also come from other languages and am used to Camel case.
Being mostly a programmer, I use python for programming tools.
A nice feature for TextArea would be to have option to enable syntax highlighting. Since it is a not so easy to implement feature, I just drop it here without any urge to have it.
By the way, great job.

**Comment by jarvisteach** [comment]
Hi @MessuKilkain - I've had a quick look into this, and there are a few options.

It's easy enough to create `tags` - settings for parts of the text.
Then you just have to tell the text widget where to apply those tags.

I'll add functions to create tags & tag a range as well as a string.

To then create a syntax highlighter, I guess you;d just need to define your tags, and some arrays of strings to apply those tags to. Then keep checking the text area for any matches...

**Comment by jarvisteach** [comment]
@MessuKilkain - OK I've added three functions:
* `.tagtextArea(title, **kwargs)` - create the named tag, with the specified arguments
* `.tagTextAreaPattern(title, tag, pattern, regexp=False)` apply a previously made tag to the specified pattern (set `regexp` to True if you want to use a regular expression)
* `.tagTextAreaRange(title, tag, start, end)` - apply a previously made tag to the specified range

**Comment by MessuKilkain** [comment]
Thank you a lot. I don't know yet when I will be able to test that for my little projet but this seems really promising. Good job.

**Comment by MessuKilkain** [comment]
@jarvisteach Ok, I tried the tags for what I wanted to do and it does that pretty well with a wise use of regexp. The only down, for now, to my opinion is that to clear the tags, you have to apply a clear tag to all the textArea (or maybe I didn't find the right function). I know I can use directly the tkinter widget bu it would be great to just call a function like clearTagTextArea(title) or removeTagTextArea(title, tag).

**Comment by jarvisteach** [comment]
Happy to add those features - do you want the put the code for them here? Or, you could issue a PR against the next_release branch...

**Comment by MessuKilkain** [comment]
The next_release branch is good for me. I already use it.

**Comment by jarvisteach** [comment]
The following functions should be implemented:
* `tag_names()` gets a list of all tags
* `tag_remove(start_pos, stop_pos)` removes the tag from any text between the two positions
* `tag_delete(*tag_names)` removes the tag from the text and also removes the definition of the tag

There is also a `SEL` tag, referring to the current selected text.

So a `tag_selected` could be implemented using `SEL_FIRST` & `SEL_LAST` as the positions.

**Comment by jarvisteach** [comment]
A simple search option can be implemented as well:
```python
start = 1.0
while True:
    pos = text.search("o", start, stopindex=END)
    if not pos:
        break
    print pos
    start = pos + "+1c"
```

`stopindex` tells it not to wrap.
`backwards=True` will search backwards (start at END, set stopindex to 1.0, use **-1c**)

**Comment by jarvisteach** [comment]
@MessuKilkain - multiple functions now implemented for tagging.
The naming has also been changed for all tag functions:
* textAreaCreateTag()
* textAreaChangeTag()
* textAreaDeleteTag()
* textAreaTagPattern()
* textAreaTagRange()
* textAreaTagSelected()
* textAreaUntagRange()
* textAreaUntagSelected()
* textAreaToggleTagRange()
* textAreaToggleTagSelected()
* getTextAreaTags()
* getTextAreaTag()

There is also a search * highlight option.

**Comment by jarvisteach** [comment]
Would like to implement built-in tags for:
* normal
* bold
* italic
* bold_italic

These will have to be implemented as 4 different fonts.

Additional tags for:
* underline

**Comment by jarvisteach** [comment]
Have implemented the above font tags. Except, no NORMAL tag is necessary - just remove the tags already applied...

**Comment by Lithimlin** [comment]
Hey, quick question as I'm somewhat confused:
I want to replace the text in a `textArea`. For this I tried using the following code:

```
with gui("MyWidget", bg="lightblue") as app:
    app.text("ta", value=get_corpus(), scroll=True)
[...]
    app.text("corpus", value=get_corpus(), end=False)
```
However, this only prepends the text. How do I remove the old text?
