### ISSUE TITLE
Call a function when the Selected Item in a list change

### ISSUE THREAD

**Issue by Kodac** [jarvisteach/appJar#76]
It would be great if, like for the RadioButtons we could call a function when the selected item from a list changes.
Thank You

**Comment by jarvisteach** [comment]
Had a quick look into this, super easy to implement:
 - the function already exists (.setListBoxFunction) - there's just no property **command** to bind to

However, there is a virtual event to bind to:
 - <<ListboxSelect>>

Will include in the next release.

**Comment by jarvisteach** [comment]
This is now implemented & will be in the next release.
