### ISSUE TITLE
Generating a Menu

### ISSUE THREAD

**Issue by maestroi** [jarvisteach/appJar#77]
I have the following problem:

appJar version: 0.3
Python: 2.7.11

```
app.addMenuItem("File", "File", func=None, shortcut=None, underline=-1)
app.addMenuItem("Info", "About", func=None, shortcut=None, underline=-1)
app.getMenuCheckBox("Info", "About")
```

Gives the error:
  ```
  if not newItem and item not in items: raise ItemLookupError("Invalid key: "+ item + " does not exist")
appJar.appjar.ItemLookupError: Invalid key: InfocbAbout does not exist 
```

**Comment by jarvisteach** [comment]
You've created two top-level menus (File & Info) each with a sub-menu (File & About) - these haven't been linked to any function.

You then try to get the state of a menu check box (info, about) - but there is no check box called info-about, only a menu item.

You'll need to change the 2nd line to be:
   app.addMenuCheckBox("Info", "About", ...)
If you want to use it as a checkbox...
