### ISSUE TITLE
Calling menu

### ISSUE THREAD

**Issue by maestroi** [jarvisteach/appJar#79]
Calling `.addMenu(menu, function, shortcut=None, underline=-1)`
with defined function will call function on startup on application not on click.

**Comment by jarvisteach** [comment]
I'm unable to reproduce this - could you let me know what platform/python version you're using?

The .addMenu function uses the same method to link functions to widgets that everything else does, and they all seem to work fine, so I can't see where this would fall down.

**Comment by jarvisteach** [comment]
Closing as can't reproduce
