### ISSUE TITLE
No module named 'idlelib.TreeWidget'

### ISSUE THREAD

**Issue by kennyngston** [jarvisteach/appJar#80]
Fresh install.

Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import appJar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\appJar\__init__.py", line 2, in <module>
    from appJar.appjar import gui
  File "C:\Python\Python36\lib\site-packages\appJar\appjar.py", line 39, in <module>
    from idlelib.TreeWidget import TreeItem, TreeNode
ModuleNotFoundError: No module named 'idlelib.TreeWidget'
>>>

**Comment by maestroi** [comment]
you need to install tinkert it will solve the problem, are you using linux ?
and what destro?

**Comment by kennyngston** [comment]
I'm using windows 8 64 bit, the installation came from python's website: python-3.6.0-amd64
As far as I know tkinter is included in python by default (at least I didn't install it separately)

>>> import tkinter
>>> import appJar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python36\lib\site-packages\appJar\__init__.py", line 2, in <module>
    from appJar.appjar import gui
  File "C:\Python\Python36\lib\site-packages\appJar\appjar.py", line 39, in <module>
    from idlelib.TreeWidget import TreeItem, TreeNode
ModuleNotFoundError: No module named 'idlelib.TreeWidget'
>>>

**Comment by DSMTurboAWD** [comment]
I am having this issue as well, and tk is installed and tested working.
From python console:
`import tkinter`
`tkinter._test()`

tests OK, but still having issues running any appJar code
Windows 10. I have not tried it on my Linux box yet

**Comment by gthreepwood** [comment]
Same here, Windows 10 and python 3.6 amd64.

**Comment by maestroi** [comment]
Did you guys tried it with python 2.7?
I am using python 2.7.12

**Comment by DSMTurboAWD** [comment]
I was actually able to fix this by changing to the 3.5 interpreter for my project. I have not tried to force it to work in 3.6 but it does work in 3.5

**Comment by jarvisteach** [comment]
3.6 not currently supported - there have been some changes to the idlelib widgets in the 3.6 release that need incorporating - will be looking into this over the next few days.

**Comment by jarvisteach** [comment]
New release available to install.
