### ISSUE TITLE
Negative numbers with .addNumericEntry

### ISSUE THREAD

**Issue by jacobthetechy** [jarvisteach/appJar#81]
When an entry is .addNumericEntry you can not use an negative or a period before typing in an number. What you have to do it type your number then either use the arrow keys or click at the beginning of the entry form and then add "-" or "." .

**Comment by jarvisteach** [comment]
I've had a quick look - the characters are accepted in the character validation, but it then tries to cast the contents of the entry as a float every time you type a character.

Having just a minus or decimal point, or both throws an exception as they're not valid floats.

However, you're right they should be allowed - I'll add in specify use cases to allow those three combinations.

**Comment by jarvisteach** [comment]
Will be fixed in next release

**Comment by jacobthetechy** [comment]
What is the next release, if you dont mind me asking?

**Comment by jarvisteach** [comment]
I'll hopefully be able to push one out over the weekend.

**Comment by jarvisteach** [comment]
New version released.
