### ISSUE TITLE
Ability to select a container to add widgets to

### ISSUE THREAD

**Issue by jarvisteach** [jarvisteach/appJar#83]
Once the GUI is up and running, there is a requirement to dynamically create new widgets.

It's possible to hide/delete existing widgets. But, if widgets are added - they'll be added to the topLevel container at the end (or over the top of existing /removed widgets).

It should be possible to select a container, remove all widgets from it, and add widgets to it.

A simple call - `openContainer(type, name)` - could be provided to allow widgets to be added to the relevant container. 
`removeAllWidgets()` should then only apply to the current container and its children...

**Comment by jacobthetechy** [comment]
Just tested this on version 0.042 and .openLabelFrame() does not put the added widgets into the frame border

**Comment by jarvisteach** [comment]
As mentioned in issue (#98) the website is out of sync with the release cycle - it's being updated from the development build (next_release branch). This will hopefully be resolved with the next release (0.05) - which is scheduled for the end of the month.

If you want access to the 0.05 features, you can switch to the next_release branch and download the appjar.py file, and replace your existing one...

**Comment by jarvisteach** [comment]
Currently, it's not possible to create empty containers - as there was no way to reopen them, there was never a use case for this. It does seem that this is something desirable, now that containers can be opened later and modified... I'll raise this as a new feature request.

**Comment by jacobthetechy** [comment]
this is the code im testing with for the open container

```
from appJar import gui

def addFileSettings(bn):
    app.openLabelFrame('Test')
    for s in range(int(app.getEntry('sets'))):
        for o in range(int(app.getSpinBox('set_options'))):
            row = app.getRow()
            app.addLabelOptionBox('Set {} Option {}'.format(s + 1, o + 1),
                                  ['--','OC','HS'], row, 0)
            app.addNumericEntry('set_{}_{}'.format(s, o), row, 1)
            app.setEntryDefault('set_{}_{}'.format(s, o), '.006')
            app.setEntryWidth('set_{}_{}'.format(s, o), 9)
        if s < int(app.getEntry('sets')) - 1:
            app.addHorizontalSeparator(colour = None)
    app.stopLabelFrame()

def addFileSettings2(bn):
    app.startLabelFrame('Test2')
    for s in range(int(app.getEntry('sets'))):
        for o in range(int(app.getSpinBox('set_options'))):
            row = app.getRow()
            app.addLabelOptionBox('2Set {} Option {}'.format(s + 1, o + 1),
                                  ['--','OC','HS'], row, 0)
            app.addNumericEntry('2set_{}_{}'.format(s, o), row, 1)
            app.setEntryDefault('2set_{}_{}'.format(s, o), '.006')
            app.setEntryWidth('2set_{}_{}'.format(s, o), 9)
        if s < int(app.getEntry('sets')) - 1:
            app.addHorizontalSeparator(colour = None)

app=gui()

app.addLabelEntry('sets')
app.startLabelFrame('Test')
row = app.getRow()
app.addLabel('Options', 'Options per Set', row, 0)
app.addSpinBoxRange('set_options', 1, 3, row, 1)
app.setSpinBoxWidth('set_options', 10)
app.stopLabelFrame()

app.addButton('Next', addFileSettings)
app.addButton('Next2', addFileSettings2)
app.go()
```

Pressing Next2 is what i want to get when pressing next. What am I doing wrong?

**Comment by jarvisteach** [comment]
Having a quick look, I think there's a bug in getRow when you open a container. getRow is returning 0 when you open the labelFrame, causing it to overwrite the existing widgets, instead of returning what would have been the nextRow.

If you manage your own row counter your may have more success, initialise it to 0, then add 2 at the beginning of each iteration.

**Comment by jarvisteach** [comment]
In fact, all container settings get lost when you reopen a container.
Need to change implementation - cache old container settings.

__removeContainer() should pop the top item, but add it to a cache
__openContainer() will then reload the cached dictionary and add it back to the stack

**Comment by jarvisteach** [comment]
Have updated next_release to retain config options.
