### ISSUE TITLE
Issues packing into Windows EXE

### ISSUE THREAD

**Issue by DSMTurboAWD** [jarvisteach/appJar#84]
I am not certain if this is an issue with appJar or an issue with the EXE creator (Pyinstaller) but my appgui.py program works great in the IDE and when executing python appgui.py 
However, when I pack the script into an EXE, I get an exception running the script related to the appJar favicon... stuff.
Again, I apologize if this is not in the right place, or if I should post on pyinstaller, I am just trying to figure out what is choking where.

Here is the console output when running the script:

```
C:\Users\_User_>C:\temp\fileCreatorGUI\fileCreatorGUI.exe
Traceback (most recent call last):
  File "F:\Users\_User_\python_working\fileCreatorGUI.py", line 73, in <module>
    app = gui()
  File "C:\Users\_User_\AppData\Local\Programs\Python\Python35\lib\site-packages\appJar\appjar.py", line 509, in __init__
    self.topLevel.wm_iconbitmap(self.appJarIcon)
  File "C:\Users\_User_\AppData\Local\Programs\Python\Python35\lib\tkinter\__init__.py", line 1716, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "C:\temp\fileCreatorGUI\appJar\resources\icons\favicon.ico" not defined
Failed to execute script fileCreatorGUI
```

I can supply the full source if necessary, though it does not seem to be blowing up inside my actual script.

**Comment by DSMTurboAWD** [comment]
NOTE:
Packing into an EXE on Linux works perfectly without issue, and script can be executed without issue

**Comment by jarvisteach** [comment]
Interesting, have never tried packing into an executable!

The error looks to be that appJar is trying to load the default appJar icon, but can't find it. I would guess that Pyinstaller hasn't included the resources folder? You could try adding resources/icons/favicon.bmp to however the packaging process works.

appJar only adds a default icon on Windows, as Mac/Linux work in a slightly different way...

An alternative, would be to comment out lines 508/509 in appjar.py, to disable the icon

**Comment by jarvisteach** [comment]
Feature request - should be possible to disable default icon on Windows, maybe it should be disabled by default, as it's not set on other platforms.

**Comment by DSMTurboAWD** [comment]
Commenting out the lines fixed it.
There is a function in Pyinstaller that does allow you to add paths to the packaging process but even adding it explicitly, it still choked. I am not certain why, though I have not beat on it anymore to find out.

**Comment by jacobthetechy** [comment]
I had this issue yesterday coincidentally, and fixed it by commenting out lines 349 & 350.

The error I had gotten was this.
```
Traceback (most recent call last):
  File "<string>", line 204, in <module>
  File "site-packages\appJar\appjar.py", line 350, in __init__
  File "lib-tk\Tkinter.py", line 1694, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\jpooler\Projects\SENSOR~1\dist\app\appJar\resources\icons\favicon.ico" not defined
app returned -1
```

Tho I was using python 2.7.

**Comment by jarvisteach** [comment]
New version released (0.041) with error handling for missing windows icon

**Comment by marks** [comment]
@DSMTurboAWD / @jarvisteach  - how were you packaging into a exe and whats the right way to do this for Mac .app files?

**Comment by DSMTurboAWD** [comment]
@marks http://www.pyinstaller.org/
It works in Linux, so in theory it will work in MacOS
