### ISSUE TITLE
Importing matplotlib.pyplot crashes the app on MacOS

### ISSUE THREAD

**Issue by Adam93MT** [jarvisteach/appJar#91]
Importing only `matplotlib` is fine, but the app crashes when importing `matplotlib.pyplot`

**Comment by jarvisteach** [comment]
Could you log the error message, and a sample of code you're using.

**Comment by jarvisteach** [comment]
I've done a bit of digging - seems this is an issue between matplotlib and tkinter

[This link](http://stackoverflow.com/questions/32019556/matplotlib-crashing-tkinter-application) discusses how to fix it:
```
import matplotlib
matplotlib.use("TkAgg")
from matplotlib import pyplot as put
```

**Comment by jarvisteach** [comment]
I'm going to close this, as it's not an issue with appJar.

But, I will raise a feature request, to include basic support for MatPlotLib.
