### ISSUE TITLE
method to get all text box Entries (like .getEntry('entry_title)  as list or dictionary...

### ISSUE THREAD

**Issue by stcorry** [jarvisteach/appJar#92]
It would be awesome if we could get a method to get all of the entry values as a dictionary so that we can easily hand over all values to the helper functions...

**Comment by jarvisteach** [comment]
I'll look into this - should be fairly simple.

There are already two built-in dictionaries that you can access directly:  
 * ```n_entries``` - contains all the entry widgets, indexed by name.
 * ```n_entryVars``` - contains all the entry widgets' StringVars, indexed by name.

So, in your helper function, you could include a line of code like this:
```
print ( app.n_entryVars [ "entry1"].get() )
```

Although, that does the same as:
```
print ( app.getEntry ( "entry1" ) )
```

**Comment by jarvisteach** [comment]
Wrapper function to return all entry values as a dictionary.
Loop through each entry in either of the above - not sure which is more efficient.
And add it to a dictionary, using the dictionary key.
