### ISSUE TITLE
TypeError when using .textBox(title, message)

### ISSUE THREAD

**Issue by elbows82** [jarvisteach/appJar#93]
When attempting to execute this code:
```
app = gui()
a = app.textBox("Enter remark", "test")
print a
```

I get the following error:
```
Traceback (most recent call last):
  File "C:/Users/Joe/PycharmProjects/Tooldit/test.py", line 4, in <module>
    a = app.textBox("Enter remark", "test")
  File "C:\Python27\lib\appJar\appjar.py", line 6123, in textBox
    return TextDialog(self.topLevel, title, question).result
  File "C:\Python27\lib\appJar\appjar.py", line 8194, in __init__
    super(TextDialog, self).__init__(parent, title, question)
TypeError: super() argument 1 must be type, not classobj
```

The code works fine if the questionBox() funtion is used instead:
```
app = gui()
a = app.questionBox("Enter remark", "test")
print a
```

**Comment by jarvisteach** [comment]
This is a bug with support for Python2. ```TextDialog``` and ```NumDialog``` are additional dialogs, added on top of the basic tkinter dialogs. Unfortunately - they were developed in Python3 and don't (currently) support Python2.

I'll update their constructors to check the version of Python, and make sure they work in both, I'll try to push out a minor fix for that in the next couple of days.

**Comment by jarvisteach** [comment]
Version 0.042 released
