### ISSUE TITLE
Showcase is not running under Python 2.7

### ISSUE THREAD

**Issue by mubed** [jarvisteach/appJar#95]
![2017-02-09 13_45_24-python 2 7 13 shell](https://cloud.githubusercontent.com/assets/694738/22784299/d22712de-eecf-11e6-885f-8f7e6c7c96c5.png)

**Comment by jarvisteach** [comment]
This is an issue with the bundled png library not being able to read the icon images.

Ideally, Id like to get the png library to work properly in 2.7, but in the short term I will look at changing the toolbar to not load images...

**Comment by jarvisteach** [comment]
Version 0.042 released
