### ISSUE TITLE
Textarea font and size

### ISSUE THREAD

**Issue by xircon** [jarvisteach/appJar#96]
Is there any way to set the font and size in a textarea?

**Comment by Shooshka** [comment]
http://appjar.info/pythonGuiOptions/

**Comment by xircon** [comment]
That controls font size of all widgets, not just the text area.

I found get XXX Widget which may do it, modifying the base tkinter widget, but no examples...............

**Comment by jarvisteach** [comment]
You know, I was thinking about this the other day.
You're right, appJar doesn't support addressing individual widgets to set their font.
For now, as you've said, you can use:
```
app.addTextArea("ta1")
ta = app.getTextAreaWidget("ta1")
ta.config(font="Courier 35")
```

I'm planning a whole piece of work to give better font/fg/bg support as well as improved documentation on how to modify fonts - I'll raise that as a change request.

You can also have a look at: [Effbot's font info](http://effbot.org/tkinterbook/tkinter-widget-styling.htm#font-names)

**Comment by xircon** [comment]
Thanks! Was struggling with the syntax for the getXXXWidget function, nearly got it, but nearly is a million miles away :D
