### ISSUE TITLE
Question about website and current version.

### ISSUE THREAD

**Issue by jacobthetechy** [jarvisteach/appJar#98]
Current version that is able to be down loaded is 0.042 per a `pip search apjar.`  Website says version 0.05 is out.

**Comment by jarvisteach** [comment]
Yes, sorry - the website reflects the current development branch, not the current release. That's a mistake on my part... If you want to get the current development build, switch to the next_release branch and copy the appjar.py file. I'm hoping to release 0.5 by the end of the month...
